### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference on executeTemplate

### ISSUE THREAD

**Issue by frimuchkov** [argoproj/argo-workflows#8968] opened 2022-06-15 07:30 UTC
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

Workflow-controller panics suddenly, and once the panic occurs, it continues.

What version are you running?
3.3.6, I've updated from 3.0.0-rc8 and there wasn't any problem with the previous version
## Diagnostics

```
runtime error: invalid memory address or nil pointer dereference

goroutine 346 [running]:
runtime/debug.Stack()
   /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2()
   /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:194 +0xd4
panic({0x1cdf7e0, 0x336f3e0})
   /usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc008b67740, {0x22af168, 0xc00005a018}, {0xc0096f7180, 0x47}, {0x228fc10, 0xc016869a40}, 0x1, {{0xc00186c160, 0x1, ...}, ...}, ...)
   /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1947 +0x2f13
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc008b67740, {0x22af168, 0xc00005a018}, 0xc0165ccf50, {0xc0163e12e0, 0x10})
   /go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:513 +0x1888
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAG(0xc008b67740, {0x22af168, 0xc00005a018}, {0xc01381de00, 0x0}, 0xc01656e2c0, {0xc0165727b0, 0x23}, 0xc016687d40, {0x228fc10, ...}, ...)
   /go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:244 +0x433
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc008b67740, {0x22af168, 0xc00005a018}, {0xc01381de00, 0x36}, {0x228fc10, 0xc016684f00}, 0x0, {{0x0, 0x0, ...}, ...}, ...)
   /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1885 +0x232c
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc008b67740, {0x22af168, 0xc00005a018}, 0xc014adf340, {0xc014ac18d0, 0xf})
   /go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:513 +0x1888
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAG(0xc008b67740, {0x22af168, 0xc00005a018}, {0xc016572330, 0x0}, 0xc01656e0c0, {0xc016572450, 0x23}, 0xc016575200, {0x228fc10, ...}, ...)
   /go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:244 +0x433
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc008b67740, {0x22af168, 0xc00005a018}, {0xc016572330, 0x26}, {0x228fc10, 0xc0165454a0}, 0x0, {{0x0, 0x0, ...}, ...}, ...)
   /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1885 +0x232c
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc008b67740, {0x22af168, 0xc00005a018}, 0xc01455aa10, {0xc011d655c2, 0x8})
   /go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:513 +0x1888
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc008b67740, {0x22af168, 0xc00005a018}, 0xc01455aa10, {0xc015b20314, 0x13})
   /go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:438 +0x1f25
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc008b67740, {0x22af168, 0xc00005a018}, 0xc01455aa10, {0xc01453b158, 0x17})
   /go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:438 +0x1f25
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAG(0xc008b67740, {0x22af168, 0xc00005a018}, {0xc00a49ca20, 0x0}, 0xc013bedf80, {0xc013e8dbc0, 0x23}, 0xc01456ed80, {0x2290ea0, ...}, ...)
   /go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:244 +0x433
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc008b67740, {0x22af168, 0xc00005a018}, {0xc00a49ca20, 0x1d}, {0x2290ea0, 0xc0139eccc0}, 0x8ace20, {{0x0, 0x0, ...}, ...}, ...)
   /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1885 +0x232c
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc008b67740, {0x22af168, 0xc00005a018})
   /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:350 +0x16a8
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc000101800, {0x22af168, 0xc00005a018})
   /go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:749 +0x8ee
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0x0)
   /go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:671 +0x9e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f02e474d578)
   /go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x647451486231466d, {0x226c720, 0xc008d49620}, 0x1, 0xc000225f20)
   /go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x646835575a794a43, 0x3b9aca00, 0x0, 0x58, 0x5975566d63697769)
   /go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x497a524864747332, 0x5975566d63697769, 0x6570314364735658)
   /go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:90 +0x25
created by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).Run
   /go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:295 +0x1a6c
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by juliev0** [comment] 2022-06-16 19:01
Also, does this happen every time or no?

**Comment by juliev0** [comment] 2022-06-17 23:16
@frimuchkov Can you please provide a Workflow that I can use to reproduce this?

**Comment by frimuchkov** [comment] 2022-06-19 11:08
> Also, does this happen every time or no?

No, it happens every time in a while
We downgraded it to 3.3.0 and there is no such error anymore


> @frimuchkov Can you please provide a Workflow that I can use to reproduce this? Also, it seems like this crash occurs during some retry logic. If you happen to have a log file that would help too.

It's WF with the client's data and there is no guarantee error will appear again :(

I thought, maybe there is some obvious moment in code on this line

**Comment by juliev0** [comment] 2022-06-19 14:02
@frimuchkov  Are you not able to identify which Workflow it is? Or are you concerned about the data being private? Just wondering if you can provide a generic version of the Workflow plus any underlying WorkflowTemplate so I can get an idea of what settings are being used? What I can guess about the Workflow is that maybe based on the stack trace, it's some nested DAG - is it perhaps a DAG which uses a DAG, which uses a third DAG? (or otherwise, I'm misinterpreting the stack) Also, there must be a RetryStrategy set in the Workflow but it would be good to have details.

The crash occurs on [this](https://github.com/argoproj/argo-workflows/blob/v3.3.6/workflow/controller/operator.go#L1947) line, but I can't tell from that if it occurs because of 'retryNode' or 'node' being nil. And I'm not sure which logic was executed above that to cause one of them to be nil. 

If I can't come up with something, I may just add a check there for either of those being nil, and if so, logging information about the Workflow which could provide clues.

**Comment by juliev0** [comment] 2022-06-22 15:11
@frimuchkov I just added some checks for nil and some additional logging [here](https://github.com/argoproj/argo-workflows/pull/9010), and it's been merged into master. If you have time, it would be great to know what's happening on your side with this latest change. Are you able to run with latest master?

**Comment by juliev0** [comment] 2022-06-23 15:06
Closing this - need to look for newly added logging to determine root cause of the issue.

**Closed by juliev0** 2022-06-23 15:06 UTC
Labels: bug, regression, triage

**Comment by frimuchkov** [comment] 2022-07-25 20:10
@juliev0 hi! Sorry for this huge delay. We can't catch this problem after upgrading to 3.3.8
Looks like fixed, thanks a lot :)
