### ISSUE TITLE
Quickstart: transport: authentication handshake failed

### ISSUE THREAD

**Issue by jmclean-starburst** [argoproj/argo-workflows#7632] opened 2022-01-25 12:56 UTC
## Summary

What happened/what you expected to happen?
When connecting to the UI of Argo Workflows (after port forwarding), I receive this message and virtually no components load:
```
Service Unavailable: connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority"
```

What version of Argo Workflows are you running?
latest (ie 3.2.6)

## Diagnostics
Quickstart Guide - follow steps in guide to reproduce

What Kubernetes provider are you using?
EKS/Minikube

Configuration:
```yaml
    spec:
      containers:
      - args:
        - server
        - --namespaced
        - --auth-mode
        - server
        - --auth-mode
        - client
        - --insecure-skip-verify
        - "true"
```

kustomization.yaml
```yaml
resources:
  - namespace.yml
  - https://raw.githubusercontent.com/argoproj/argo-workflows/v3.2.6/manifests/quick-start-minimal.yaml

namespace: argo-workflows
```

![image](https://user-images.githubusercontent.com/72760973/150980729-23a15247-ddea-4ddd-bfff-c13a9a5d4934.png)

> Note: This is reproducible w/ the minimal quickstart via minikube as well
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by materkey** [comment] 2022-01-25 13:24
I also have this issue

**Comment by materkey** [comment] 2022-01-25 13:44
argo-server seems to respond with 503 but can't see it in argo-server pod logs even with -v flag

**Comment by materkey** [comment] 2022-01-25 13:58
I've ended up by using `--secure=false`as a workaround. Also deleted `nginx.ingress.kubernetes.io/backend-protocol: https`

**Comment by jmclean-starburst** [comment] 2022-01-25 14:10
@materkey I have done this in the past...its just kind of annoying to update the readiness probe, add a new flag to server start, update ingress; This definitely needs to be resolve by the Argo team bc any new user of workflows is going to be put off by these errors. I have used the quickstart it he past without any issues...so this seems a bit wonky.

**Comment by jmclean-starburst** [comment] 2022-01-25 14:41
I believe I found the issue; the argo CLI is using `latest` for the image tag, instead of specifying the version tag (ie `v3.2.6`). I have tested this w/ v3.1.15 and after changing the image tag, it works. I will now validate same for version 3.2.6

**Comment by jmclean-starburst** [comment] 2022-01-25 14:49
I was able to fix this by patching the image off of `latest`
```yaml
resources:
  - namespace.yml
  - https://raw.githubusercontent.com/argoproj/argo-workflows/v3.2.6/manifests/quick-start-minimal.yaml

images:
- name: quay.io/argoproj/argocli
  newTag: v3.2.6

namespace: argo-workflows
```

**Comment by alexec** [comment] 2022-01-25 16:44
Please, you must use the manifests attached to the release:

```
kubectl create namespace argo
kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.2.6/install.yaml
```

**Comment by jmclean-starburst** [comment] 2022-01-25 16:50
@alexec I believe the quickstart guide is broken then, as the `latest` tag on argocli will spawn the issue mentioned by this bug

**Comment by alexec** [comment] 2022-01-25 23:15
I now think this might be bug.

**Comment by alexec** [comment] 2022-01-25 23:16
Maybe caused by:

72356abad fix: Allow self-signed Root CA for SSO. Fixes #6793 (#6961)

**Comment by alexec** [comment] 2022-01-25 23:23
Maybe

3614db690 feat: adding support for getting tls certificates from kubernetes secret (e.g. (#7621)

**Comment by alexec** [comment] 2022-01-25 23:24
@ChaosInTheCRD do you think your commit could have introduced this bug please?

**Comment by tachyus-ryan** [comment] 2022-01-26 01:39
I ran into this error after updating one of my clusters from GKE 1.19 to 1.20. I cannot seem to connect to argo-server since restarting deployments, no matter what I try.

**Comment by tachyus-ryan** [comment] 2022-01-26 15:21
> I was able to fix this by patching the image off of `latest`

This worked for me, too.

**Comment by 0xSQL** [comment] 2022-01-26 16:13
> Please, you must use the manifests attached to the release:
> 
> ```
> kubectl create namespace argo
> kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.2.6/install.yaml
> ```

This did it for me. I was using the quick start manifest instead of the release specific. That will have to be updated.

**Comment by andrein** [comment] 2022-01-26 16:51
> Please, you must use the manifests attached to the release:
> 
> ```
> kubectl create namespace argo
> kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.2.6/install.yaml
> ```

For kustomize users, it's much easier to reference the remote base from git. We tried to do this for the 3.2.6 tag and experienced the same issue. 

We've been doing the same with argo-cd for a while without issues. 

It look like they're overriding the images with the correct version when the git tag is created:
- https://github.com/argoproj/argo-cd/blob/v2.2.3/hack/update-manifests.sh
- https://github.com/argoproj/argo-cd/blob/v2.2.3/manifests/ha/base/kustomization.yaml

I found https://github.com/argoproj/argo-workflows/issues/2715 that seems related, @alexec can you reopen it to continue the kustomize discussion there?

**Comment by ChaosInTheCRD** [comment] 2022-01-26 17:47
@alexec it seems that yes, the problem has come from my PR, apologies for that. My suspicion is that it is related to the removal of [this line](https://github.com/argoproj/argo-workflows/pull/7621/files#diff-be34a0a09190a73bc32281a1fcbaf87126b3d61dd315f34c48cd3d8e044876a5L119), which I overlooked as I guess some process (I guess the UI) can't trust the self signed cert generated. I will investigate this further.

I guess though, the main thing to resolve right now is to ensure that this quickstart does not use the latest image. This way it can be ensured that prerelease bugs like this don't hinder users.

As for the error itself, can I get some clarity on what is resolving the error? Is it directly from the ui or is there something else involved (e.g. API).

**Comment by alexec** [comment] 2022-01-26 17:58
This issues is a blocker or v3.3, which we'd hoped to release this week. If you don't have time to look into this, I suggest we revert the commit.

**Comment by tachyus-ryan** [comment] 2022-01-26 18:02
> As for the error itself, can I get some clarity on what is resolving the error? Is it directly from the ui or is there something else involved (e.g. API).

I found that I could not submit workflows to the API, so this does not appear to be a UI-only issue. Ensuring `latest` was not used was the means of resolving the error for me.

**Closed** 2022-01-26 21:25 UTC
