### ISSUE TITLE
Archived workflows can't be searched by name anymore

### ISSUE THREAD

**Issue by paulfouquet** [argoproj/argo-workflows#12852] opened 2024-03-28 02:40 UTC
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Since the Archived Workflows have been unified to the Workflow main page, it is not possible to [search by name of prefix anymore ](https://github.com/argoproj/argo-workflows/pull/6801)

### Version

v3.5.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Any workflow
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by agilgur5** [comment] 2024-03-28 04:31
Duplicate of #12161

**Closed by agilgur5** 2024-03-28 04:31 UTC
Labels: type/bug, area/workflow-archive
