### ISSUE TITLE
workflow-of-workflows : waiting "child" workflow is not working

### ISSUE THREAD

**Issue by christopheblin** [argoproj/argo-workflows#6045] opened 2021-05-28 14:35 UTC
## Summary 

I try to use https://github.com/argoproj/argo-workflows/blob/master/examples/workflow-of-workflows.yaml

The child workflow is executed correctly. However, the parent fails to wait with a strange error (see the logs)

From my understanding, the problem is due to `Failing for conditions: status.phase in (Error,Failed)` with `index out of range [-1]` which is coming from the initial yaml as `failureCondition: "status.phase in (Failed, Error)"` 

However, this is directly from the provided example ->is this something wrong on my side or is this a bug ?

Here are the logs
```
time="2021-05-28T14:26:54.792Z" level=info msg="Starting Workflow Executor" executorType=k8sapi version=untagged
time="2021-05-28T14:26:54.796Z" level=info msg="Creating a K8sAPI executor"
time="2021-05-28T14:26:54.796Z" level=info msg="Executor initialized" includeScriptOutput=false namespace=staging-argo podName=dataset-all-in-coverage-2crft-3484945999 template="{\"name\":\"dataset-all-in-coverage-execute\",\"inputs\":{\"paramete
rs\":[{\"name\":\"coverage\",\"value\":\"fr-cor\"},{\"name\":\"dataset\",\"value\":\"ajaccio\"}]},\"outputs\":{},\"metadata\":{},\"resource\":{\"action\":\"create\",\"manifest\":\"\\napiVersion: argoproj.io/v1alpha1\\nkind: Workflow\\nmetadata:\\
n  generateName: dataset-\\nspec:\\n  workflowTemplateRef:\\n    name: dataset\\n  arguments:\\n    parameters:\\n    - name: dataset\\n      value: ajaccio\\n    - name: coverage\\n      value: fr-cor\\n\",\"successCondition\":\"status.phase ==
Succeeded\",\"failureCondition\":\"status.phase in (Failed, Error)\"},\"archiveLocation\":{\"archiveLogs\":true,\"s3\":{\"endpoint\":\"minio-az-gw:9000\",\"bucket\":\"argo\",\"insecure\":true,\"accessKeySecret\":{\"name\":\"argo-storage-secret\",
\"key\":\"accessKey\"},\"secretKeySecret\":{\"name\":\"argo-storage-secret\",\"key\":\"secretKey\"},\"key\":\"dataset-all-in-coverage-2crft/dataset-all-in-coverage-2crft-3484945999\"}}}" version="&Version{Version:untagged,BuildDate:2021-05-27T23:
52:25Z,GitCommit:73539fadbe81b644b912ef0ddddebb178c97cc94,GitTag:untagged,GitTreeState:clean,GoVersion:go1.15.7,Compiler:gc,Platform:linux/amd64,}"
time="2021-05-28T14:26:54.796Z" level=info msg="Loading manifest to /tmp/manifest.yaml"
time="2021-05-28T14:26:54.796Z" level=info msg="kubectl create -f /tmp/manifest.yaml -o json"
time="2021-05-28T14:26:55.794Z" level=info msg="Resource: staging-argo/Workflow.argoproj.io/dataset-2zlqn. SelfLink: "
time="2021-05-28T14:26:55.794Z" level=info msg="Starting SIGUSR2 signal monitor"
time="2021-05-28T14:26:55.795Z" level=info msg="Waiting for conditions: status.phase==Succeeded"
time="2021-05-28T14:26:55.795Z" level=info msg="Failing for conditions: status.phase in (Error,Failed)"
E0528 14:26:55.818725       1 runtime.go:78] Observed a panic: runtime.boundsError{x:-1, y:1, signed:true, code:0x0} (runtime error: index out of range [-1])
goroutine 1 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x2022ae0, 0xc000436b20)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/runtime/runtime.go:48 +0x89
panic(0x2022ae0, 0xc000436b20)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/argoproj/argo-workflows/v3/util/k8s.ParseRequest(0xc00070e400, 0xc00070e400, 0xc00084c090, 0x0, 0x0)
        /go/src/github.com/argoproj/argo-workflows/util/k8s/parse.go:45 +0x739
github.com/argoproj/argo-workflows/v3/util/logs.k8sLogRoundTripper.RoundTrip(0x245c400, 0xc00016b040, 0xc00070e400, 0x1e15c40, 0xc000714a01, 0xc00070c420)
        /go/src/github.com/argoproj/argo-workflows/util/logs/log-k8s-requests.go:19 +0xb2
k8s.io/client-go/transport.(*bearerAuthRoundTripper).RoundTrip(0xc00033c690, 0xc00070e300, 0x216157e, 0xa, 0xc00070c360)
        /go/pkg/mod/k8s.io/client-go@v0.19.6/transport/round_trippers.go:297 +0x271
k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip(0xc0001a3760, 0xc00070e200, 0xc0001a3760, 0xc0245d53ef659ab4, 0x7b1191738)
        /go/pkg/mod/k8s.io/client-go@v0.19.6/transport/round_trippers.go:159 +0x1d6
net/http.send(0xc00070e100, 0x245c1a0, 0xc0001a3760, 0xc0245d53ef659ab4, 0x7b1191738, 0x3235b80, 0xc000182020, 0xc0245d53ef659ab4, 0x1, 0x0)
        /usr/local/go/src/net/http/client.go:252 +0x453
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment] 2021-05-28 14:38
Related https://github.com/argoproj/argo-workflows/issues/5981. 

Could you paste the controller log as well?

**Comment by christopheblin** [comment] 2021-05-28 14:47
The relevant part of the logs (I hope this is the relevant part:))

```
time="2021-05-28T14:27:22.738Z" level=info msg="Processing workflow" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.739Z" level=info msg="Updating node dataset-all-in-coverage-2crft-3482325643 exit code 0" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.739Z" level=info msg="Setting node dataset-all-in-coverage-2crft-3482325643 outputs: {\"artifacts\":[{\"name\":\"main-logs\",\"s3\":{\"key\":\"dataset-all-in-coverage-2crft/dataset-all-in-coverage-2crft-3482325643/main.log\"}}]}" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.739Z" level=info msg="Updating node dataset-all-in-coverage-2crft-3482325643 status Running -> Succeeded" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.739Z" level=info msg="Running OnExit handler: onExit" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.741Z" level=info msg="Step group node dataset-all-in-coverage-2crft-1107239280 successful" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.741Z" level=info msg="node dataset-all-in-coverage-2crft-1107239280 phase Running -> Succeeded" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.741Z" level=info msg="node dataset-all-in-coverage-2crft-1107239280 finished: 2021-05-28 14:27:22.741242335 +0000 UTC" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.741Z" level=info msg="Outbound nodes of dataset-all-in-coverage-2crft-3561919422 is [dataset-all-in-coverage-2crft-3561919422]" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.741Z" level=info msg="Outbound nodes of dataset-all-in-coverage-2crft-3482325643 is [dataset-all-in-coverage-2crft-3482325643]" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.741Z" level=info msg="Outbound nodes of dataset-all-in-coverage-2crft-2061615214 is [dataset-all-in-coverage-2crft-3561919422 dataset-all-in-coverage-2crft-3482325643]" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.741Z" level=info msg="node dataset-all-in-coverage-2crft-2061615214 phase Running -> Succeeded" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.741Z" level=info msg="node dataset-all-in-coverage-2crft-2061615214 finished: 2021-05-28 14:27:22.741337736 +0000 UTC" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.741Z" level=info msg="Checking daemoned children of dataset-all-in-coverage-2crft-2061615214" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.741Z" level=info msg="Step group node dataset-all-in-coverage-2crft-3426888839 successful" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.741Z" level=info msg="node dataset-all-in-coverage-2crft-3426888839 phase Running -> Succeeded" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.741Z" level=info msg="node dataset-all-in-coverage-2crft-3426888839 finished: 2021-05-28 14:27:22.741395937 +0000 UTC" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.741Z" level=info msg="Outbound nodes of dataset-all-in-coverage-2crft-2061615214 is [dataset-all-in-coverage-2crft-3561919422 dataset-all-in-coverage-2crft-3482325643]" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.741Z" level=info msg="Outbound nodes of dataset-all-in-coverage-2crft-3170434411 is [dataset-all-in-coverage-2crft-3561919422 dataset-all-in-coverage-2crft-3482325643]" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.741Z" level=info msg="node dataset-all-in-coverage-2crft-3170434411 phase Running -> Succeeded" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.741Z" level=info msg="node dataset-all-in-coverage-2crft-3170434411 finished: 2021-05-28 14:27:22.741465838 +0000 UTC" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.741Z" level=info msg="Checking daemoned children of dataset-all-in-coverage-2crft-3170434411" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.741Z" level=info msg="Updated phase Running -> Failed" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.741Z" level=info msg="Updated message  -> child 'dataset-all-in-coverage-2crft-3484945999' failed" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.741Z" level=info msg="Marking workflow completed" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.741Z" level=info msg="Marking workflow as pending archiving" namespace=staging-argo workflow=dataset-all-in-coverage-2crft
time="2021-05-28T14:27:22.741Z" level=info msg="Checking daemoned children of " namespace=staging-argo workflow=dataset-all-in-coverage-2crft

```

**Comment by christopheblin** [comment] 2021-05-28 14:52
@terrytangyuan  as I said in the ticket :
> The child workflow is executed correctly.

Here is the relevant part I can see in the UI

![Capture d’écran 2021-05-28 à 16 52 19](https://user-images.githubusercontent.com/11044877/120002415-18350800-bfd5-11eb-9000-9bb983da255d.png)

**Comment by terrytangyuan** [comment] 2021-05-28 14:58
Okay I am able to reproduce. I'll look into it.

**Comment by terrytangyuan** [comment] 2021-05-28 15:01
Looks like your selfLink is missing:
```
time="2021-05-28T14:26:55.794Z" level=info msg="Resource: staging-argo/Workflow.argoproj.io/dataset-2zlqn. SelfLink:"
```

Are you running on k8s>=1.21? If so, I think this will be fixed in https://github.com/argoproj/argo-workflows/pull/6014.

**Comment by terrytangyuan** [comment] 2021-05-28 15:04
Could you check if your workflows have selfLink, e.g. `kubectl get -o json dataset-all-in-coverage-2crft-3484945999`?

**Comment by christopheblin** [comment] 2021-05-28 15:09
I am using Azure Kubernetes Services

Here is the output of the command 

[dataset-all-in-coverage-2crft-3484945999.json.txt](https://github.com/argoproj/argo-workflows/files/6561684/dataset-all-in-coverage-2crft-3484945999.json.txt)

I can not see any selfLink inside but as I do not know what they are I prefer to give you the full output

**Comment by alexec** [comment] 2021-06-02 15:28
Please add version affected.

**Comment by terrytangyuan** [comment] 2021-06-02 18:49
@alexec https://github.com/argoproj/argo-workflows/commit/ed957dd9cf257b1db9a71dcdca49fc38678a4dcb is the commit so v3.1.0-rc releases are affected (if k8s>=1.21 is used).

**Closed** 2021-06-02 18:53 UTC
Labels: bug
