### ISSUE TITLE
Metadata/Description for templates

### ISSUE THREAD

**Issue by ankitanallana** [argoproj/argo-workflows#1456] opened 2019-07-02 03:03 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature Request

A description/metadata field for templates would be helpful while writing template definitions. While YAML supports comments, a description field would be a convenient way to store/record some information about a template after a workflow has been submitted. Could be a single field or something like [`labels` ](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/)

**Comment by alexec** [comment] 2020-07-17 20:19
Duplicate of #2871.

**Closed by alexec** 2020-07-17 20:19 UTC
Labels: area/spec, solution/superseded
