### ISSUE TITLE
workflow controller panics when workflow parameter was not supplied

### ISSUE THREAD

**Issue by Bobgy** [argoproj/argo-workflows#5473] opened 2021-03-22 03:05 UTC
## Summary 

What happened/what you expected to happen?

I created a workflow.
It failed with
> runtime error: invalid memory address or nil pointer dereference
> time="2021-03-19T14:48:13.638Z" level=info msg="Processing workflow" namespace=kubeflow workflow=v2-sample-test-v586w
time="2021-03-19T14:48:13.638Z" level=error msg="Recovered from panic" namespace=kubeflow r="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 208 [running]:\nruntime/debug.Stack(0xc0588e65f5, 0x180bdc0, 0x29f4e30)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/argoproj/argo/v2/workflow/controller.(*wfOperationCtx).operate.func2(0xc0011f2240)\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:184 +0xbe\npanic(0x180bdc0, 0x29f4e30)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/argoproj/argo/v2/workflow/controller.(*wfOperationCtx).setGlobalParameters(0xc0011f2240, 0xc0002a70e0, 0x6, 0x6, 0x0, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:476 +0x66e\ngithub.com/argoproj/argo/v2/workflow/controller.(*wfOperationCtx).operate(0xc0011f2240)\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:229 +0x480\ngithub.com/argoproj/argo/v2/workflow/controller.(*WorkflowController).processNextItem(0xc000468a80, 0x0)\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:574 +0x828\ngithub.com/argoproj/argo/v2/workflow/controller.(*WorkflowController).runWorker(0xc000468a80)\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:496 +0x2b\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000a9c000)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.8/pkg/util/wait/wait.go:152 +0x5e\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000a9c000, 0x3b9aca00, 0x0, 0x1, 0xc0000a2b40)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.8/pkg/util/wait/wait.go:153 +0xf8\nk8s.io/apimachinery/pkg/util/wait.Until(0xc000a9c000, 0x3b9aca00, 0xc0000a2b40)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.8/pkg/util/wait/wait.go:88 +0x4d\ncreated by github.com/argoproj/argo/v2/workflow/controller.(*WorkflowController).Run\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:215 +0xa5d\n" workflow=v2-sample-test-v586w
time="2021-03-19T14:48:13.638Z" level=info msg="Updated phase  -> Error" namespace=kubeflow workflow=v2-sample-test-v586w
time="2021-03-19T14:48:13.638Z" level=info msg="Updated message  -> runtime error: invalid memory address or nil pointer dereference" namespace=kubeflow workflow=v2-sample-test-v586w

I'd expect it to fail with a meaningful error message. I tried the workflow on argo v2.7.5 and got a meaningful error message instead:
```
invalid spec: templates.v2-sample-test inputs.parameters.samples_destination was not supplied
```

## Diagnostics

What Kubernetes provider are you using? 
GCP
What version of Argo Workflows are you running? 
v2.12.9

Here's a minimal reproducible failure example, note you should use `kubectl create -f` to create this workflow, because `argo CLI` can correctly gives the error message:
```yaml
Paste a workflow that reproduces the bug, including status:
kubectl get wf -o yaml ${workflow} 
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2021-03-22T03:03:23Z"
  generateName: missing-parameter-
  generation: 2
  labels:
    workflows.argoproj.io/archive-strategy: "false"
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Error
  name: missing-parameter-zb8lg
  namespace: kubeflow
  resourceVersion: "117065224"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/kubeflow/workflows/missing-parameter-zb8lg
  uid: c90118ce-664f-440b-bd55-31c36a21034f
spec:
  arguments:
    parameters:
    - name: missing
  entrypoint: whalesay
  templates:
  - arguments: {}
    container:
      args:
      - hello world
      command:
      - cowsay
      image: docker/whalesay:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: whalesay
    outputs: {}
status:
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2021-03-22T03:03:23Z"
  message: 'runtime error: invalid memory address or nil pointer dereference'
  phase: Error
  progress: 0/0
  startedAt: "2021-03-22T03:03:23Z"
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Bobgy** [comment] 2021-03-22 03:08
For context, I was building a workflow with kubeflow pipelines, therefore when I submit it for execution, I won't use argo CLI. I'd expect workflow controller to be able to emit meaningful error message in this case too.

**Comment by terrytangyuan** [comment] 2021-03-22 14:36
@Bobgy Thanks. I submitted #5477 that should fix this and give more meaningful error messages.

**Comment by simster7** [comment] 2021-03-23 19:06
This has been fixed in [`v3.0.0-rc9`](https://github.com/argoproj/argo-workflows/releases/tag/v3.0.0-rc9)

**Comment by Bobgy** [comment] 2021-03-29 09:25
Thank you all!

May I ask for a cherry pick to v2 branch?

**Comment by vbarbaresi** [comment] 2021-03-29 13:39
I experience a similar error on `v3.0.0-rc9` but it happens randomly. I'm triggering the same `WorkflowTemplate` with similar parameters every 5 minutes, and the panic happens roughly 20% of the time.


> runtime error: invalid memory address or nil pointer dereference

```
goroutine 150 [running]:
runtime/debug.Stack(0xc072925a21, 0x1b6c980, 0x2c969c0)
\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2(0xc007f1f340, 0x20698a0, 0xc000056020)
\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:181 +0xd1
panic(0x1b6c980, 0x2c969c0)
\t/usr/local/go/src/runtime/panic.go:975 +0x47a
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).setGlobalParameters(0xc007f1f340, 0xc000452960, 0x3, 0x3, 0x0, 0x0, 0x0)
\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:504 +0x772
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc007f1f340, 0x20698a0, 0xc000056020)
\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:286 +0x3a65
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc0004a1500, 0x20698a0, 0xc000056020, 0x5372657473756c00)
\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:621 +0x7f0
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0xc0004a1500)
\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:546 +0x4f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000d8aea0)
\t/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000d8aea0, 0x201ee20, 0xc0004ff230, 0x2063657053205d01, 0xc00088c5a0)
\t/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000d8aea0, 0x3b9aca00, 0x0, 0x2066655265746101, 0xc00088c5a0)
\t/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc000d8aea0, 0x3b9aca00, 0xc00088c5a0)
\t/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:90 +0x4d
created by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).Run.func1
\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:255 +`0x505
 ```

I diffed the `Workflow` objects between to try to spot any difference

``` 
storedWorkflowTemplateSpec:
    arguments:
      parameters:
```
On the workflow that triggered the panic, my parameters seem to be missing from this field, despite being present in
```
spec:
  arguments:
    parameters:
```

**Comment by alexec** [comment] 2021-03-29 15:31
@sarabala1979 ?

**Comment by alexec** [comment] 2021-04-09 16:33
@sarabala1979 this is your code no?

**Comment by vbarbaresi** [comment] 2021-04-09 16:39
I didn't reproduce in the last week after upgrading to `v3.0.1`. So if you can't reproduce either, you can ignore my last comment

**Closed** 2021-04-09 16:46 UTC
Labels: bug

**Comment by Bobgy** [comment] 2021-04-10 01:31
> Thank you all!
> 
> May I ask for a cherry pick to v2 branch?

Friendly reminder, what's general criteria to cherry pick to v2?
