### ISSUE TITLE
3.5.5+: Workflow stuck Running when failed resource template

### ISSUE THREAD

**Issue by BarryOwensDigital** [argoproj/argo-workflows#13299] opened 2024-07-04 10:39 UTC
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

When running a workflow that includes a [Kubernetes Resource](https://argo-workflows.readthedocs.io/en/latest/walk-through/kubernetes-resources/) step, if that step fails the workflow is stuck in Running phase even while using `continueOn: error` and `continueOn: failed`.

This issue started occurring when we upgraded from v3.4.8 to v3.5.8. I have confirmed the issue is not preset on v3.4.8.
Edit: on further investigation the issue seems to have started since v3.5.6 (v3.5.5 is working fine) 

I have reproduced the issue using the latest image for the controller. 

Example workflow using `continueOn: failed`:
<img width="889" alt="image" src="https://github.com/argoproj/argo-workflows/assets/133855741/a9e83d61-30fd-4663-86cc-b5d6f11eb9d3">

#### Metadata present on the workflow stuck in the Running phase

The following labels are present on the Workflow: 
    `workflows.argoproj.io/completed: 'false'`
    `workflows.argoproj.io/phase: Running`

The following label is present on the WorkflowTaskResult:
  `workflows.argoproj.io/report-outputs-completed: 'false'`

The conditions have only one entry: `PodRunning: false` 
```yaml
progress: 1/2
taskResultsCompletionStatus:
    sligo-bug-2486207007: false
    sligo-bug-2605594679: true
```
 
All pods created for each step are removed from the namespace

The full yaml for the node running the kubernetes resource step is:
```yaml
    sligo-bug-2486207007:
      boundaryID: sligo-bug
      children:
        - sligo-bug-2988043323
      displayName: check-k8-resource
      finishedAt: '2024-07-04T09:49:44Z'
      hostNodeName: aks-default-65748190-vmss000008
      id: sligo-bug-2486207007
      message: Error (exit code 1)
      name: sligo-bug[0].check-k8-resource
      outputs:
        exitCode: '1'
      phase: Failed
      progress: 0/1
      resourcesDuration:
        cpu: 0
        memory: 2
      startedAt: '2024-07-04T09:49:39Z'
      templateName: check-mongo-ready
      templateScope: local/sligo-bug
      type: Pod
```

#### Comparison using container step instead of kubernetes resource step

If we replace the template for the kubernetes resource step `check-mongo-ready` with a container step such as `intentional-fail` taken from [examples](https://github.com/argoproj/argo-workflows/blob/main/examples/continue-on-fail.yaml) the workflow finishes fine (it does not get stuck in Running phase):

```yaml
  - name: intentional-fail
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo intentional failure; exit 1"]
``` 

### Version

v3.5.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

To avoid RBAC issues with this workflow, you need these permissions:
```yaml
  - verbs:
      - get
    apiGroups:
      - apps
    resources:
      - statefulsets
```

```YAML
metadata:
  name: sligo-bug
  namespace: argo-wf
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
      - - name: check-k8-resource
          template: check-mongo-ready
          arguments: {}
          continueOn:
            error: true
            failed: true
      - - name: B
          template: finish
          arguments: {}
  - name: check-mongo-ready
    resource:
      action: get
      manifest: |
        apiVersion: apps/v1
        kind: StatefulSet
        metadata:
          name: myapp-mongodb
      # we expect this to fail because the resource does not exist
      successCondition: status.readyReplicas > 0
      failureCondition: status.readyReplicas < 1
  - name: finish
    container:
      name: ''
      image: docker/whalesay:latest
      command:
        - cowsay
      args:
        - hello world; exit 0
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
```

### Logs from the workflow controller

```text
{"Phase":"","ResourceVersion":"1708512","level":"info","msg":"Processing workflow","namespace":"argo-wf","time":"2024-07-04T09:49:39.515Z","workflow":"sligo-bug"}
{"level":"info","msg":"Task-result reconciliation","namespace":"argo-wf","numObjs":0,"time":"2024-07-04T09:49:39.526Z","workflow":"sligo-bug"}
{"level":"info","msg":"Updated phase  -\u003e Running","namespace":"argo-wf","time":"2024-07-04T09:49:39.526Z","workflow":"sligo-bug"}
{"level":"warning","msg":"Node was nil, will be initialized as type Skipped","namespace":"argo-wf","time":"2024-07-04T09:49:39.526Z","workflow":"sligo-bug"}
{"level":"info","msg":"was unable to obtain node for , letting display name to be nodeName","namespace":"argo-wf","time":"2024-07-04T09:49:39.526Z","workflow":"sligo-bug"}
{"level":"info","msg":"Steps node sligo-bug initialized Running","namespace":"argo-wf","time":"2024-07-04T09:49:39.527Z","workflow":"sligo-bug"}
{"level":"info","msg":"StepGroup node sligo-bug-3055300894 initialized Running","namespace":"argo-wf","time":"2024-07-04T09:49:39.527Z","workflow":"sligo-bug"}
{"level":"warning","msg":"Node was nil, will be initialized as type Skipped","namespace":"argo-wf","time":"2024-07-04T09:49:39.527Z","workflow":"sligo-bug"}
{"level":"info","msg":"Pod node sligo-bug-2486207007 initialized Pending","namespace":"argo-wf","time":"2024-07-04T09:49:39.527Z","workflow":"sligo-bug"}
{"level":"info","msg":"Created pod: sligo-bug[0].check-k8-resource (sligo-bug-check-mongo-ready-2486207007)","namespace":"argo-wf","time":"2024-07-04T09:49:39.589Z","workflow":"sligo-bug"}
{"level":"info","msg":"Workflow step group node sligo-bug-3055300894 not yet completed","namespace":"argo-wf","time":"2024-07-04T09:49:39.589Z","workflow":"sligo-bug"}
{"level":"info","msg":"TaskSet Reconciliation","namespace":"argo-wf","time":"2024-07-04T09:49:39.589Z","workflow":"sligo-bug"}
{"level":"info","msg":"reconcileAgentPod","namespace":"argo-wf","time":"2024-07-04T09:49:39.589Z","workflow":"sligo-bug"}
{"level":"info","msg":"Workflow update successful","namespace":"argo-wf","phase":"Running","resourceVersion":"1708515","time":"2024-07-04T09:49:39.601Z","workflow":"sligo-bug"}
{"Phase":"Running","ResourceVersion":"1708515","level":"info","msg":"Processing workflow","namespace":"argo-wf","time":"2024-07-04T09:49:49.590Z","workflow":"sligo-bug"}
{"level":"info","msg":"Task-result reconciliation","namespace":"argo-wf","numObjs":1,"time":"2024-07-04T09:49:49.591Z","workflow":"sligo-bug"}
{"level":"info","msg":"task-result changed","namespace":"argo-wf","nodeID":"sligo-bug-2486207007","time":"2024-07-04T09:49:49.591Z","workflow":"sligo-bug"}
{"displayName":"check-k8-resource","level":"info","msg":"Pod failed: Error (exit code 1)","namespace":"argo-wf","pod":"sligo-bug-check-mongo-ready-2486207007","templateName":"check-mongo-ready","time":"2024-07-04T09:49:49.591Z","workflow":"sligo-bug"}
{"level":"info","msg":"node changed","namespace":"argo-wf","new.message":"Error (exit code 1)","new.phase":"Failed","new.progress":"0/1","nodeID":"sligo-bug-2486207007","old.message":"","old.phase":"Pending","old.progress":"0/1","time":"2024-07-04T09:49:49.591Z","workflow":"sligo-bug"}
{"level":"info","msg":"Step group node sligo-bug-3055300894 successful","namespace":"argo-wf","time":"2024-07-04T09:49:49.592Z","workflow":"sligo-bug"}
{"level":"info","msg":"node sligo-bug-3055300894 phase Running -\u003e Succeeded","namespace":"argo-wf","time":"2024-07-04T09:49:49.592Z","workflow":"sligo-bug"}
{"level":"info","msg":"node sligo-bug-3055300894 finished: 2024-07-04 09:49:49.592112732 +0000 UTC","namespace":"argo-wf","time":"2024-07-04T09:49:49.592Z","workflow":"sligo-bug"}
{"level":"info","msg":"StepGroup node sligo-bug-2988043323 initialized Running","namespace":"argo-wf","time":"2024-07-04T09:49:49.592Z","workflow":"sligo-bug"}
{"level":"info","msg":"SG Outbound nodes of sligo-bug-2486207007 are [sligo-bug-2486207007]","namespace":"argo-wf","time":"2024-07-04T09:49:49.592Z","workflow":"sligo-bug"}
{"level":"warning","msg":"Node was nil, will be initialized as type Skipped","namespace":"argo-wf","time":"2024-07-04T09:49:49.592Z","workflow":"sligo-bug"}
{"level":"info","msg":"Pod node sligo-bug-2605594679 initialized Pending","namespace":"argo-wf","time":"2024-07-04T09:49:49.592Z","workflow":"sligo-bug"}
{"level":"info","msg":"Created pod: sligo-bug[1].B (sligo-bug-finish-2605594679)","namespace":"argo-wf","time":"2024-07-04T09:49:49.614Z","workflow":"sligo-bug"}
{"level":"info","msg":"Workflow step group node sligo-bug-2988043323 not yet completed","namespace":"argo-wf","time":"2024-07-04T09:49:49.614Z","workflow":"sligo-bug"}
{"level":"info","msg":"TaskSet Reconciliation","namespace":"argo-wf","time":"2024-07-04T09:49:49.615Z","workflow":"sligo-bug"}
{"level":"info","msg":"reconcileAgentPod","namespace":"argo-wf","time":"2024-07-04T09:49:49.615Z","workflow":"sligo-bug"}
{"level":"info","msg":"Workflow update successful","namespace":"argo-wf","phase":"Running","resourceVersion":"1708590","time":"2024-07-04T09:49:49.629Z","workflow":"sligo-bug"}
{"action":"deletePod","key":"argo-wf/sligo-bug-check-mongo-ready-2486207007/deletePod","level":"info","msg":"cleaning up pod","time":"2024-07-04T09:49:54.631Z"}
{"Phase":"Running","ResourceVersion":"1708590","level":"info","msg":"Processing workflow","namespace":"argo-wf","time":"2024-07-04T09:49:59.616Z","workflow":"sligo-bug"}
{"level":"info","msg":"Task-result reconciliation","namespace":"argo-wf","numObjs":2,"time":"2024-07-04T09:49:59.618Z","workflow":"sligo-bug"}
{"level":"info","msg":"task-result changed","namespace":"argo-wf","nodeID":"sligo-bug-2486207007","time":"2024-07-04T09:49:59.618Z","workflow":"sligo-bug"}
{"level":"info","msg":"task-result changed","namespace":"argo-wf","nodeID":"sligo-bug-2605594679","time":"2024-07-04T09:49:59.618Z","workflow":"sligo-bug"}
{"level":"info","msg":"node changed","namespace":"argo-wf","new.message":"","new.phase":"Succeeded","new.progress":"0/1","nodeID":"sligo-bug-2605594679","old.message":"","old.phase":"Pending","old.progress":"0/1","time":"2024-07-04T09:49:59.618Z","workflow":"sligo-bug"}
{"level":"info","msg":"SG Outbound nodes of sligo-bug-2486207007 are [sligo-bug-2486207007]","namespace":"argo-wf","time":"2024-07-04T09:49:59.619Z","workflow":"sligo-bug"}
{"level":"info","msg":"Step group node sligo-bug-2988043323 successful","namespace":"argo-wf","time":"2024-07-04T09:49:59.620Z","workflow":"sligo-bug"}
{"level":"info","msg":"node sligo-bug-2988043323 phase Running -\u003e Succeeded","namespace":"argo-wf","time":"2024-07-04T09:49:59.620Z","workflow":"sligo-bug"}
{"level":"info","msg":"node sligo-bug-2988043323 finished: 2024-07-04 09:49:59.620324699 +0000 UTC","namespace":"argo-wf","time":"2024-07-04T09:49:59.620Z","workflow":"sligo-bug"}
{"level":"info","msg":"Outbound nodes of sligo-bug-2605594679 is [sligo-bug-2605594679]","namespace":"argo-wf","time":"2024-07-04T09:49:59.620Z","workflow":"sligo-bug"}
{"level":"info","msg":"Outbound nodes of sligo-bug is [sligo-bug-2605594679]","namespace":"argo-wf","time":"2024-07-04T09:49:59.620Z","workflow":"sligo-bug"}
{"level":"info","msg":"node sligo-bug phase Running -\u003e Succeeded","namespace":"argo-wf","time":"2024-07-04T09:49:59.620Z","workflow":"sligo-bug"}
{"level":"info","msg":"node sligo-bug finished: 2024-07-04 09:49:59.620749704 +0000 UTC","namespace":"argo-wf","time":"2024-07-04T09:49:59.620Z","workflow":"sligo-bug"}
{"level":"info","msg":"TaskSet Reconciliation","namespace":"argo-wf","time":"2024-07-04T09:49:59.620Z","workflow":"sligo-bug"}
{"level":"info","msg":"reconcileAgentPod","namespace":"argo-wf","time":"2024-07-04T09:49:59.620Z","workflow":"sligo-bug"}
{"level":"info","msg":"Workflow update successful","namespace":"argo-wf","phase":"Running","resourceVersion":"1708676","time":"2024-07-04T09:49:59.636Z","workflow":"sligo-bug"}
{"action":"deletePod","key":"argo-wf/sligo-bug-finish-2605594679/deletePod","level":"info","msg":"cleaning up pod","time":"2024-07-04T09:50:04.637Z"}
{"Phase":"Running","ResourceVersion":"1708676","level":"info","msg":"Processing workflow","namespace":"argo-wf","time":"2024-07-04T09:50:14.667Z","workflow":"sligo-bug"}
{"level":"info","msg":"Task-result reconciliation","namespace":"argo-wf","numObjs":2,"time":"2024-07-04T09:50:14.668Z","workflow":"sligo-bug"}
{"level":"info","msg":"task-result changed","namespace":"argo-wf","nodeID":"sligo-bug-2486207007","time":"2024-07-04T09:50:14.668Z","workflow":"sligo-bug"}
{"level":"info","msg":"task-result changed","namespace":"argo-wf","nodeID":"sligo-bug-2605594679","time":"2024-07-04T09:50:14.668Z","workflow":"sligo-bug"}
{"level":"info","msg":"TaskSet Reconciliation","namespace":"argo-wf","time":"2024-07-04T09:50:14.668Z","workflow":"sligo-bug"}
{"level":"info","msg":"reconcileAgentPod","namespace":"argo-wf","time":"2024-07-04T09:50:14.668Z","workflow":"sligo-bug"}
{"level":"info","msg":"Workflow update successful","namespace":"argo-wf","phase":"Running","resourceVersion":"1708676","time":"2024-07-04T09:50:14.685Z","workflow":"sligo-bug"}
```

### Logs from in your workflow's wait container

Edit: There is no wait container for Resource type pods. These logs are for the step that uses a container 

```text
{"level":"info","msg":"Starting Workflow Executor","time":"2024-07-04T09:55:13.015Z","version":"v3.5.8"}
{"Duration":1000000000,"Factor":1.6,"Jitter":0.5,"Steps":5,"level":"info","msg":"Using executor retry strategy","time":"2024-07-04T09:55:13.018Z"}
{"deadline":"2024-07-05T01:55:00Z","includeScriptOutput":false,"level":"info","msg":"Executor initialized","namespace":"argo-wf","podName":"sligo-bug-vj8v4-finish-1000479478","templateName":"finish","time":"2024-07-04T09:55:13.018Z","version":"\u0026Version{Version:v3.5.8,BuildDate:2024-06-18T03:43:17Z,GitCommit:3bb637c0261f8c08d4346175bb8b1024719a1f11,GitTag:v3.5.8,GitTreeState:clean,GoVersion:go1.21.10,Compiler:gc,Platform:linux/amd64,}"}
W0704 09:55:13.045324       1 warnings.go:70] Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
{"level":"info","msg":"Starting deadline monitor","time":"2024-07-04T09:55:13.046Z"}
{"error":null,"level":"info","msg":"Main container completed","time":"2024-07-04T09:55:16.047Z"}
{"level":"info","msg":"No Script output reference in workflow. Capturing script output ignored","time":"2024-07-04T09:55:16.047Z"}
{"level":"info","msg":"No output parameters","time":"2024-07-04T09:55:16.047Z"}
{"level":"info","msg":"No output artifacts","time":"2024-07-04T09:55:16.047Z"}
W0704 09:55:16.061106       1 warnings.go:70] Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
W0704 09:55:16.068093       1 warnings.go:70] Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
{"level":"info","msg":"Alloc=8106 TotalAlloc=13731 Sys=19557 NumGC=4 Goroutines=8","time":"2024-07-04T09:55:16.068Z"}
W0704 09:55:16.074405       1 warnings.go:70] Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
```

**Comment by Joibel** [comment] 2024-07-04 12:23
Can you ensure that the service account for the workflow pods has the correct RBAC: https://argo-workflows.readthedocs.io/en/latest/workflow-rbac/

**Comment by BarryOwensDigital** [comment] 2024-07-04 12:55
> Can you ensure that the service account for the workflow pods has the correct RBAC: https://argo-workflows.readthedocs.io/en/latest/workflow-rbac/
 
Yes we have the correct RBAC for both workflowtaskresults (create/patch) & statefulsets (get)
 
<details>
<summary> View full Role YAML </summary>

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-wf-argo-workflows-workflow
rules:
  - verbs:
      - get
    apiGroups:
      - apps
    resources:
      - statefulsets
  - verbs:
      - create
      - patch
    apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
  - verbs:
      - list
      - watch
    apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets
  - verbs:
      - get
    apiGroups:
      - '*'
    resources:
      - secrets
  - verbs:
      - patch
    apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets/status
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - kubernetes.dask.org
    resources:
      - daskclusters
      - daskworkergroups
      - daskworkergroups/scale
      - daskjobs
      - daskautoscalers
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods
      - pods/status
      - services
```

</details>

**Comment by BarryOwensDigital** [comment] 2024-07-04 14:14
v3.5.5 (chart version 0.41.0) seems to be the last version where the workflow provided completes and is not stuck in Running phase.  

The issue starts to arise with v3.5.6 (chart: 0.41.2)

**Comment by agilgur5** [comment] 2024-07-04 15:19
Thanks for the super detailed bug report! ❤️

> The following label is present on the WorkflowTaskResult:
> `workflows.argoproj.io/report-outputs-completed: 'false'`

Does this part happen in 3.5.5 too?

#12544 was in 3.5.5, so I'm guessing the bug results from that combined with #12574 in 3.5.6 -- if the reports are never marked as completed.

If the resource template gets an error, it would trigger the [`HandleError` line](https://github.com/argoproj/argo-workflows/blob/a929c8f4dd03460d0f1e5ab2937dd2990a659d81/cmd/argoexec/commands/resource.go#L41) before the `FinalizeOutputs` line. But that would only not continue during a `panic` specifically, which I would think this would not cause 🤔

@BarryOwensDigital could you provide the logs of the `main` container as well?

@shuangkun could you take a look here?

**Comment by BarryOwensDigital** [comment] 2024-07-04 16:35
> Does this part happen in 3.5.5 too?

Seems like in 3.5.5 we get `workflows.argoproj.io/report-outputs-completed: 'true'`. The workflowtask is removed quickly on this version 

Logs from the main container (v3.5.8). We expect myapp-mongodb not found here:
```
time="2024-07-04T16:27:32 UTC" level=info msg="Starting Workflow Executor" version=v3.5.8
time="2024-07-04T16:27:32 UTC" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2024-07-04T16:27:32 UTC" level=info msg="Executor initialized" deadline="2024-07-05 08:27:28 +0000 UTC" includeScriptOutput=false namespace=jenkins podName=sligo-bug2-check-mongo-ready-2523367045 templateName=check-mongo-ready version="&Version{Version:v3.5.8,BuildDate:2024-06-18T03:43:17Z,GitCommit:3bb637c0261f8c08d4346175bb8b1024719a1f11,GitTag:v3.5.8,GitTreeState:clean,GoVersion:go1.21.10,Compiler:gc,Platform:linux/amd64,}"
W0704 16:27:32.689976      14 warnings.go:70] Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
time="2024-07-04T16:27:32 UTC" level=info msg="Loading manifest to /tmp/manifest.yaml"
time="2024-07-04T16:27:32 UTC" level=info msg="kubectl get -f /tmp/manifest.yaml -o json"
Warning: Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
Error from server (NotFound): statefulsets.apps "myapp-mongodb" not found
{"argo":true,"error":null,"level":"info","msg":"sub-process exited","time":"2024-07-04T16:27:33.620Z"}
Error: exit status 1
```
Also agree this might be related to https://github.com/argoproj/argo-workflows/pull/12544, when I enable the debug logs we get this log on the controller: 
`...msg="taskresults of workflow are incomplete or still have daemon nodes, so can't mark workflow completed" fromPhase=Running namespace=jenkins toPhase=Succeeded ...`

**Comment by agilgur5** [comment] 2024-07-04 17:23
> Seems like in 3.5.5 we get `workflows.argoproj.io/report-outputs-completed: 'true'`

Huh. So the problem is that it's not being marked complete for some reason in 3.5.6+. But you also have no errors... 🤔

The [diff between 3.5.5 and 3.5.6](https://github.com/argoproj/argo-workflows/compare/v3.5.5...v3.5.6) has no relevant changes to the Executor though (the tiny changes are for when task result RBAC is not granted, which does not apply here).

I'm wondering if something else is changing the task result or something or if there's a wonky dep change or something 

> Also agree this might be related to #12544, when I enable the debug logs we get this log on the controller:

Yea though it is correct in this case; if the task result was marked complete this wouldn't happen

**Comment by BarryOwensDigital** [comment] 2024-07-05 07:31
> So the problem is that it's not being marked complete for some reason in 3.5.6+

I've checked again, I might have been mistaken earlier looking at incorrect WorkflowTaskResult.

In 3.5.5 the WorkflowTaskResult does still have `workflows.argoproj.io/report-outputs-completed: 'false'`

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTaskResult
metadata:
  generation: 1
  labels:
    workflows.argoproj.io/report-outputs-completed: 'false'
    workflows.argoproj.io/workflow: sligo-bug
```

**Comment by BarryOwensDigital** [comment] 2024-07-05 11:01
> Maybe this is the reason [#12103 (comment)](https://github.com/argoproj/argo-workflows/issues/12103#issuecomment-2185487682).

That issue looks to be different. We have no workflows running and the example workflow provided can reproduce the issue when a Workflow is started on 3.5.6+ 

> I reproduce this issue with your demo...The main container exited with code 1 because of RBAC problems

Additional RBAC is required for that example workflow. I have added rules to the above example. Regardless, on 3.5.5 if the step fails due to RBAC problems but has continueOn.error and continueOn.failed the workflow does not get stuck in Running phase.

> Pod of `Resource` type do not have the wait container, why do you have the logs of wait container.

Thanks for confirming, I didn't realise it didn't have a wait container until now. The wait container logs above are for the second step in the provided example workflow, not the step using the Resource type. I have added a note above

**Comment by jswxstw** [comment] 2024-07-05 11:46
> Sorry I'm not familiar with FinalizeOutput but this sounds like continueOn.error will not work as expected then?

`workflows.argoproj.io/report-outputs-completed` will be set to `true` in function `FinalizeOutput`, workflow will stuck in `Running` if it did not execute.

Can you provide the logs of the main container in the pod of `Resource` type? I think it might also exit midway.

**Comment by jswxstw** [comment] 2024-07-05 13:31
> `...msg="taskresults of workflow are incomplete or still have daemon nodes, so can't mark workflow completed" fromPhase=Running namespace=jenkins toPhase=Succeeded ...`

This line of log already shows the reason for this issue. 

The root cause is as I analyzed above: `FinalizeOutput will not be executed if the main container exits midway.`, which the log you privided `Error: exit status 1` has proved.

**Comment by BarryOwensDigital** [comment] 2024-07-05 14:36
> This line of log already shows the reason for this issue.

Just confirming, we in agreement then that there is an issue in 3.5.6+?

The error is expected and the workflow is expected to handle that and continue to completion since we have continueOn.error. 

"FinalizeOutput will not be executed if the main container exits midway" - this poses an issue since this means continueOn.error will not work for steps of type Resource. 

To compare, we can swap out the Resource type with a Container type that exits midway. This finishes fine and as it probably runs FinalizeOutput even if there is an error midway. 

<details>
<summary> show example workflow using no Container Type with continuesOn.error and exit midway </summary>

```
metadata:
  name: container-with-intentional-fail
  namespace: jenkins
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
      - - name: intentional-fail
          template: intentional-fail
          arguments: {}
          continueOn:
            error: true
            failed: true
  - name: intentional-fail
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo intentional failure; exit 1"]
```

Logs from main 

```
intentional failure
{"argo":true,"error":null,"level":"info","msg":"sub-process exited","time":"2024-07-05T14:22:33.391Z"}
Error: exit status 1
```

<img width="1207" alt="image" src="https://github.com/argoproj/argo-workflows/assets/133855741/144ef480-3053-457d-9489-768af928dcf6">


 

</details>

**Comment by agilgur5** [comment] 2024-07-05 15:05
@jswxstw yes, I already mentioned `FinalizeOutputs` not being run in my [very first comment here](https://github.com/argoproj/argo-workflows/issues/13299#issuecomment-2209218699). But, per that comment, it seemed like it should still run unless there's a panic in `HandleError`? Unless I'm misunderstanding how Go `defer` works

In any case, `FinalizeOutputs` must still run if there's an error. It shouldn't be stuck ever (unless there is a bug).

> I've checked again, I might have been mistaken earlier looking at incorrect WorkflowTaskResult.
> 
> In 3.5.5 the WorkflowTaskResult does still have `workflows.argoproj.io/report-outputs-completed: 'false'`

@BarryOwensDigital ok, that makes a lot more sense. That means the code from #12544 has a bug in it in the error case.

Also would you mind adding syntax highlighting to your code blocks? i.e. \```yaml. I've been editing all your comments to add it 😅

**Comment by jswxstw** [comment] 2024-07-05 15:33
> @jswxstw yes, I already mentioned `FinalizeOutputs` not being run in my [very first comment here](https://github.com/argoproj/argo-workflows/issues/13299#issuecomment-2209218699). But, per that comment, it seemed like it should still run unless there's a panic in `HandleError`? Unless I'm misunderstanding how Go `defer` works

It seems the main container exited by `os.Exit(1)`, thus `defer` function will not be executed.

**Comment by agilgur5** [comment] 2024-07-05 15:51
Yes, though I wonder what's running `os.Exit(1)` since we have error handling throughout `runKubectlCmd` -- that would suggest that `client-go` itself is perhaps doing that instead of returning an error?? 🤔

**Comment by agilgur5** [comment] 2024-07-05 16:06
Oh dear, I see the problem. We're not using `client-go` at all, but straight up calling the [`kubectl` code as a library](https://github.com/argoproj/argo-workflows/blob/a929c8f4dd03460d0f1e5ab2937dd2990a659d81/workflow/executor/resource.go#L26), which, as a CLI, will of course have exits 😕

If we want to keep doing that, we'd have to do what [their tests do](https://github.com/kubernetes/kubectl/blob/68dbd0767a9175dd30eb9dc8687ba5167c678c9b/pkg/cmd/explain/explain_test.go#L217) and catch exits. But tbh, I don't think we should run like that, I would think using `client-go` directly would make more sense. Although idk if the `flags` field would work the same that way

**Closed** 2024-07-08 09:16 UTC
Labels: type/regression, area/controller, area/executor, area/templates/resource, P2, solution/suggested
