### ISSUE TITLE
cronworkflow with configmap mounted with defaultmode ie 0744 breaks

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#11323] opened 2023-07-10 10:54 UTC
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

if I create via kubectl apply its fine but not if I create via pasting yaml in the ui

what I think happens is the ui removes the leading 0

### Version

3.4.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by terrytangyuan** [comment] 2023-07-10 14:18
Any examples?

**Comment by tooptoop4** [comment] 2023-07-10 21:24
maybe https://github.com/traPtitech/manifest/blob/5a4e3ba1e1b56065a4d6546122134d9bd28855d4/ns-system/backup/mongodb-backup-workflow-template.yaml#L15

**Comment by agilgur5** [comment] 2023-11-16 15:25
Closing in favor of #12205 which is much more detailed, both describing the problem in-depth and explaining the root cause

**Closed by agilgur5** 2023-11-16 15:25 UTC
Labels: bug, more information needed
