### ISSUE TITLE
Additional parameters for retry/resubmit in the UI

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#10824] opened 2023-04-04 19:38 UTC

**Comment by heavelock** [comment] 2023-04-06 13:53
Is this issue something that is free to take?
I am trying to find issues that are the most important for my team and get engineering resources for it. 

Would love to have `resubmit --memoized` equivalent in UI.

**Comment by terrytangyuan** [comment] 2023-04-06 15:09
> Is this issue something that is free to take?

Yes!

**Comment by terrytangyuan** [comment] 2023-04-06 19:46
Would you or your team members like to work on this? We can assign this issue to anyone interested.

**Comment by agilgur5** [comment] 2023-08-16 03:11
Was this implemented by #11083 ?

Not sure if this issue is a duplicate of #4662 or if the intent for this issue is slightly different?

**Comment by terrytangyuan** [comment] 2023-08-17 01:15
Resubmit is implemented but not for retry yet. cc @toyamagu-2021

**Comment by toyamagu-2021** [comment] 2023-08-20 01:30
I'm going to try to implement a retry version!

**Closed** 2023-08-20 15:24 UTC
Labels: enhancement, area/ui
