### ISSUE TITLE
v3.5.1 only works in / endpoint BASE_HREF

### ISSUE THREAD

**Issue by gabrielfsousa** [argoproj/argo-workflows#12217] opened 2023-11-17 15:04 UTC
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

blank page when using different BASE_HREF

### Version

v3.5.1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
...
    targetMemoryUtilizationPercentage: 50
  baseHref: /argowf/
  clusterWorkflowTemplates:
...

error in chrome console:
Uncaught SyntaxError: Unexpected token
```

### Logs from the workflow controller

```text
no errors in logs
```

### Logs from in your workflow's wait container

```text
no errors in logs
```

**Comment by gabrielfsousa** [comment] 2023-11-17 15:16
![image](https://github.com/argoproj/argo-workflows/assets/722744/e966d1a5-29af-44ea-8efc-62a12acd8bd6)

**Comment by terrytangyuan** [comment] 2023-11-19 13:14
Relevant https://github.com/argoproj/argo-workflows/pull/11644

**Comment by agilgur5** [comment] 2023-11-20 07:16
Duplicate of #11643, #11401, #10194, #3080.

Same as I wrote in https://github.com/argoproj/argo-workflows/issues/11643#issuecomment-1685871836, your [first screenshot](https://github.com/argoproj/argo-workflows/issues/12217#issuecomment-1816604149) shows that the HTML has `<base href="/argowf/">`, so that is working correctly.

Per https://github.com/argoproj/argo-workflows/issues/10194#issuecomment-1685866941, you might also be looking for `rootpath` support, i.e. #7767, which is a separate feature.

**Closed** 2023-11-20 07:17 UTC
Labels: duplicate, area/server, support

**Comment by gabrielfsousa** [comment] 2023-11-20 09:10
but we have blank page :(

**Comment by agilgur5** [comment] 2023-11-20 09:34
> but we have blank page :(

It appears that you're port-forwarding to `localhost` per your screenshot. Per https://github.com/argoproj/argo-workflows/issues/10194#issuecomment-1685850592:

> If you _aren't_ proxying Argo to a subpath, then setting `BASE_HREF` to a subpath would be a misconfiguration. Only set `BASE_HREF` if you _are_ proxying to a subpath.
> 
> A port-forward to `localhost` is _not_ proxying to a subpath.
