### ISSUE TITLE
v3.5: Archive Workflows button missing from UI

### ISSUE THREAD

**Issue by ichandra93** [argoproj/argo-workflows#13559] opened 2024-09-05 11:18 UTC
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

After we upgrade our argo to v3.5.8 , we are not seeing archive button on the UI.

![v3 5 8](https://github.com/user-attachments/assets/b0130766-b526-4b5f-9087-f82b9cc99292)

### Version(s)

v3.5.8

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
removed by agilgur5: this contained a Helm configuration with a lot of defaults and not a Workflow
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

no error in logs
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

no error in logs
```

**Comment by agilgur5** [comment] 2024-09-05 13:25
Duplicate of https://github.com/argoproj/argo-workflows/discussions/12545, https://github.com/argoproj/argo-workflows/discussions/13126#discussioncomment-9643345, https://github.com/argoproj/argo-workflows/issues/13356, etc

Please also see [the note in the "Upgrading Guide" of the docs](https://argo-workflows.readthedocs.io/en/release-3.5/upgrading/#upgrading-to-v35), as added in #13371

**Closed by agilgur5** 2024-09-05 13:25 UTC
Labels: area/ui, area/workflow-archive, solution/duplicate, type/support
