### ISSUE TITLE
v3.4.8 only works in / endpoint

### ISSUE THREAD

**Issue by gabrielfsousa** [argoproj/argo-workflows#11401] opened 2023-07-20 10:08 UTC
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

if i configure 
env:
          - name: BASE_HREF
            value: /argo/

i have a blank page

### Version

v3.4.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
blank page
```

### Logs from the workflow controller

```text
theres are no error messages
```

### Logs from in your workflow's wait container

```text
theres are no error messages
```

**Comment by caelan-io** [comment] 2023-07-20 16:13
@tico24 confirmed this is a bug on v3.4.8 - I don't believe any fixes pushed in v3.4.9 would fix this, but maybe someone else knows.

**Comment by JPZ13** [comment] 2023-07-20 17:34
Given this is a regression, let's see if we can add a test on the PR that fixes it so that we don't run into it again on a go forward

**Comment by agilgur5** [comment] 2023-08-21 06:33
This appears to actually duplicate an older issue with several comments: #10194

Not sure how long this has been broken for. Also not actually sure if this is an Argo bug per se (as opposed to a misconfiguration), as #3080 has various configurations for all sorts of Ingresses to get it to work

**Comment by agilgur5** [comment] 2023-08-21 07:55
> Also not actually sure if this is an Argo bug per se or just a cluster misconfiguration, as #3080 has various configurations for all sorts of Ingresses to get it to work

Ok so I looked through the `BASE_HREF` history in the repo (search [`BASE_HREF`](https://github.com/search?q=repo%3Aargoproj%2Fargo-workflows%20base_href&type=code) and [`baseHref`](https://github.com/search?q=repo%3Aargoproj%2Fargo-workflows%20basehref&type=code)) and there have not been changes to those in 3-4+ years, so I believe this is indeed due to cluster misconfiguration and therefore working correctly.

`BASE_HREF` does not change where Argo serves from, it changes what Argo interprets as the base. It is intended for proxying, as in, if your Ingress has the Argo Server at `/argo/`, you'll need to set `BASE_HREF` to `/argo/`. But if you have no proxy in front or are serving at `/` (i.e. not at a subpath), then you shouldn't set `BASE_HREF`.

**Comment by agilgur5** [comment] 2023-08-21 08:23
From my most [recent comment](https://github.com/argoproj/argo-workflows/issues/10194#issuecomment-1685866941) in #10194, looks like folks might be looking for `rootpath` support, i.e. #7767.

Both in #10194 and #11643, `BASE_HREF` is indeed being set correctly. People are just expecting it to act like `rootpath`, which is actually a separate (and as of yet unimplemented) feature.

Going to close this one out as such

**Closed by agilgur5** 2023-08-21 08:23 UTC
Labels: bug, regression, P1

**Comment by sonbui00** [comment] 2023-08-21 12:55
@agilgur5 I found the issue on this. Please help me reopen
