### ISSUE TITLE
Support Viewing Sub-Workflows in Top level Workflows

### ISSUE THREAD

**Issue by DP19** [argoproj/argo-workflows#4238] opened 2020-10-08 13:36 UTC
# Summary

Our use case in Argo depends a lot on using the Workflow of Workflows model. With this however, we are only able to see that a sub-workflow was spawned and some logs that it ran successfully. If we want to see the steps within that sub-workflow we have to back out of the top level workflow and dive into the spawned workflow.

It would be great to be able to see the full output of those sub-workflows within the top level workflow to get a better overall picture of our pipeline

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment] 2020-10-08 19:00
I don't think we should show the fully embedded workflow in the workflow-of-workflows pattern, but what we can/should do is link to the other workflow when we detect that the resource kind is a Workflow.

**Comment by jessesuen** [comment] 2020-10-08 19:01
@DP19 would you like to submit a PR for the above? Would be a UI only change

**Comment by DP19** [comment] 2020-10-08 19:18
Yeah, I can give this a shot. Any ideas on what would need to be changed exactly. Not familiar with the code base yet.

**Comment by alexec** [comment] 2020-10-08 19:53
Try this help: https://argoproj.github.io/argo/CONTRIBUTING/

**Comment by DP19** [comment] 2020-10-09 14:23
Thanks @alexec. Someone else can take this over. I just took a quick look and i'm not well versed in node. But from what i can tell just by following the [workflow of workflow guide](https://argoproj.github.io/argo/workflow-of-workflows/) as an example, then using the apiDocs to get info about the spawned workflow, there doesn't seem to be any reference to the sub workflow that gets launched so I'm not positive this is just a UI change

**Comment by agilgur5** [comment] 2023-08-27 11:13
Closing as duplicate of #6922 as that one has more up votes (though of course this one came first)

**Closed by agilgur5** 2023-08-27 11:13 UTC
Labels: enhancement, area/ui
