### ISSUE TITLE
support git repo http.sslverify false

### ISSUE THREAD

**Issue by willzhang** [argoproj/argo-workflows#11656] opened 2023-08-23 06:14 UTC
# Summary

What change needs making?

# Use Cases

i have a gitlab repo with self-signed certificate
``
git config --global http.sslverify false
git clone https://gitlab.example.com/root/test.git
```

i want git clone use arog-workflows,  and config http.sslverify false, how can i do that?

---
<!-- Issue Author: Don't delete this message to encourage other users to support your issue! -->
**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by moonyoungCHAE** [comment] 2023-09-09 05:26
@willzhang 
I think you need to check your git version or config.
If it does not work, I'd like to know more detail in your case.

**Comment by agilgur5** [comment] 2023-10-12 15:57
Seems like a duplicate of #10762

**Closed by agilgur5** 2023-10-12 15:57 UTC
Labels: enhancement, area/artifacts
