### ISSUE TITLE
Argo Workflows v3.1.0 tag manifest has latset tags in images

### ISSUE THREAD

**Issue by axsaucedo** [argoproj/argo-workflows#6229] opened 2021-06-26 06:34 UTC
## Summary 

What happened/what you expected to happen?

Installed Argo workflwos from v3.1.0 tag and expected images to be pinned to 3.1.0.

Used:

```
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/v3.1.0/manifests/install.yaml
```

Images installed have tag `latest` - can be verified with:

```
kubectl get pods -n argo -o yaml | grep image
```

**Comment by alexec** [comment] 2021-06-26 16:35
Duplicate of https://github.com/argoproj/argo-workflows/issues/6219

**Closed by alexec** 2021-06-26 16:35 UTC
Labels: bug
