### ISSUE TITLE
[master branch only] UI crashes when clicking node with an error message: Buffer is not defined 

### ISSUE THREAD

**Issue by toyamagu-2021** [argoproj/argo-workflows#11764] opened 2023-09-06 16:21 UTC
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

THIS DOES NOT RELATES TO RELEASED IMAGES either v3.5.0-rc nor v3.10.0.
Might be local development only?

* Summary
  * UI crashes when we click a node `hello1`.
  * Curiously, `step-mnss7` is ok.
  * ![image](https://github.com/argoproj/argo-workflows/assets/83329336/66316938-7254-4e05-b2db-c5713b14a5c4)
  * ![image](https://github.com/argoproj/argo-workflows/assets/83329336/1ce3693e-7b2a-495b-810a-6f478c933af9)
* Procedure
  * checkout master branch
  * `make start UI=true`
* My Env
  * WSL
  * k3d

### Version

master

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello-hello-hello

  # This spec contains two templates: hello-hello-hello and whalesay
  templates:
  - name: hello-hello-hello
    # Instead of just running a container
    # This template has a sequence of steps
    steps:
    - - name: hello1            # hello1 is run before the following steps
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "hello1"
    - - name: hello2a           # double dash => run after previous step
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "hello2a"
      - name: hello2b           # single dash => run in parallel with previous step
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "hello2b"

  # This is the same template as from the previous example
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```
```


### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by terrytangyuan** [comment] 2023-09-06 16:38
Might be related to recent dependency updates? cc @agilgur5

**Comment by toyamagu-2021** [comment] 2023-09-06 16:59
I'm not completely sure, but https://github.com/argoproj/argo-workflows/commit/aac4f89d1649125a7c431e0c92fbc3862e60f494 might cause this problem.
Previous commits are ok.

**Comment by agilgur5** [comment] 2023-09-06 17:00
I can check if I can reproduce. All of my PRs I had no errors locally, but maybe when mixed with dependabot updates something broke.

**Comment by agilgur5** [comment] 2023-09-06 17:08
> I'm not completely sure, but [aac4f89](https://github.com/argoproj/argo-workflows/commit/aac4f89d1649125a7c431e0c92fbc3862e60f494) might cause this problem.
> Previous commits are ok.

> `Buffer is not defined`

So #11628 upgraded to Webpack v5, which no longer auto-adds Node polyfills. `Buffer` I believe is one of them. In https://github.com/argoproj/argo-workflows/pull/11418#issuecomment-1696260188 I got a _build error_ on `Buffer` not resolving. This is a run-time error though, so that suggests that a dep might be using `Buffer` as a global (i.e. did not explicitly import it) 🤔

**Comment by agilgur5** [comment] 2023-09-06 17:13
Oh. That is internal code using `Buffer`: https://github.com/argoproj/argo-workflows/blob/94fbb3bf27f0746a0b84ea2f654568cc655bfbfb/ui/src/app/shared/pod-name.ts#L38.

That probably requires a polyfill now. I'll look into that.

**Comment by agilgur5** [comment] 2023-09-06 17:25
TIL what an FNV hash is. This comes from 2 year old code in #6925, which was quite literally intended to duplicate server-side code per https://github.com/argoproj/argo-workflows/issues/6865#issuecomment-934930003.

So that makes a bit more sense why server-side JS is being used 😅 

Ideally we might be able to replace the hash function with a library that works client-side, but if not, will add a polyfill

**Comment by toyamagu-2021** [comment] 2023-09-06 17:33
Great! Thank you!

FYI, this regression does not included in v3.4.11.
I've checked this by checking out to release-3.4.11 and create local environment.

**Comment by terrytangyuan** [comment] 2023-09-06 18:18
Yeah I intentionally didn't include those UI changes since they are relatively new and not thoroughly tested yet. Thanks for confirming.

**Comment by agilgur5** [comment] 2023-09-06 18:22
Yea the UI build system being upgraded a major version is definitely more of a risky change and certainly _not_ a bugfix 😅

Idk how long 3.4.x will get backports for (this is the first minor release I've been part of), but if it's a while, we may eventually want to add some of the UI deps changes so that it doesn't diverge too much.

**Comment by agilgur5** [comment] 2023-09-06 19:44
Managed to find a pretty tiny fix that didn't need a polyfill or another library.

See #11766

**Closed** 2023-09-06 22:55 UTC
Labels: bug, regression, area/ui
