### ISSUE TITLE
Allow specifying the payload key for groups claim

### ISSUE THREAD

**Issue by michael132** [argoproj/argo-workflows#5953] opened 2021-05-20 05:59 UTC
# Summary

Currently in `v3.0.3`, it is [hardcoding](https://github.com/argoproj/argo-workflows/blob/4e450e250168e6b4d51a126b784e90b11a0162bc/server/auth/types/claims.go#L7) the key `groups` for the `groups` claim.
 It would be very helpful to allow this to be configurable. 

# Use Cases

In our case, our key is `ad_groups` instead of `groups`. This causes argo workflows to not able to read the groups correctly and therefore unable to achieve RBAC SSO via groups claim.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment] 2021-05-20 15:02
Would you like to submit a PR to add this?

**Comment by michael132** [comment] 2021-05-21 07:15
> Would you like to submit a PR to add this?

I am not efficient enough in Go to get this done in the most elegant way. Does anyone have any cycles? I am currently just hack it and build the `argocli` image that we use.

**Comment by alexec** [comment] 2021-05-21 15:45
Given that (a) core team is currently <50% capacity and (b) he core team does not use `ad_groups` it is unlikely to be picked up anytime soon.

Check out the CONTRIBUTING.md to find out how to contribute.

**Comment by liafizan** [comment] 2021-07-01 19:47
hello @alexec we are facing similar issue as we use a different OIDC provider and have to use a custom claim but cannot use `groups` as the claim name. We plan to work on this. Could you please assign this?

**Comment by alexec** [comment] 2021-07-01 19:55
Done.

**Comment by alexec** [comment] 2021-07-01 19:59
(a) add `ADGroups` to `types.Claims` 
(b) add to `GetUserInfoResponse` in `info.proto` 
(c)  surface it to the user in `UserInfo` in user-info.tsx

i.e don't try and jam `ad_groups` into the existing `groups` variables, create a new place of it. No coupling.

**Comment by michael132** [comment] 2021-07-02 07:06
> hello @alexec we are facing similar issue as we use a different OIDC provider and have to use a custom claim but cannot use `groups` as the claim name. We plan to work on this. Could you please assign this?

Thank you for taking care of this!

**Comment by liafizan** [comment] 2021-07-07 17:42
hey @michael132 looks like the original request was to allow users to specify the key name for groups clam but looks it is not configurable and would add unnecessary complexity if try to make it user defined. 

We are planning to go with what @alexec suggested and have `ad_groups` as another claim in there which I suppose will serve your purpose as well as others like us to set a custom claim with that name. I hope this will help, please let us know in case it does not.

**Comment by michael132** [comment] 2021-07-08 06:42
> hey @michael132 looks like the original request was to allow users to specify the key name for groups clam but looks it is not configurable and would add unnecessary complexity if try to make it user defined.
> 
> We are planning to go with what @alexec suggested and have `ad_groups` as another claim in there which I suppose will serve your purpose as well as others like us to set a custom claim with that name. I hope this will help, please let us know in case it does not.

Hey @liafizan, not a problem at all. I have being building images locally with the support of custom group claims (with the same exact way) as well.

**Comment by OscardR** [comment] 2021-07-13 13:50
We are facing the same issue, only our OIDC provider is using yet another key for this claim. Would it be too difficult to make this configurable so _any_ key could be possibly used?

**Comment by alexec** [comment] 2021-07-13 15:45
The marshalling of the claims goes into a struct, where keys are set at compile time. Maybe we need to change the struct to a map if we end up with many variations.

**Comment by liafizan** [comment] 2021-07-13 16:31
@OscardR Does your oidc support custom claims? Most providers do and might be the easiest approach as we are adopting the same path. 

@alexec We were sort of done with the change based on your previous inputs and testing out stuff. I believe converting `Claims` type to map as suggested above would then also involve type assertion or reflection at some level and may add some complexity. Please correct me if wrong. 

I would also leave this decision to you/community and move forward with you all recommend.

**Comment by OscardR** [comment] 2021-07-15 07:59
Hi @liafizan no, unfortunately our OIDC provides the _roles_ claim with a custom key and it doesn't by default use the _groups_ scope either (it can be enabled but it doesn't cover our use case; we need application-scoped roles). So I am afraid we can only use clients that can be configured with the custom key for _roles_.

We have the same problem with other applications, so it's not specific just to Argo Workflows, but I don't think there's any plan for our infra to provide custom claims for the moment 🤷🏻‍♂️

**Comment by alexec** [comment] 2021-07-15 15:34
Would someone like to send a PR to fix this?

**Comment by liafizan** [comment] 2021-07-15 16:10
@alexec we am working on it and the issue is assigned to me. 

Should we proceed with making `Claims` ds a Map instead of Struct? Is configmap the right place to then also get the name of claim to be expected ( somewhere along with SSO config ). Please let me know if you think there is a better place for that

**Comment by alexec** [comment] 2021-07-15 16:17
I think if we make it a map, we can support *any* claim, which is more powerful and would meet all use cases.

**Comment by liafizan** [comment] 2021-07-15 16:24
Ok, we will give it a shot and see how it goes.

**Comment by liafizan** [comment] 2021-07-26 18:06
Hi there, we do have the fix ready for this and we have been testing it out in our environments. However, we do have to follow up on some approvals before we can officially contribute it here. Hoping to get it done this week.

**Closed** 2021-07-30 21:27 UTC
Labels: enhancement, help wanted
