### ISSUE TITLE
Random steps fail with message "pod deleted"

### ISSUE THREAD

**Issue by dafinguzman** [argoproj/argo-workflows#5321] opened 2021-03-07 19:21 UTC
## Summary 

We operate with calls to a 3-step workflow in Argo-events using a RabbitMQ trigger (each step uses as input an artifact from the previous one). We set up the workflow around the second semester of 2020, with Argo v2.10.0 rc4, and put it in production with no issues. We have now over 700 run workflows. 

Suddenly, around January-February this year, a random number of pods started getting deleted. We had not made any changes to Argo.

The error always happens during the second step, which is the most time-consuming and resource-intensive. These running pods get deleted after a variable time period, which can range from some minutes to several hours. 

For example, this Friday, we sent 10 jobs and 4 of them failed. Some failed after running for 14 hours, another one failed after running for 6 hours, and another one after 30 minutes.

These steps run in their own nodegroup, which uses autoscaling to start and stop nodes.

We set the argo-workflow-controller log level to debug and saw this type of message in the logs: 
```
time="2021-03-07T02:47:09.823Z" level=info msg="Processing workflow" namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.824Z" level=info msg="Workflow pod is missing" namespace=argo-events nodePhase=Running podName="cliktor-ueuropea-2-47-145-zst9j[1].diktor" recentlyStarted=false workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.824Z" level=info msg="node cliktor-ueuropea-2-47-145-zst9j-1474123981 phase Running -> Error" namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.824Z" level=info msg="node cliktor-ueuropea-2-47-145-zst9j-1474123981 message: pod deleted" namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.824Z" level=info msg="node cliktor-ueuropea-2-47-145-zst9j-1474123981 finished: 2021-03-07 02:47:09.8241151 +0000 UTC" namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.824Z" level=debug msg="Evaluating node cliktor-ueuropea-2-47-145-zst9j: template: *v1alpha1.WorkflowStep (cliktor), boundaryID: " namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.824Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo-events,name=cliktor-ueuropea-2-47-145-zst9j)" depth=0 tmpl="*v1alpha1.WorkflowStep (cliktor)"
time="2021-03-07T02:47:09.824Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo-events,name=cliktor-ueuropea-2-47-145-zst9j)" depth=0 tmpl="*v1alpha1.WorkflowStep (cliktor)"
time="2021-03-07T02:47:09.824Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=argo-events,name=cliktor-ueuropea-2-47-145-zst9j)" depth=0 tmpl="*v1alpha1.WorkflowStep (cliktor)"
time="2021-03-07T02:47:09.824Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo-events\", Name:\"cliktor-ueuropea-2-47-145-zst9j\", UID:\"716756a8-3e33-45b1-9042-e949474e5054\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"145493435\", FieldPath:\"\"}): type: 'Warning' reason: 'WorkflowNodeError' Error node cliktor-ueuropea-2-47-145-zst9j[1].diktor: pod deleted"
time="2021-03-07T02:47:09.830Z" level=debug msg="Executing node cliktor-ueuropea-2-47-145-zst9j of Steps is Running" namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.830Z" level=debug msg="Step group node &NodeStatus{ID:cliktor-ueuropea-2-47-145-zst9j-2209442595,Name:cliktor-ueuropea-2-47-145-zst9j[0],DisplayName:[0],Type:StepGroup,TemplateName:,TemplateRef:nil,Phase:Succeeded,BoundaryID:cliktor-ueuropea-2-47-145-zst9j,Message:,StartedAt:2021-03-07 00:07:24 +0000 UTC,FinishedAt:2021-03-07 00:10:03 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[cliktor-ueuropea-2-47-145-zst9j-3377949011],OutboundNodes:[],TemplateScope:local/cliktor-ueuropea-2-47-145-zst9j,ResourcesDuration:ResourcesDuration{cpu: 1m25s,memory: 1h4m46s,},HostNodeName:,MemoizationStatus:nil,EstimatedDuration:0,SynchronizationStatus:nil,Progress:1/2,} already marked completed" namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.830Z" level=info msg="SG Outbound nodes of cliktor-ueuropea-2-47-145-zst9j-3377949011 are [cliktor-ueuropea-2-47-145-zst9j-3377949011]" namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.830Z" level=debug msg="Evaluating node cliktor-ueuropea-2-47-145-zst9j[1].diktor: template: *v1alpha1.WorkflowStep (diktor), boundaryID: cliktor-ueuropea-2-47-145-zst9j" namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.830Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo-events,name=cliktor-ueuropea-2-47-145-zst9j)" depth=0 tmpl="*v1alpha1.WorkflowStep (diktor)"
time="2021-03-07T02:47:09.830Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo-events,name=cliktor-ueuropea-2-47-145-zst9j)" depth=0 tmpl="*v1alpha1.WorkflowStep (diktor)"
time="2021-03-07T02:47:09.830Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=argo-events,name=cliktor-ueuropea-2-47-145-zst9j)" depth=0 tmpl="*v1alpha1.WorkflowStep (diktor)"
time="2021-03-07T02:47:09.830Z" level=debug msg="Node cliktor-ueuropea-2-47-145-zst9j[1].diktor already completed" namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.830Z" level=info msg="Step group node cliktor-ueuropea-2-47-145-zst9j-2276700166 deemed failed: child 'cliktor-ueuropea-2-47-145-zst9j-1474123981' failed" namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.830Z" level=info msg="node cliktor-ueuropea-2-47-145-zst9j-2276700166 phase Running -> Failed" namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.830Z" level=info msg="node cliktor-ueuropea-2-47-145-zst9j-2276700166 message: child 'cliktor-ueuropea-2-47-145-zst9j-1474123981' failed" namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.830Z" level=info msg="node cliktor-ueuropea-2-47-145-zst9j-2276700166 finished: 2021-03-07 02:47:09.83079918 +0000 UTC" namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.830Z" level=info msg="step group cliktor-ueuropea-2-47-145-zst9j-2276700166 was unsuccessful: child 'cliktor-ueuropea-2-47-145-zst9j-1474123981' failed" namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.830Z" level=info msg="Outbound nodes of cliktor-ueuropea-2-47-145-zst9j-1474123981 is [cliktor-ueuropea-2-47-145-zst9j-1474123981]" namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.830Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo-events\", Name:\"cliktor-ueuropea-2-47-145-zst9j\", UID:\"716756a8-3e33-45b1-9042-e949474e5054\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"145493435\", FieldPath:\"\"}): type: 'Warning' reason: 'WorkflowNodeFailed' Failed node cliktor-ueuropea-2-47-145-zst9j[1]: child 'cliktor-ueuropea-2-47-145-zst9j-1474123981' failed"
time="2021-03-07T02:47:09.830Z" level=info msg="Outbound nodes of cliktor-ueuropea-2-47-145-zst9j is [cliktor-ueuropea-2-47-145-zst9j-1474123981]" namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.830Z" level=info msg="node cliktor-ueuropea-2-47-145-zst9j phase Running -> Failed" namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.830Z" level=info msg="node cliktor-ueuropea-2-47-145-zst9j message: child 'cliktor-ueuropea-2-47-145-zst9j-1474123981' failed" namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.830Z" level=info msg="node cliktor-ueuropea-2-47-145-zst9j finished: 2021-03-07 02:47:09.830922974 +0000 UTC" namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.830Z" level=info msg="Checking daemoned children of cliktor-ueuropea-2-47-145-zst9j" namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.830Z" level=info msg="Updated phase Running -> Failed" namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.830Z" level=info msg="Updated message  -> child 'cliktor-ueuropea-2-47-145-zst9j-1474123981' failed" namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.830Z" level=info msg="Marking workflow completed" namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.830Z" level=info msg="Checking daemoned children of " namespace=argo-events workflow=cliktor-ueuropea-2-47-145-zst9j
time="2021-03-07T02:47:09.831Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo-events\", Name:\"cliktor-ueuropea-2-47-145-zst9j\", UID:\"716756a8-3e33-45b1-9042-e949474e5054\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"145493435\", FieldPath:\"\"}): type: 'Warning' reason: 'WorkflowNodeFailed' Failed node cliktor-ueuropea-2-47-145-zst9j: child 'cliktor-ueuropea-2-47-145-zst9j-1474123981' failed"
time="2021-03-07T02:47:09.831Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo-events\", Name:\"cliktor-ueuropea-2-47-145-zst9j\", UID:\"716756a8-3e33-45b1-9042-e949474e5054\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"145493435\", FieldPath:\"\"}): type: 'Warning' reason: 'WorkflowFailed' child 'cliktor-ueuropea-2-47-145-zst9j-1474123981' failed"
time="2021-03-07T02:47:09.835Z" level=debug msg="Log changes patch: {\"metadata\":{\"labels\":{\"workflows.argoproj.io/completed\":\"true\",\"workflows.argoproj.io/phase\":\"Failed\"}},\"status\":{\"conditions\":[{\"status\":\"False\",\"type\":\"PodRunning\"},{\"status\":\"True\",\"type\":\"Completed\"}],\"finishedAt\":\"2021-03-07T02:47:09Z\",\"message\":\"child 'cliktor-ueuropea-2-47-145-zst9j-1474123981' failed\",\"nodes\":{\"cliktor-ueuropea-2-47-145-zst9j\":{\"finishedAt\":\"2021-03-07T02:47:09Z\",\"message\":\"child 'cliktor-ueuropea-2-47-145-zst9j-1474123981' failed\",\"outboundNodes\":[\"cliktor-ueuropea-2-47-145-zst9j-1474123981\"],\"phase\":\"Failed\"},\"cliktor-ueuropea-2-47-145-zst9j-1474123981\":{\"finishedAt\":\"2021-03-07T02:47:09Z\",\"message\":\"pod deleted\",\"phase\":\"Error\"},\"cliktor-ueuropea-2-47-145-zst9j-2276700166\":{\"finishedAt\":\"2021-03-07T02:47:09Z\",\"message\":\"child 'cliktor-ueuropea-2-47-145-zst9j-1474123981' failed\",\"phase\":\"Failed\"}},\"phase\":\"Failed\"}}"
time="2021-03-07T02:47:09.868Z" level=info msg="Workflow update successful" namespace=argo-events phase=Failed resourceVersion=145546136 workflow=cliktor-ueuropea-2-47-145-zst9j
```

There isn't much there that we can use to conclude what the error is. In Grafana's Pod Overview we see that the pods stop generating data at around the same time:

![Screenshot from 2021-03-07 15-55-13](https://user-images.githubusercontent.com/12529429/110251119-c8a6e900-7f5d-11eb-9728-0347ea960027.png)
![Screenshot from 2021-03-07 16-01-10](https://user-images.githubusercontent.com/12529429/110251231-64d0f000-7f5e-11eb-84a9-85fc446a1ac7.png)

After this, we have tried updating to newer Argo versions. We are currently running version v3.0.0 rc4. We have also tried setting resource requirements to argo-workflow-controller, argo-server, and argo-ui. The problem persists.

## Diagnostics

What Kubernetes provider are you using? 
**EKS, Kubernetes version 1.15**. We are using the **Docker executor**. 

~Right now we changed to the **PNS executor** to see if this makes any difference.~ (**Edit:** we could not get it to work with the PNS Executor, so we stayed with the Docker executor)

What version of Argo Workflows are you running? 
**v3.0.0 rc4**

Since the error occurs at random moments in random workflows, we haven't been able to reproduce it at will. We have even seen identical workflows run at the same time, one of them succeeding and the other one failing, or even failing at different times.

Tagging @paltaa who could maybe complement with other details. 

If you need more details please let me know. I would greatly appreciate suggestions on how to debug this.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment] 2021-03-07 22:32
There's been some bug with the latest PNS executor. Please make sure you're not running `argoproj/argoexec:latest` and that you are running the matching version for your controller.

**Comment by dafinguzman** [comment] 2021-03-07 23:42
Thanks for the response @alexec. We could not get it to work with the PNS executor today and we didn't have more time for testing, so we reverted to the original Docker Executor for now.

**Comment by paltaa** [comment] 2021-03-08 15:19
hey @alexec we were using Docker executor, tried to switch to PNS executor, same version of the controller 3.0.0-rc4 but still no useful errors from the wait, init, or workflow-controller, it seems it just stops sending data, noticed it sends pod status every 5 mins

**Comment by alexec** [comment] 2021-03-08 16:00
It is important with this issue to determine if the pod was actually deleted (e.g. Kuberenetes evicted it because it needed the resources) or was not.

**Comment by paltaa** [comment] 2021-03-08 18:25
That is not possible, the workflow run in order 3 pods that are executed in a dedicated node with plenty of resources, showed in the grafana dashboard at the begining of the issue, we do now know for sure it was not deleted anyways, any logs/events that saves this? As this happense randomly its hard to be around checking the pods every few minutes

**Comment by alexec** [comment] 2021-03-08 18:27
The Kubernetes audit log is very helpful for finding out what happened:

https://kubernetes.io/docs/tasks/debug-application-cluster/audit/

**Comment by paltaa** [comment] 2021-03-12 15:05
Hey Alex! Will take a look at that during the weekend, thanks! will keep you posted

**Comment by paltaa** [comment] 2021-03-22 15:59
Hey @alexec, Thank you very much for the policy audit, the problem was that the pods requested too much resources from the kubelet and then stopped posting status, hence marked it has node unavailable.

You can close the issue now, thanks!

**Comment by alexec** [comment] 2021-03-22 16:13
Thank you

**Closed by alexec** 2021-03-22 16:13 UTC
Labels: bug

**Comment by thundergolfer** [comment] 2022-03-22 03:35
> the pods requested too much resources from the kubelet and then stopped posting status,

@paltaa If you don't mind, can you add detail to this? It's the Kubelet that stopped posting status, right? How is it that the pods requested "too much resources" from Kubelet? Use of `request` and `limit` should stop a node failing from resource exhaustion, or was there some other way that pods were interfering with the execution of the Kubelet?

**Comment by paltaa** [comment] 2022-03-22 12:40
@thundergolfer The real problem here was that AWS EKS is always trying to balance the nodes between availability zones, unexpectedly killing nodes... So that made the kubelet stop posting status and killed the pods scheduled there

**Comment by thundergolfer** [comment] 2022-03-23 03:19
@paltaa thanks for that extra detail. How did you root cause that problem? That EKS behaviour seems undesirable, and figuring out if that's happening on our end would be helpful. We are also experiencing 'random' steps fail with the message "pod deleted", and we can't explain the deletions with reference to any Argo garbage collection behaviour or application failure.

**Comment by paltaa** [comment] 2022-03-23 13:11
Well, this happened quite some time ago... I remember seeing some sig kill/term sent to the jobs, afterward remember reading that if your node group got more than one availability zone it will always try to balance them between them. What we did is to only use one availability zone per node group doing the jobs ( of course different availability zones for the kind of nodes) and the problem never happened again, so, went to the cloudformation templates for that nodegroup and deleted subnets for that availability zone, so they wouldn't balance. Of course this is not ideal but it worked to check if that was the problem or not.

Hope this helps
