### ISSUE TITLE
Support MYSQL DB options for persistence

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#8905] opened 2022-06-03 17:04 UTC
# Summary

What change needs making?

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment] 2024-10-16 03:30
Duplicate of #8901 and already completed in #8157 per [JM's comment there](https://github.com/argoproj/argo-workflows/issues/8901#issuecomment-1212385568)

**Closed** 2024-10-16 03:31 UTC
Labels: area/workflow-archive, solution/duplicate, type/support
