### ISSUE TITLE
Workflow marked as finished before template level onExit hooks finished when stop workflow

### ISSUE THREAD

**Issue by toyamagu-2021** [argoproj/argo-workflows#11880] opened 2023-09-24 08:34 UTC
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

* Workflow does not wait for template-level onExit hooks to be finished when stopping
   * onExit hooks for template-level onExit hook is marked as Running Permanently
   * ![image](https://github.com/argoproj/argo-workflows/assets/83329336/f7347252-e2d2-4b60-8199-716bd6f9920b)
* This might be the root cause of flakiness of TestStopBehavior
   * https://github.com/argoproj/argo-workflows/blob/d0588ea092012c36ce06f44b008dc057bdf72154/test/e2e/signals_test.go#L27
   * https://github.com/argoproj/argo-workflows/actions/runs/6288766349/job/17074596262?pr=11839
 
```
Condition "to be done" met after 9s
Checking expectation stop-terminate-wpvxk
stop-terminate-wpvxk : Failed Stopped with strategy 'Stop'
    signals_test.go:44: 
        	Error Trace:	/home/runner/work/argo-workflows/argo-workflows/test/e2e/signals_test.go:44
        	            				/home/runner/work/argo-workflows/argo-workflows/test/e2e/fixtures/then.go:68
        	            				/home/runner/work/argo-workflows/argo-workflows/test/e2e/fixtures/then.go:43
        	            				/home/runner/work/argo-workflows/argo-workflows/test/e2e/signals_test.go:36
        	Error:      	Not equal: 
        	            	expected: "Succeeded"
        	            	actual  : "Running"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,2 @@
        	            	-(v1alpha1.NodePhase) (len=9) "Succeeded"
        	            	+(v1alpha1.NodePhase) (len=7) "Running"
        	            	 
        	Test:       	TestSignalsSuite/TestStopBehavior
=== FAIL: SignalsSuite/TestStopBehavior
```

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: stop-terminate-
spec:
  entrypoint: main
  onExit: exit
  templates:
    - name: main
      dag:
        tasks:
          - name: A
            template: echo
            onExit: exit-template

    - name: echo
      container:
        image: argoproj/argosay:v1
        command: [ sleep ]
        args: [ "999" ]

    - name: exit
      container:
        image: argoproj/argosay:v1
        command: [ sleep ]
        args: [ "10" ]

    - name: exit-template
      container:
        image: argoproj/argosay:v1
        command: [ sleep ]
        args: [ "20" ]
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by agilgur5** [comment] 2023-09-24 14:54
Wow nice find and good hypothesis! I didn't realize there were two hooks on that Workflow, but that could make a lot of sense if that is root cause. Fairly edge case edge case.

If the controller has marked it as stopped and moved on, then the `NodeStatus` never gets updated 🤔

**Comment by toyamagu-2021** [comment] 2023-09-24 15:14
Yeah. Truely edge case which might not problem for our users but for us suffered from flakiness :)

For workflow-level hooks, controller will wait for NodeStatus:
* https://github.com/argoproj/argo-workflows/blob/6399ac70619ff037793b773d44131c7a1f9e7fb6/workflow/controller/operator.go#L430
But not for template-level hooks for dag?:
* https://github.com/argoproj/argo-workflows/blob/6399ac70619ff037793b773d44131c7a1f9e7fb6/workflow/controller/dag.go#L290

**Comment by skytt** [comment] 2023-12-20 09:00
same questions. stopped workflow was archived with dag `onExit` hook running. And the archived worlflow cannot retry again because the running exit hook. Is there any fix processing?

**Comment by toyamagu-2021** [comment] 2023-12-20 13:52
I'm afraid there is no fic processing currently.

**Comment by toyamagu-2021** [comment] 2023-12-20 23:16
Thanks for sharing your use-case.
Can we get over this by checking NodeStatuses recursively? I might know the related logic, so I'll look into it.

**Closed** 2024-01-01 01:18 UTC
Labels: area/hooks, area/exit-handler, P3, area/shutdown
