### ISSUE TITLE
Support Catchup feature on Cronworkflow

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#4210] opened 2020-10-04 22:23 UTC
# Summary
Trigger the missed events/schedules if the user resumes the suspended cronworkflow or the workflow controller was down for long period.

What change needs making?
Add a `catchup=true`flag in `cronworkflow` CDR

# Use Cases
The user wants to trigger all missed events from the last triggered event if the user resumes the suspended cronworkflow or workflow controller was down for long period.

When would you use this?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by tooptoop4** [comment] 2022-04-09 00:12
would this cover a case where you have a 5pm cron schedule but k8s had an outage from 4.59pm-5.01pm, would it trigger that missed 5pm at 5.02pm when k8s is back?

**Comment by agilgur5** [comment] 2023-09-01 06:58
Seems like a duplicate of #2706

**Closed by agilgur5** 2023-09-01 06:58 UTC
Labels: enhancement, area/cron-workflows

**Comment by ramoslucas-lr** [comment] 2024-09-06 15:49
I don't think this is a duplicate of #2706
Running backfill is great but they require either manual intervention or creating new workflows to cover the main one.
It would be great to enable catchup on CronWorkflow natively, similar to what was done in issue 897 of Argo Events https://github.com/argoproj/argo-events/issues/897

**Comment by agilgur5** [comment] 2024-09-06 17:52
> It would be great to enable catchup on CronWorkflow natively

That's why #2706 is still open -- see https://github.com/argoproj/argo-workflows/issues/2706#issuecomment-666777083 which also references Argo Events
