### ISSUE TITLE
Ability to Ignore certain Tasks for Workflow Status

### ISSUE THREAD

**Issue by DerekTBrown** [argoproj/argo-workflows#13342] opened 2024-07-12 20:33 UTC
# Summary
What change needs making?

- I have a workflow that includes a task that periodically fails. 
- I don't want this task failure to impact the overall status (`Success/Failure`) condition of the workflow. I use the `continueOn` feature to properly handle this falure.
- Having the overall status (`Success/Failure`) condition of the workflow is critical so that metrics appear correct / that this workflow doesn't trigger alerts.

## Use Cases

When would you use this?

- For instance, I have a CI Workflow implemented in Argo Workflows. The platform owner of Argo Workflows shouldn't be alerted when the CI step fails, because a `continueOn` step reports this failure directly on the GitHub PR that triggered the workflow.
- Others had a similar issue: https://github.com/argoproj/argo-workflows/discussions/13084

---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment] 2024-07-13 18:41
Sounds like a duplicate of #12530

**Closed by agilgur5** 2024-07-13 18:41 UTC
Labels: type/feature
