### ISSUE TITLE
Workflow Archive database connections are not closed

### ISSUE THREAD

**Issue by n1klasD** [argoproj/argo-workflows#10498] opened 2023-02-10 09:01 UTC
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

About two days after upgrading Argo to v3.4.5, my team noticed, that workflows are not archived anymore. 
We are using a Postgres database manged by Azure to archive workflows. 

When digging into the error, we noticed that the number of active connections to our database only increases over time, and eventually hits the limit of active connections. This then results in workflows not being archived anymore.

We did a manual restart of the argo workflows controller, which then closes the connections as expected. 
This was the initial configuration in our configmap that caused the issues: 

``` yaml
persistence:
    archive: true
    nodeStatusOffLoad: true
    postgresql:
      database: argo
      host: ***
      passwordSecret:
        key: ***
        name: ***
      port: ***
      ssl: true
      sslMode: require
      tableName: argo_workflows
```

To resolve the issues, we tried to add the `connectionPool` setting as seen below, but that did not change anything.

``` yaml
persistence:
    connectionPool:
      maxIdleConns: 100
      maxOpenConns: 0
    archive: true
    nodeStatusOffLoad: true
    postgresql:
      database: argo
      host: ***
      passwordSecret:
        key: ***
        name: ***
      port: ***
      ssl: true
      sslMode: require
      tableName: argo_workflows
```

For now we had to revert to argo workflows v3.4.4, and the issue was gone. 

### Version

v.3.4.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Applies to all of our workflows
```

### Logs from the workflow controller

```text
time="2023-02-10T08:50:22.633Z" level=info msg="Enforcing history limit for 'WORKFLOW1'" namespace=NAMESPACE1 workflow=WORKFLOW1
time="2023-02-10T08:50:22.634Z" level=info msg="Enforcing history limit for 'WORKFLOW2'" namespace=NAMESPACE2 workflow=WORKFLOW2
time="2023-02-10T08:50:22.634Z" level=info msg="Enforcing history limit for 'WORKFLOW3'" namespace=NAMESPACE3 workflow=WORKFLOW3
time="2023-02-10T08:50:22.634Z" level=info msg="Enforcing history limit for 'WORKFLOW4'" namespace=NAMESPACE4 workflow=WORKFLOW4
time="2023-02-10T08:50:22.634Z" level=info msg="Enforcing history limit for 'WORKFLOW5'" namespace=NAMESPACE3 workflow=WORKFLOW5
time="2023-02-10T08:50:22.634Z" level=info msg="Enforcing history limit for 'WORKFLOW6'" namespace=NAMESPACE2 workflow=WORKFLOW6
time="2023-02-10T08:50:22.634Z" level=info msg="Enforcing history limit for 'WORKFLOW7'" namespace=NAMESPACE2 workflow=WORKFLOW7
time="2023-02-10T08:50:22.634Z" level=info msg="Enforcing history limit for 'WORKFLOW8'" namespace=NAMESPACE2 workflow=WORKFLOW8
time="2023-02-10T08:50:22.634Z" level=info msg="Enforcing history limit for 'WORKFLOW9'" namespace=NAMESPACE4 workflow=WORKFLOW9
time="2023-02-10T08:50:25.013Z" level=info msg="Get leases 200"
time="2023-02-10T08:50:25.025Z" level=info msg="Update leases 200"
time="2023-02-10T08:50:27.417Z" level=info msg="Watch configmaps 200"
time="2023-02-10T08:50:29.709Z" level=info msg="List workflows 200"
time="2023-02-10T08:50:30.037Z" level=info msg="Get leases 200"
time="2023-02-10T08:50:30.048Z" level=info msg="Update leases 200"
time="2023-02-10T08:50:32.638Z" level=info msg="Enforcing history limit for 'WORKFLOW1'" namespace=NAMESPACE1 workflow=WORKFLOW1
time="2023-02-10T08:50:32.638Z" level=info msg="Enforcing history limit for 'WORKFLOW2'" namespace=NAMESPACE2 workflow=WORKFLOW2
time="2023-02-10T08:50:32.638Z" level=info msg="Enforcing history limit for 'WORKFLOW3'" namespace=NAMESPACE3 workflow=WORKFLOW3
time="2023-02-10T08:50:32.639Z" level=info msg="Enforcing history limit for 'WORKFLOW4'" namespace=NAMESPACE4 workflow=WORKFLOW4
time="2023-02-10T08:50:32.639Z" level=info msg="Enforcing history limit for 'WORKFLOW5'" namespace=NAMESPACE3 workflow=WORKFLOW5
time="2023-02-10T08:50:32.639Z" level=info msg="Enforcing history limit for 'WORKFLOW6'" namespace=NAMESPACE2 workflow=WORKFLOW6
time="2023-02-10T08:50:32.639Z" level=info msg="Enforcing history limit for 'WORKFLOW7'" namespace=NAMESPACE2 workflow=WORKFLOW7
time="2023-02-10T08:50:32.639Z" level=info msg="Enforcing history limit for 'WORKFLOW8'" namespace=NAMESPACE2 workflow=WORKFLOW8
time="2023-02-10T08:50:32.639Z" level=info msg="Enforcing history limit for 'WORKFLOW9'" namespace=NAMESPACE4 workflow=WORKFLOW9
time="2023-02-10T08:50:34.618Z" level=info msg="Watch pods 200"
time="2023-02-10T08:50:35.056Z" level=info msg="Get leases 200"
time="2023-02-10T08:50:35.070Z" level=info msg="Update leases 200"
time="2023-02-10T08:50:35.421Z" level=info msg="Watch workflowtasksets 200"
time="2023-02-10T08:50:40.082Z" level=info msg="Get leases 200"
```

### Logs from in your workflow's wait container

```text
-
```

**Comment by jkldrr** [comment] 2023-02-10 12:53
![grafik](https://user-images.githubusercontent.com/64646731/218097126-78f8b579-47ef-4cd1-b334-ff46e490e36f.png)

**Comment by n1klasD** [comment] 2023-02-10 12:57
> ![grafik](https://user-images.githubusercontent.com/64646731/218097126-78f8b579-47ef-4cd1-b334-ff46e490e36f.png)

Here you can see the number of active connections to the database, that increase over time. At the sharp drops, the controller was restarted manually.

**Comment by tooptoop4** [comment] 2023-02-10 21:13
v3.4.5 is also broken with https://github.com/argoproj/argo-workflows/issues/10490

**Comment by tooptoop4** [comment] 2023-02-15 07:12
@sxllwx do u think this is caused by https://github.com/argoproj/argo-workflows/pull/10140 ?

**Comment by jawadqur** [comment] 2023-02-15 16:06
We are also running into this issue. Added the workaround from @n1klasD so far.

**Comment by tooptoop4** [comment] 2023-02-25 21:53
maybe related to https://github.com/argoproj/argo-workflows/pull/10300

**Comment by reddymh** [comment] 2023-02-26 03:40
> maybe related to #10300

Postgres SSL changes are not related to any connection change and didn't change any code which is related to postgres connection
And @10300 changes are not yet released but committed into the master after v3.4.5 release (See the latest release changelog) and waiting for the release and this changes is for adding SSL certificate while making connection to postgress with sslmode as require|verify-ca|verify-full|prefer.
After the release argo helm chart changes has to be merge.

**Comment by alexec** [comment] 2023-03-05 18:18
I can't see any CHANGELOG.md entries for v3.4.5 that looks likely to have caused this. Perhaps we could modify the code to use a default value for `connMaxLifetime: 300s` so this value is always set.

@reddymh would you like to submit a PR?

**Comment by reddymh** [comment] 2023-03-06 05:37
@alexec  I can do this change by adding the default connection max lifetime to 300s if this is not defined in the configmap.

**Comment by tmshn** [comment] 2023-03-22 10:05
I believe the issue is introduced here: https://github.com/argoproj/argo-workflows/pull/10218

It update configs and DB sessions of the workflow controller along with every updates of the configmap; but the problem is it doesn't close the old session before creating new one.

**Closed** 2023-03-24 18:32 UTC
Labels: bug, regression, workaround, P1
