### ISSUE TITLE
`Pod was active on the node longer than the specified deadline` issue with v3.4.2+

### ISSUE THREAD

**Issue by sakshimalani** [argoproj/argo-workflows#11156] opened 2023-05-31 07:53 UTC
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

We have upgraded argo-workflow to v3.4.8 and workflow controller pod is running fine. However, workflow pods are giving below message-
**level=info msg="Pod failed: Pod was active on the node longer than the specified deadline"**
This issue was observed from v3.4.2 onwards.
This issue is not allowing us to upgrade to latest version and older versions are having security violations.

There is already an issue created regarding this https://github.com/argoproj/argo-workflows/issues/9934 but there is no recent updates.

### Version

v3.4.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
We cannot share those information.
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep kaas-external-secrets-canary-1685518200

time="2023-05-31T07:33:27.121Z" level=info msg="node changed" namespace=external-secrets new.message= new.phase=Running new.progress=0/1 nodeID=kaas-external-secrets-canary-1685518200-1847453086 old.message= old.phase=Running old.progress=0/1 workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:27.122Z" level=info msg="SG Outbound nodes of kaas-external-secrets-canary-1685518200-3820792552 are [kaas-external-secrets-canary-1685518200-1729983040]" namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:27.123Z" level=info msg="Workflow step group node kaas-external-secrets-canary-1685518200-3290429874 not yet completed" namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:27.123Z" level=info msg="Workflow step group node kaas-external-secrets-canary-1685518200-413055525 not yet completed" namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:27.123Z" level=info msg="Workflow step group node kaas-external-secrets-canary-1685518200-155986833 not yet completed" namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:27.123Z" level=info msg="TaskSet Reconciliation" namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:27.123Z" level=info msg=reconcileAgentPod namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:27.126Z" level=info msg="cleaning up pod" action=terminateContainers key=external-secrets/kaas-external-secrets-canary-1685518200-create-external-secret-1847453086/terminateContainers
time="2023-05-31T07:33:27.139Z" level=info msg="Workflow update successful" namespace=external-secrets phase=Running resourceVersion=138104858 workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:28.149Z" level=info msg="Processing workflow" namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:28.153Z" level=info msg="Task-result reconciliation" namespace=external-secrets numObjs=0 workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:28.154Z" level=warning msg="workflow uses legacy/insecure pod patch, see https://argoproj.github.io/argo-workflows/workflow-rbac/" namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:28.154Z" level=info msg="node unchanged" namespace=external-secrets nodeID=kaas-external-secrets-canary-1685518200-1847453086 workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:28.155Z" level=info msg="SG Outbound nodes of kaas-external-secrets-canary-1685518200-3820792552 are [kaas-external-secrets-canary-1685518200-1729983040]" namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:28.156Z" level=info msg="Workflow step group node kaas-external-secrets-canary-1685518200-3290429874 not yet completed" namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:28.156Z" level=info msg="Workflow step group node kaas-external-secrets-canary-1685518200-413055525 not yet completed" namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:28.156Z" level=info msg="Workflow step group node kaas-external-secrets-canary-1685518200-155986833 not yet completed" namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:28.156Z" level=info msg="TaskSet Reconciliation" namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:28.156Z" level=info msg=reconcileAgentPod namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:28.159Z" level=info msg="cleaning up pod" action=terminateContainers key=external-secrets/kaas-external-secrets-canary-1685518200-create-external-secret-1847453086/terminateContainers
time="2023-05-31T07:33:30.091Z" level=info msg="Processing workflow" namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:30.094Z" level=info msg="Task-result reconciliation" namespace=external-secrets numObjs=0 workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:30.095Z" level=info msg="Pod failed: Pod was active on the node longer than the specified deadline" displayName="create-external-secret(0)" namespace=external-secrets pod=kaas-external-secrets-canary-1685518200-create-external-secret-1847453086 templateName= workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:30.095Z" level=warning msg="workflow uses legacy/insecure pod patch, see https://argoproj.github.io/argo-workflows/workflow-rbac/" namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:30.095Z" level=info msg="node changed" namespace=external-secrets new.message="Pod was active on the node longer than the specified deadline" new.phase=Failed new.progress=0/1 nodeID=kaas-external-secrets-canary-1685518200-1847453086 old.message= old.phase=Running old.progress=0/1 workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:30.096Z" level=info msg="SG Outbound nodes of kaas-external-secrets-canary-1685518200-3820792552 are [kaas-external-secrets-canary-1685518200-1729983040]" namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:30.097Z" level=info msg="Node not set to be retried after status: Failed" namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:30.097Z" level=info msg="node kaas-external-secrets-canary-1685518200-2582881683 phase Running -> Failed" namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:30.097Z" level=info msg="node kaas-external-secrets-canary-1685518200-2582881683 message: Pod was active on the node longer than the specified deadline" namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:30.097Z" level=info msg="node kaas-external-secrets-canary-1685518200-2582881683 finished: 2023-05-31 07:33:30.097882456 +0000 UTC" namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:30.097Z" level=info msg="Step group node kaas-external-secrets-canary-1685518200-3290429874 deemed failed: child 'kaas-external-secrets-canary-1685518200-2582881683' failed" namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:30.097Z" level=info msg="node kaas-external-secrets-canary-1685518200-3290429874 phase Running -> Failed" namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:30.097Z" level=info msg="node kaas-external-secrets-canary-1685518200-3290429874 message: child 'kaas-external-secrets-canary-1685518200-2582881683' failed" namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:30.097Z" level=info msg="node kaas-external-secrets-canary-1685518200-3290429874 finished: 2023-05-31 07:33:30.097969288 +0000 UTC" namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
time="2023-05-31T07:33:30.097Z" level=info msg="step group kaas-external-secrets-canary-1685518200-3290429874 was unsuccessful: child 'kaas-external-secrets-canary-1685518200-2582881683' failed" namespace=external-secrets workflow=kaas-external-secrets-canary-1685518200
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=kaas-external-secrets-canary-1685518200,workflow.argoproj.io/phase!=Succeeded

time="2023-05-31T07:32:08.488Z" level=info msg="Starting Workflow Executor" version=v3.4.8
time="2023-05-31T07:32:08.514Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2023-05-31T07:32:08.514Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=external-secrets podName=kaas-external-secrets-canary-1685518200-create-external-secret-1847453086 template="{\"name\":\"create-external-secret\",\"inputs\":{\"parameters\":[{\"name\":\"name\",\"value\":\"external-secrets-cluster-ok-kaas-external-secrets-canary-1685518200-default-region\"},{\"name\":\"kind\",\"value\":\"ClusterSecretStore\"},{\"name\":\"storename\",\"value\":\"default\"},{\"name\":\"dataFrom\",\"value\":\"platform/kaas/tests/esdummy\"}]},\"outputs\":{\"parameters\":[{\"name\":\"name\",\"valueFrom\":{\"jsonPath\":\"{.metadata.name}\"}},{\"name\":\"status\",\"valueFrom\":{\"jsonPath\":\"{.status.conditions[0].status}\"}}]},\"metadata\":{},\"resource\":{\"action\":\"create\",\"manifest\":\"apiVersion: external-secrets.io/v1beta1\\nkind: ExternalSecret\\nmetadata:\\n  name: external-secrets-cluster-ok-kaas-external-secrets-canary-1685518200-default-region\\n  ownerReferences:\\n  - apiVersion: argoproj.io/v1alpha1\\n    blockOwnerDeletion: true\\n    controller: true\\n    kind: Workflow\\n    name: kaas-external-secrets-canary-1685518200\\n    uid: 7f795b10-f643-4708-9f91-6813d9508568\\nspec:\\n  data:\\n  - remoteRef:\\n      key: platform/kaas/tests/esdummy\\n      property: test\\n    secretKey: test.txt\\n  secretStoreRef:\\n    kind: ClusterSecretStore\\n    name: default\\n  target:\\n    creationPolicy: Owner\\n    name: external-secrets-cluster-ok-kaas-external-secrets-canary-1685518200-default-region\\n\",\"setOwnerReference\":true,\"successCondition\":\"status.conditions.0.status\"},\"activeDeadlineSeconds\":90,\"retryStrategy\":{\"limit\":\"2\",\"retryPolicy\":\"OnTransientError\"}}" version="&Version{Version:v3.4.8,BuildDate:2023-05-25T22:19:57Z,GitCommit:9e27baee4b3be78bb662ffa5e3a06f8a6c28fb53,GitTag:v3.4.8,GitTreeState:clean,GoVersion:go1.20.4,Compiler:gc,Platform:linux/amd64,}"
time="2023-05-31T07:32:08.514Z" level=info msg="Loading manifest to /tmp/manifest.yaml"
time="2023-05-31T07:32:08.531Z" level=info msg="kubectl create -f /tmp/manifest.yaml -o json"
time="2023-05-31T07:32:13.893Z" level=info msg="Resource: external-secrets/externalsecret.external-secrets.io/external-secrets-cluster-ok-kaas-external-secrets-canary-1685518200-default-region. SelfLink: apis/external-secrets.io/v1beta1/namespaces/external-secrets/externalsecrets/external-secrets-cluster-ok-kaas-external-secrets-canary-1685518200-default-region"
time="2023-05-31T07:32:13.895Z" level=info msg="Waiting for conditions: status.conditions.0.status"
time="2023-05-31T07:32:13.908Z" level=info msg="Get externalsecrets 200"
time="2023-05-31T07:32:13.908Z" level=info msg="success condition '{status.conditions.0.status exists []}' evaluated false"
time="2023-05-31T07:32:13.908Z" level=info msg="0/1 success conditions matched"
time="2023-05-31T07:32:13.908Z" level=info msg="Waiting for resource externalsecret.external-secrets.io/external-secrets-cluster-ok-kaas-external-secrets-canary-1685518200-default-region in namespace external-secrets resulted in retryable error: Neither success condition nor the failure condition has been matched. Retrying..."
time="2023-05-31T07:32:18.926Z" level=info msg="Get externalsecrets 200"
time="2023-05-31T07:32:18.928Z" level=info msg="success condition '{status.conditions.0.status exists []}' evaluated true"
time="2023-05-31T07:32:18.928Z" level=info msg="1/1 success conditions matched"
time="2023-05-31T07:32:18.928Z" level=info msg="Returning from successful wait for resource externalsecret.external-secrets.io/external-secrets-cluster-ok-kaas-external-secrets-canary-1685518200-default-region in namespace external-secrets"
time="2023-05-31T07:32:18.928Z" level=info msg="Saving resource output parameters"
time="2023-05-31T07:32:18.928Z" level=info msg="kubectl -n external-secrets get externalsecret.external-secrets.io/external-secrets-cluster-ok-kaas-external-secrets-canary-1685518200-default-region -o jsonpath={.metadata.name}"
I0531 07:32:20.194960      16 request.go:601] Waited for 1.085736944s due to client-side throttling, not priority and fairness, request: GET:https://172.20.0.1:443/apis/coordination.k8s.io/v1?timeout=32s
I0531 07:32:30.383454      16 request.go:601] Waited for 11.273407084s due to client-side throttling, not priority and fairness, request: GET:https://172.20.0.1:443/apis/vpcresources.k8s.aws/v1beta1?timeout=32s
I0531 07:32:40.384243      16 request.go:601] Waited for 9.390073843s due to client-side throttling, not priority and fairness, request: GET:https://172.20.0.1:443/apis/kyverno.io/v1beta1?timeout=32s
time="2023-05-31T07:32:46.401Z" level=info msg=kubectl args="[kubectl -n external-secrets get externalsecret.external-secrets.io/external-secrets-cluster-ok-kaas-external-secrets-canary-1685518200-default-region -o jsonpath={.metadata.name}]" error="<nil>" out=external-secrets-cluster-ok-kaas-external-secrets-canary-1685518200-default-region
time="2023-05-31T07:32:46.401Z" level=info msg="Saved output parameter: name, value: external-secrets-cluster-ok-kaas-external-secrets-canary-1685518200-default-region"
time="2023-05-31T07:32:46.401Z" level=info msg="kubectl -n external-secrets get externalsecret.external-secrets.io/external-secrets-cluster-ok-kaas-external-secrets-canary-1685518200-default-region -o jsonpath={.status.conditions[0].status}"
I0531 07:32:50.547507      16 request.go:601] Waited for 3.073673583s due to client-side throttling, not priority and fairness, request: GET:https://172.20.0.1:443/apis/kyverno.io/v1beta1?timeout=32s
I0531 07:33:00.741916      16 request.go:601] Waited for 2.188778516s due to client-side throttling, not priority and fairness, request: GET:https://172.20.0.1:443/apis/autoscaling/v2beta1?timeout=32s
I0531 07:33:10.742275      16 request.go:601] Waited for 12.18230736s due to client-side throttling, not priority and fairness, request: GET:https://172.20.0.1:443/apis/argoproj.io/v1alpha1?timeout=32s
time="2023-05-31T07:33:13.947Z" level=info msg=kubectl args="[kubectl -n external-secrets get externalsecret.external-secrets.io/external-secrets-cluster-ok-kaas-external-secrets-canary-1685518200-default-region -o jsonpath={.status.conditions[0].status}]" error="<nil>" out=True
time="2023-05-31T07:33:13.947Z" level=info msg="Saved output parameter: status, value: True"
time="2023-05-31T07:33:13.948Z" level=info msg="Create workflowtaskresults 403"
time="2023-05-31T07:33:13.948Z" level=warning msg="failed to patch task set, falling back to legacy/insecure pod patch, see https://argoproj.github.io/argo-workflows/workflow-rbac/" error="workflowtaskresults.argoproj.io is forbidden: User \"system:serviceaccount:external-secrets:external-secrets-tests\" cannot create resource \"workflowtaskresults\" in API group \"argoproj.io\" in the namespace \"external-secrets\""
time="2023-05-31T07:33:14.003Z" level=info msg="Patch pods 200"
time="2023-05-31T07:33:15.008Z" level=info msg="sub-process exited" argo=true error="<nil>"
```

**Comment by sarabala1979** [comment] 2023-06-01 17:27
@sakshimalani can you provide your workflow yaml? Do you have configured workflowduration or activepoddeadlineseconds on workflow?

**Comment by vadasambar** [comment] 2023-06-06 11:56
@sarabala1979 thank you for looking at this and sorry for the delay in response. We are seeing this issue intermittently. What we know is, it happens when the churn is high on the cluster. 

> can you provide your workflow yaml? Do you have configured workflowduration or activepoddeadlineseconds on workflow?

I am looking for answers around this as well. As of now, I haven't found a particular workflow which helps re-create this issue. 

What we have observed is we start seeing `Pod failed: Pod was active on the node longer than the specified deadline` when we upgrade from v3.3.8 to v3.4.5, v3.4.6, v3.4.7 (we see the issue in all of them). AFAIK, we haven't changed something in workflow (and workflowtemplates) during the upgrade. 

Maybe the workflow configuration used in v3.3.8 is not the best configuration for v3.4.5, v3.4.6 and v3.4.7 OR maybe there is some hard-to-reproduce bug in the workflows controller.

**Comment by themoonstone** [comment] 2023-06-13 02:15
I'm having the same issue too in version 3.4.5. 
when error msg "Pod failed: Pod was active on the node longer than the specified deadline" occurs. I found that the wait container and main container in this pod is still running

**Comment by themoonstone** [comment] 2023-06-13 03:07
https://github.com/kubernetes/kubernetes/issues/98718  @sakshimalani 
hello, you can check your K8s version, it may be because the k8s version is too old. the error occrus when I used version 1.20.8.  but the error no longer occurs when  I user the latest version.

**Comment by kalpanathanneeru21** [comment] 2023-06-15 11:02
Currently our k8s version is 1.23  and latest release of argo-workflows v3.4.8 should be compatible.
https://argoproj.github.io/argo-workflows/releases/#kubernetes-compatibility-matrix

**Comment by cdemarco-drw** [comment] 2023-09-25 19:00
This is also affecting us. Can anybody give an update as to whether there's work happening on this issue?

**Comment by agilgur5** [comment] 2024-05-11 14:04
> There is already an issue created regarding this #9934 but there is no recent updates.

Closing as #9934 has been resolved per https://github.com/argoproj/argo-workflows/issues/9934#issuecomment-2026619789 by #12329 / #12761.

Please don't file duplicate issues for something that is already open. That doesn't help with getting it resolved and in fact takes up more triage time and divides up users and maintainers who find one issue but not the other.

See also: https://justinmayer.com/posts/any-updates/, https://sindresorhus.com/blog/issue-bumping

**Closed by agilgur5** 2024-05-11 14:04 UTC
Labels: type/bug, type/regression, area/controller, P1
