### ISSUE TITLE
Argo UI : archived workflows > main logs > "Try getting logs from the artifacts" error

### ISSUE THREAD

**Issue by christopheblin** [argoproj/argo-workflows#6015] opened 2021-05-26 09:32 UTC
## Summary 

When you click on a pod of an archived workflow, you can click on "Main logs"

When you click on "Main logs" and the pod have been deleted by the ttlStrategy, you are seeing an empty window

Fine, this is explained that the logs do not appear when the pod has been deleted.

However, when you click on the message "Try getting the logs from the artifacts", it displays a 502 with my nginx ingress (so I suppose this is a link that does not exist)

![Capture d’écran 2021-05-26 à 11 23 11](https://user-images.githubusercontent.com/11044877/119636453-f12fd800-be14-11eb-8bb8-b95df96c1ac7.png)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by svmaris** [comment] 2021-05-26 09:52
This is a duplicate of #5983

**Closed** 2021-05-26 15:32 UTC
