### ISSUE TITLE
argo litmus chaos not able to reflect the exact status or logs

### ISSUE THREAD

**Issue by bmanikantareddy** [argoproj/argo-workflows#11173] opened 2023-06-03 10:56 UTC
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When we run the Argo/argowf-native-pod-delete.yaml with argo submit Argo/argowf-native-pod-delete.yaml its able to created the workflow.

I have an issue that this worflow is not reflecting in litmus UI.
I have an issue that argo worflow still shows success even though the experiment failed. and I didn't find a way to see the failed experiment helper pod logs in argo UI or litmus UI as we are running them via argo.

https://github.com/litmuschaos/chaos-workflows/tree/master/Argo

### Version

v3.4.8+9e27bae.dirty

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
This is the argo watch output
Name:                custom-pod-memory-hog-7fd5w
Namespace:           litmus
ServiceAccount:      argo-chaos
Status:              Succeeded
Conditions:
 PodRunning          False
 Completed           True
Created:             Sat Jun 03 16:19:34 +0530 (1 minute ago)
Started:             Sat Jun 03 16:19:34 +0530 (1 minute ago)
Finished:            Sat Jun 03 16:21:31 +0530 (now)
Duration:            1 minute 57 seconds
Progress:            2/2
ResourcesDuration:   3m10s*(1 cpu),3m10s*(100Mi memory)
Parameters:
  adminModeNamespace: litmus

STEP                              TEMPLATE                   PODNAME                                                           DURATION  MESSAGE
 ✔ custom-pod-memory-hog-7fd5w    custom-chaos
 ├───✔ install-chaos-experiments  install-chaos-experiments  custom-pod-memory-hog-7fd5w-install-chaos-experiments-3677427404  34s
 └───✔ pod-memory-hog-0fx         pod-memory-hog-0fx         custom-pod-memory-hog-7fd5w-pod-memory-hog-0fx-3465651147         1m

Even though the experiment that launched via argo workflow failed.
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

time="2023-06-03T10:49:34.093Z" level=info msg="Processing workflow" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:49:34.104Z" level=info msg="Updated phase  -> Running" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:49:34.105Z" level=info msg="Steps node custom-pod-memory-hog-7fd5w initialized Running" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:49:34.105Z" level=info msg="StepGroup node custom-pod-memory-hog-7fd5w-1458599889 initialized Running" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:49:34.105Z" level=info msg="Pod node custom-pod-memory-hog-7fd5w-3677427404 initialized Pending" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:49:34.229Z" level=info msg="Created pod: custom-pod-memory-hog-7fd5w[0].install-chaos-experiments (custom-pod-memory-hog-7fd5w-install-chaos-experiments-3677427404)" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:49:34.229Z" level=info msg="Workflow step group node custom-pod-memory-hog-7fd5w-1458599889 not yet completed" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:49:34.229Z" level=info msg="TaskSet Reconciliation" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:49:34.229Z" level=info msg=reconcileAgentPod namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:49:34.261Z" level=info msg="Workflow update successful" namespace=litmus phase=Running resourceVersion=26828175 workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:49:44.221Z" level=info msg="Processing workflow" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:49:44.222Z" level=info msg="Task-result reconciliation" namespace=litmus numObjs=0 workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:49:44.222Z" level=info msg="node changed" namespace=litmus new.message= new.phase=Running new.progress=0/1 nodeID=custom-pod-memory-hog-7fd5w-3677427404 old.message= old.phase=Pending old.progress=0/1 workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:49:44.222Z" level=info msg="Workflow step group node custom-pod-memory-hog-7fd5w-1458599889 not yet completed" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:49:44.222Z" level=info msg="TaskSet Reconciliation" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:49:44.222Z" level=info msg=reconcileAgentPod namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:49:44.241Z" level=info msg="Workflow update successful" namespace=litmus phase=Running resourceVersion=26828245 workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:50:18.225Z" level=info msg="Processing workflow" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:50:18.225Z" level=info msg="Task-result reconciliation" namespace=litmus numObjs=0 workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:50:18.225Z" level=info msg="node changed" namespace=litmus new.message= new.phase=Succeeded new.progress=0/1 nodeID=custom-pod-memory-hog-7fd5w-3677427404 old.message= old.phase=Running old.progress=0/1 workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:50:18.226Z" level=info msg="Step group node custom-pod-memory-hog-7fd5w-1458599889 successful" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:50:18.226Z" level=info msg="node custom-pod-memory-hog-7fd5w-1458599889 phase Running -> Succeeded" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:50:18.226Z" level=info msg="node custom-pod-memory-hog-7fd5w-1458599889 finished: 2023-06-03 10:50:18.226546533 +0000 UTC" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:50:18.226Z" level=info msg="StepGroup node custom-pod-memory-hog-7fd5w-2465404124 initialized Running" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:50:18.226Z" level=info msg="SG Outbound nodes of custom-pod-memory-hog-7fd5w-3677427404 are [custom-pod-memory-hog-7fd5w-3677427404]" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:50:18.226Z" level=info msg="Pod node custom-pod-memory-hog-7fd5w-3465651147 initialized Pending" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:50:18.320Z" level=info msg="Created pod: custom-pod-memory-hog-7fd5w[1].pod-memory-hog-0fx (custom-pod-memory-hog-7fd5w-pod-memory-hog-0fx-3465651147)" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:50:18.320Z" level=info msg="Workflow step group node custom-pod-memory-hog-7fd5w-2465404124 not yet completed" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:50:18.320Z" level=info msg="TaskSet Reconciliation" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:50:18.320Z" level=info msg=reconcileAgentPod namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:50:18.338Z" level=info msg="Workflow update successful" namespace=litmus phase=Running resourceVersion=26828436 workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:50:18.344Z" level=info msg="cleaning up pod" action=labelPodCompleted key=litmus/custom-pod-memory-hog-7fd5w-install-chaos-experiments-3677427404/labelPodCompleted
time="2023-06-03T10:50:28.322Z" level=info msg="Processing workflow" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:50:28.322Z" level=info msg="Task-result reconciliation" namespace=litmus numObjs=0 workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:50:28.322Z" level=info msg="node changed" namespace=litmus new.message= new.phase=Running new.progress=0/1 nodeID=custom-pod-memory-hog-7fd5w-3465651147 old.message= old.phase=Pending old.progress=0/1 workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:50:28.323Z" level=info msg="SG Outbound nodes of custom-pod-memory-hog-7fd5w-3677427404 are [custom-pod-memory-hog-7fd5w-3677427404]" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:50:28.323Z" level=info msg="Workflow step group node custom-pod-memory-hog-7fd5w-2465404124 not yet completed" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:50:28.323Z" level=info msg="TaskSet Reconciliation" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:50:28.323Z" level=info msg=reconcileAgentPod namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:50:28.350Z" level=info msg="Workflow update successful" namespace=litmus phase=Running resourceVersion=26828539 workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:51:31.449Z" level=info msg="Processing workflow" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:51:31.449Z" level=info msg="Task-result reconciliation" namespace=litmus numObjs=0 workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:51:31.450Z" level=info msg="node changed" namespace=litmus new.message= new.phase=Succeeded new.progress=0/1 nodeID=custom-pod-memory-hog-7fd5w-3465651147 old.message= old.phase=Running old.progress=0/1 workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:51:31.450Z" level=info msg="SG Outbound nodes of custom-pod-memory-hog-7fd5w-3677427404 are [custom-pod-memory-hog-7fd5w-3677427404]" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:51:31.450Z" level=info msg="Step group node custom-pod-memory-hog-7fd5w-2465404124 successful" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:51:31.450Z" level=info msg="node custom-pod-memory-hog-7fd5w-2465404124 phase Running -> Succeeded" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:51:31.450Z" level=info msg="node custom-pod-memory-hog-7fd5w-2465404124 finished: 2023-06-03 10:51:31.450528982 +0000 UTC" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:51:31.450Z" level=info msg="Outbound nodes of custom-pod-memory-hog-7fd5w-3465651147 is [custom-pod-memory-hog-7fd5w-3465651147]" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:51:31.450Z" level=info msg="Outbound nodes of custom-pod-memory-hog-7fd5w is [custom-pod-memory-hog-7fd5w-3465651147]" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:51:31.450Z" level=info msg="node custom-pod-memory-hog-7fd5w phase Running -> Succeeded" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:51:31.450Z" level=info msg="node custom-pod-memory-hog-7fd5w finished: 2023-06-03 10:51:31.450593264 +0000 UTC" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:51:31.450Z" level=info msg="Checking daemoned children of custom-pod-memory-hog-7fd5w" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:51:31.450Z" level=info msg="TaskSet Reconciliation" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:51:31.450Z" level=info msg=reconcileAgentPod namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:51:31.450Z" level=info msg="Updated phase Running -> Succeeded" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:51:31.450Z" level=info msg="Marking workflow completed" namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:51:31.450Z" level=info msg="Checking daemoned children of " namespace=litmus workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:51:31.456Z" level=info msg="cleaning up pod" action=deletePod key=litmus/custom-pod-memory-hog-7fd5w-1340600742-agent/deletePod
time="2023-06-03T10:51:31.474Z" level=info msg="Workflow update successful" namespace=litmus phase=Succeeded resourceVersion=26828911 workflow=custom-pod-memory-hog-7fd5w
time="2023-06-03T10:51:31.501Z" level=info msg="cleaning up pod" action=labelPodCompleted key=litmus/custom-pod-memory-hog-7fd5w-pod-memory-hog-0fx-3465651147/labelPodCompleted
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=custom-pod-memory-hog-7fd5w,workflow.argoproj.io/phase!=Succeeded

 kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=custom-pod-memory-hog-7fd5w,workflow.argoproj.io/phase!=Succeeded

No resources found in argo namespace.
```

**Comment by terrytangyuan** [comment] 2023-06-03 16:30
I don't think this issue belongs here. Perhaps submit to litmus repo?

**Comment by JPZ13** [comment] 2023-06-08 17:17
Hey @bmanikantareddy - we unfortunately don't have the capacity to troubleshoot projects that use Argo WF as a runtime given there are several of them. Since this doesn't seem to be a bug related to Argo WF itself but is rather a bug in Litmus, I'm going to close this issue. Could you file a bug ticket on the Litmus repo? If in the investigation, there is an Argo-specific bug that can be reproduced without using Litmus, we can re-open the issue

**Closed by JPZ13** 2023-06-08 17:17 UTC
