### ISSUE TITLE
How to connect to argo-server on linux using java sdk on windows?

### ISSUE THREAD

**Issue by jinbu6666** [argoproj/argo-workflows#12875] opened 2024-04-03 06:45 UTC
# Summary

Hello, when I was using java api to create a workflow, I got an error connecting to argo-server on another server. The error is as follows:

```
Exception when calling WorkflowServiceApi#workflowServiceCreateWorkflow
Status code: 0
Reason: null
Response headers: null
io.argoproj.workflow.ApiException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
at io.argoproj.workflow.ApiClient.execute(ApiClient.java:928)
at io.argoproj.workflow.apis.WorkflowServiceApi.workflowServiceCreateWorkflowWithHttpInfo(WorkflowServiceApi.java:172)
at io.argoproj.workflow.apis.WorkflowServiceApi.workflowServiceCreateWorkflow(WorkflowServiceApi.java:151)
at Demo.main(Demo.java:366)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964)
at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:328)
at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322)
at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614)
at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
at io.argoproj.workflow.ApiClient.execute(ApiClient.java:924)
... 3 more
```

I also tried to do the sdk trust certificate, but the content of the certificate is unstable, and the connection is still unable because of ip. I wonder if there is any good solution for connecting argo-server on linux server using java sdk in windows environment? Search for solution.

## Use Cases

```java
ApiClient defaultClient = Configuration.getDefaultApiClient();
       defaultClient.setBasePath("https://192.168.61.32:2746");
```

---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment] 2024-04-09 05:13
Duplicate of #12874. This is more appropriate for the GH Discussion given that it's a support question (and not a feature request).

**Closed by agilgur5** 2024-04-09 05:13 UTC
Labels: area/sdks, type/support
