### ISSUE TITLE
Expose the name of the cronworkflow to the pods

### ISSUE THREAD

**Issue by pgaxatte** [argoproj/argo-workflows#4793] opened 2020-12-22 10:31 UTC
# Summary

Kinda similarly to issue #1279, argo should support exposing the name of the cron that created the workflow with a label on the pods.

# Use Cases

This is especially useful to extract metrics and alerts by cron.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment] 2020-12-22 17:35
You should be able to do this using `{{workflow.name}}`

**Comment by pgaxatte** [comment] 2021-01-04 14:54
Currently, when only looking at the pods created by a CronWorkflow, there is no way to know correlate the information.

I have a concrete example where I would need this: I use CronWorkflows to backup something and I'd like to be able to monitor the state of the pods created by the workflows at each run of the cron.

**Comment by alexec** [comment] 2021-01-04 16:57
@simster7 - any thoughts?

**Comment by simster7** [comment] 2021-01-04 17:07
@pgaxatte Can't you infer this from the pod name?

If I have CronWorkflow `hello-world`, then it will create Workflow with name `hello-world-1609779960`, which will create Pods with name like `hello-world-1609779960-1646182790`

**Comment by simster7** [comment] 2021-01-04 17:08
Or would you like the labels for grouping, sorting in K8s and not necessarily for them to be accessible within the Pod?

**Comment by agilgur5** [comment] 2023-09-01 08:02
I think #7611 and #11663 are more descriptive proposal of this, so will close as duplicate of those.

**Closed by agilgur5** 2023-09-01 08:02 UTC
Labels: enhancement, area/cron-workflows
