### ISSUE TITLE
Enable user to input parameters in argo server UI

### ISSUE THREAD

**Issue by vax-r** [argoproj/argo-workflows#11580] opened 2023-08-15 06:32 UTC
# Summary

Add features to allow user to type in input parameters in argo server UI for argo workflow

# Use Cases

I am using argo workflow to create multiple branch in my github repo so I can trigger many CD process at the same time without create them manually.

Now I hope I can alter the value of input parameters directly from argo UI, so I can make my workflow template more portable and other users can use my template and type in the parameters directly.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment] 2023-09-02 18:00
This is already possible. See https://argoproj.github.io/argo-workflows/intermediate-inputs/.
Not sure if you meant something else or something more specific?

#5319 added this, making a duplicate of #4234.
#8472 also added suspended/supplied/interactive values support to the UI (issues: #6665, #8425).

**Closed by agilgur5** 2023-09-02 18:00 UTC
Labels: enhancement, area/ui
