### ISSUE TITLE
Support Complex schedule expression in CronWorkflow

### ISSUE THREAD

**Issue by t-arata** [argoproj/argo-workflows#12493] opened 2024-01-09 16:00 UTC
# Summary

Improve CronWorkflow to support multiple complex cron schedules.

## What change needs making?

Currently, a single CronWorkflow can only be configured with a single cron expression. This makes it hard to configure complex schedules that can't be expressed with a single cron expression. To resolve this, I suggest that we improve CronWorkflow to allow the usage of multiple cron expressions in a single CronWorkflow resource.

## Use Cases:

I have a script that I need to run on a complex schedule, which isn't expressible with a single cron expression. The schedule changes within the day, week, and month as follows:

```
0  11    *  *  1-5 /path/to/some_process
20 11-13 *  *  1-5 /path/to/some_process
50 11-18 21 09 *   /path/to/some_process
50 11-18 24 10 *   /path/to/some_process
```

With the current implementation, I'd need to create a separate CronWorkflow for each schedule. It comes with some inconveniences: having to manage multiple CronWorkflows and the possibility of the script executed by different CronWorkflows at the same time, causing overlapping execution.

By allowing a single CronWorkflow to take multiple cron expressions, it will ease the management of schedules and ensure that the same script is not run by different CronWorkflows simultaneously.

---
**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritize the proposals with the most 👍.

**Comment by eduardodbr** [comment] 2024-01-15 11:51
Probably duplicate of #9734, #8348, #8347

**Comment by skewer35** [comment] 2024-01-29 21:49
need this very much as well

**Closed** 2024-02-19 04:18 UTC
Labels: area/controller, area/cron-workflows
