### ISSUE TITLE
Setting base-href to "/argo/" and then accessing via portforward does not work.

### ISSUE THREAD

**Issue by ramanNarasimhan77** [argoproj/argo-workflows#11643] opened 2023-08-21 08:07 UTC
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I installed https://github.com/argoproj/argo-workflows/blob/master/manifests/quick-start-minimal.yaml 

Made the following changes.
1. Added extra server argument `--insecure=true` for testing without tls
2. Added env BASE_HREF as `/argo/`
3. Changed HTTPS to HTTP in container probe

![image](https://github.com/argoproj/argo-workflows/assets/52691361/e0241567-b5b8-457b-8749-fe2da740299c)

I port-forwarded Argo-server:2746 to localhost:2747 and got blank page

![image](https://github.com/argoproj/argo-workflows/assets/52691361/7d1fd985-c567-4a4c-98ba-b96e53422228)

I expected to be able to see the Argo home page at "/argo/"

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
NA
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

NA
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

NA
```

**Comment by agilgur5** [comment] 2023-08-21 08:09
Looks like a duplicate of #10194 which I literally just answered 😅

**Closed by agilgur5** 2023-08-21 08:09 UTC
Labels: bug

**Comment by agilgur5** [comment] 2023-08-21 08:19
From your screenshot, `<base href="/argo/">`, so that is working correctly.

Per my most [recent comment](https://github.com/argoproj/argo-workflows/issues/10194#issuecomment-1685866941) in #10194, you might be looking for `rootpath` support, i.e. #7767

**Comment by ramanNarasimhan77** [comment] 2023-08-21 08:27
Thank you for the clarification @agilgur5
