### ISSUE TITLE
Python SDK not able to get workflowtemplate list

### ISSUE THREAD

**Issue by mgloder** [argoproj/argo-workflows#10941] opened 2023-04-18 15:50 UTC
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

* the api call can return the correct workflow template data, for example, 
```
"metadata": {
        "resourceVersion": "38368833"
    },
    "items": [
        {
            "metadata": {
                "name": ".....",
                "namespace": "....",
                ....
        },
```
but the sdk failed to parse the result to `IoArgoprojWorkflowV1alpha1WorkflowTemplateList` data type

### Version

6.4.7

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
any workflow template
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by changhc** [comment] 2023-05-19 18:43
Hi @sarabala1979, I looked into this issue and found out the root cause. It's not a problem about the SDK but about the API gateway.

When `WorkflowTemplateServer` talks to kubernetes, messages are exchanged in JSON format and empty slices are populated as `[]`, so `WorkflowTemplateServer` can unmarshal the empty slices correctly. However, these empty slices are omitted when they are passed to the API gateway using gRPC. The API gateway simply takes them as `nil` and the json encoder serialises them as `null`. A sample response is as follows:

```
> curl http://localhost:2746/api/v1/workflow-templates/argo
{'items': null, 'metadata': {'resource_version': '16377'}}
```

while `items` should be `[]`. This null value fails validation in the python SDK, which is what @MGloder observed. I believe this problem applies to any resource containing an empty slice.

To fix this, we need to populate empty lists in the serialiser. I implemented this and tested locally and could fetch empty lists as expected using both `curl` and the python SDK. The downside is that it increases response time because type reflections need to be performed recursively for every single entry returned.

I'm not sure if this problem also exists in the Java SDK, but even if it doesn't, I think the right way of fixing this is to update the serialiser because now the API response does not match the API spec anyway. We can also update the API spec, e.g., marking the field as nullable, to get rid of this whole issue, but to me that sounds like distorting the spec and will probably harm usability.

If my solution sounds okay to you, I can create a PR. What do you think?

**Comment by tooptoop4** [comment] 2024-09-30 20:49
have u tried hera/couler?

**Comment by MasonM** [comment] 2024-12-16 05:19
The Python SDK has been deprecated (https://github.com/argoproj/argo-workflows/pull/13719), so I'm going to go ahead and close this. Here's a list of community-maintained libraries you can use instead: https://argo-workflows.readthedocs.io/en/latest/client-libraries/#community-maintained-client-libraries

**Closed by MasonM** 2024-12-16 05:19 UTC
Labels: area/sdks, P3
