### ISSUE TITLE
Need a way to support each step's spec in a modular way

### ISSUE THREAD

**Issue by dvavili** [argoproj/argo-workflows#576] opened 2017-12-10 08:24 UTC
Currently, the entire workflow needs to be specified in a single file. It'll be good to have a way to specify each pod spec individually and just stitch the workflow referencing these pod spec location.

**Comment by dvavili** [comment] 2017-12-10 08:29
This may be similar to how helm charts are organized and handled

**Comment by jessesuen** [comment] 2017-12-11 21:58
This is actually something that been discussed internally off and on for some time now. The crux of the problem is that in order to support the ability to reference other templates, you need context. Context could be something like a relative or absolute filepath. Or it could be a globally unique name. With filepaths, the problem is that YAML can have multiple specs contained in a single file, so filepath alone is not a good identifier. Furthermore, we believe that adding understanding of context into the workflow manifest itself is outside the purview of the workflow YAML.

Being able to reference/inline other pieces of YAML into a "main" yaml is a problem that is not unique to Argo. At the moment this is something we are hoping that higher level tooling like ksonnet can solve for us.

**Comment by bhack** [comment] 2018-01-31 13:48
See also https://github.com/kubernetes/helm/issues/2577

**Comment by jessesuen** [comment] 2018-01-31 22:53
Just to update where we are at on this issue. I'm working on generating an argo workflow.libsonnet to see what the end user experience is like to use ksonnet + argo libsonnet to generate and possibly submit their workflows. This requires some OpenAPI work/tooling which is mostly done.

**Comment by prarabdh9909** [comment] 2019-06-03 05:52
Thanks @jessesuen ! Looking forward to it.

**Comment by prarabdh9909** [comment] 2019-06-03 06:45
Don't know if it helps but tektoncd tried to solve the same thing by differentiating by  decoupling invocation with functionality using Task and TaskRun.

**Comment by alexec** [comment] 2022-02-07 22:24
This is fixed by workflow templates.

**Closed by alexec** 2022-02-07 22:24 UTC
Labels: area/workflow-templates
