### ISSUE TITLE
UI: Workflow list blocked when limit applied

### ISSUE THREAD

**Issue by alelapi** [argoproj/argo-workflows#12663] opened 2024-02-13 13:34 UTC
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

On the workflow list page, when the total number of workflows exceeds the limit applied in the query string:
(eg: total number of workflows = 150 and `<base_url>/workflows/product-replacement-engine?&limit=140`)
 
the application enters into a loop, continuously repeating the same calls, and blocking any other requests.

![Screenshot 2024-02-13 at 14 34 01](https://github.com/argoproj/argo-workflows/assets/5998461/4bbf610b-8671-427c-a08e-899cdb9d63df)

### Version

v3.5.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
n/a
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
n/a
```

**Comment by agilgur5** [comment] 2024-02-13 13:53
Hmm this might be the same root cause as #12626. I can't tell from looking at the code why this would happen though and haven't had a chance yet to sit down and test it.

**Comment by alelapi** [comment] 2024-02-13 17:38
Seems the same. I believe the cause is in the dependency array of one of the useEffect

**Comment by agilgur5** [comment] 2024-02-13 18:18
Yea that was what I checked first too, but I don't see anything obviously off with it (I even checked to make sure `toString` was stable).
If you're familiar with React, I refactored this whole component to hooks in #11891, where I actually noticed some existing `useEffect` calls had stale refs. I tested to make sure everything updated correctly too since it was a pretty sizeable and complex refactor (one of the largest I've done in recent years). I also reduced the number of network calls in that PR too (it was doing unnecessary lists).

One thing I did noticed was that I seemed to have [written the wrong key for the `offset` query param](https://github.com/argoproj/argo-workflows/blob/66680f1c9bca8b47c40ce918b5d16714058647cb/ui/src/app/workflows/components/workflows-list/workflows-list.tsx#L59), but you're not using `offset`, so I wouldn't think that would impact this specifically. Will fix that ofc, but that doesn't seem like root cause to me yet 🤔

**Comment by agilgur5** [comment] 2024-02-14 19:04
> I tested to make sure everything updated correctly too since it was a pretty sizeable and complex refactor (one of the largest I've done in recent years).

Yea I can't reproduce this locally, I only have one long-running `eventsource` request (SSE) if I don't change any filters:
![Screenshot 2024-02-14 at 1 59 25 PM](https://github.com/argoproj/argo-workflows/assets/4970083/b49f29fb-2114-4eb3-b886-b8e1f2aa7469)

Let me try building 3.5.4 specifically. #12626 suggests it might be an environment issue. Have you tried clearing your `localStorage` and similar caches?

**Comment by agilgur5** [comment] 2024-02-14 21:57
> Hmm this might be the same root cause as #12626.

Hmm actually your issue seems to be different. There none of the requests get cancelled, it just opens multiple (meaning the `useEffect` callback didn't happen) for some reason. In your case, they're quickly opened and closed in succession, ad infinitum.
Potentially same root cause, but the symptoms are different as of right now.

**Comment by agilgur5** [comment] 2024-02-14 22:08
> Let me try building 3.5.4 specifically

Huh I can't reproduce this on 3.5.4 locally either:
![Screenshot 2024-02-14 at 5 07 35 PM](https://github.com/argoproj/argo-workflows/assets/4970083/20b6a5a5-25b7-405e-a4c9-d5335b1904dd)

**Comment by agilgur5** [comment] 2024-02-15 19:11
Ok I was able to _partially_ reproduce this. With pagination on and when moving between pages, I get 2 SSEs and often neither will cancelled after moving pages (sometimes 1 will be cancelled).

![Screenshot 2024-02-15 at 1 54 28 PM](https://github.com/argoproj/argo-workflows/assets/4970083/69cfe11b-55ee-4f84-ab6e-af36080b3763)

The bizarre part is that there is no error in the console and I confirmed with a log statement and other observations that the `useEffect` callback and the `listWatch.stop()` therein is happening.

I can rewrite the logic so that it ensures there is only ever one `listWatch`, but in theory that shouldn't be necessary; I'm super confused why they're not being cancelled each time despite `listWatch.stop()` being called.

This also doesn't happen when I'm not interacting with the page, I still haven't been able to reproduce an infinite loop, nor one with no interaction required.

**Comment by agilgur5** [comment] 2024-02-15 19:29
> I can rewrite the logic so that it ensures there is only ever one `listWatch` with a ref, but in theory that shouldn't be necessary; I'm super confused why they're not being cancelled each time despite `listWatch.stop()` being called.

The plot thickens -- this doesn't fix it. Even with a singular ref, somehow multiple `listWatch`es proliferate. Even when `.stop()` is called before any `.start()`. Even if I set the ref to `null` temporarily after a `.stop()`

**Comment by agilgur5** [comment] 2024-02-16 05:55
> With pagination on and when moving between pages, I get 2 SSEs

Found the main bug, the `nextOffset` of pagination is [set by](https://github.com/argoproj/argo-workflows/blob/81ae4f0567b7f716fcf20fd96593d1c5eff16bee/ui/src/app/workflows/components/workflows-list/workflows-list.tsx#L144C47-L144C76) the `ListWatch` as well as [a dep of its `useEffect`](https://github.com/argoproj/argo-workflows/blob/81ae4f0567b7f716fcf20fd96593d1c5eff16bee/ui/src/app/workflows/components/workflows-list/workflows-list.tsx#L158C95-L158C116). 
Removing that fixes the 2 SSEs. I'm not quite sure how you got an infinite loop though, as it should only happen twice since after the second one it should be constant 🤔 

That also seems to _mostly_ the the `.stop()` not working. Doesn't need a ref and works as-is for the most part.
It seems like `.stop()` may not work properly when called in quick succession after `.start()` as with the 2 SSEs. It seems to be latency dependent, so that would explain why only some people on certain connections have experienced it (e.g. in #12626 they are using HTTP/1). That one predates 3.5.x though and I'm not entirely sure how to fix it; it might be an RxJS issue or a Server or SSE issue with the quick succession.

So I'll fix the main problem that is a regression and hopefully we won't see the `.stop()` issue again nor infinite loops, but those may need further investigating.

**Closed** 2024-02-17 06:23 UTC
Labels: bug, regression, area/ui, P2
