### ISSUE TITLE
Retry a failed Workflow just from failed step/node in UI

### ISSUE THREAD

**Issue by bygui86** [argoproj/argo-workflows#12022] opened 2023-10-17 11:58 UTC
# Summary - What change needs making?

Currently in the UI it's not possible to retry a failed Workflow just from the step/node that failed

For example I have a Workflow with following steps (in a dag):
1. build-code
2. test-code
3. build-container
4. deploy

If for any reason the build-container (3) step fails, in the UI it's not possible to retry the same Workflow starting directly from build-container step instead form the beginning.

It's only possible using Argo CLI with command `argo retry --node-field-selector` (and additionally `--restart-successful` if required).

A tool like Airflow has this feature...

## Use Cases - When would you use this?

1. Exposing the Argo Workflows UI to non-technical people, we could let them restart a workflow without bothering technical people.
2. It's not always possible or safe to let all technical people use Argo CLI, so having such feature in the UI would be a big plus.

## Additional notes

Please see the related discussion [here](https://github.com/argoproj/argo-workflows/discussions/12005)

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment] 2023-10-17 14:44
Duplicate of #10139

**Closed by agilgur5** 2023-10-17 14:44 UTC
Labels: enhancement, area/ui, area/retry
