### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by softwarebloat** [argoproj/argo-workflows#7436] opened 2021-12-17 14:33 UTC
I would like to start contributing to argo workflows but i'm new to Golang and have no experience with this codebase.

I was looking at `good first issue`, in particular the #7239 but wasn't able to reproduce it locally. But probably, even if i reproduced it, i wouldn't know what to do to solve it

> Any `good first issue` would be cool if helps me grasping the code base though

**Comment by alexec** [comment] 2021-12-17 19:56
@sarabala1979 @terrytangyuan @simster7 I'm about to go OOV for 1 month. Could I please ask if you would be interested?

**Comment by terrytangyuan** [comment] 2021-12-19 02:27
Yes, I can help to mentor this.

**Comment by terrytangyuan** [comment] 2021-12-19 02:37
@softwarebloat Could you tell me a bit about what you have tried to reproduce? When I ran `argo submit https://raw.githubusercontent.com/argoproj/argo-workflows/master/examples/http-hello-world.yaml --watch`, I observed the `0/0` progress. Could you try that? 

If you'd like to work on #7239, one potential cause of this issue is that we currently do not support reading progress from HTTP type node. Some relevant code: https://github.com/argoproj/argo-workflows/blob/master/workflow/progress/updater.go. I haven't looked into details yet but you could start understanding the code relevant to progress updating and understand  its relation to the implementation of HTTP template https://github.com/argoproj/argo-workflows/pull/5750.

**Comment by softwarebloat** [comment] 2021-12-19 20:29
@terrytangyuan you are right, i can reproduce it (i was using a wrong workflow example).

The **updater.go** file was really helpful thanks! I also check the HTTP template PR (#5750) but was really big, more difficult to understand everything :sweat_smile: 
but the problem seems to be in the `updater.go`

I wrote a test and also think i fixed the bug but, while the test passed, if i submit the workflow i still see `progress 0/0`.
Is `make start API=true` enough? i also tried to run `make clean` and `make build` before but nothing changed.

And also, if i try to run `make pre-commit -B` i get the following
```
make pre-commit -B
GIT_COMMIT=0f567ffe2ab2d81fe308901d13acdac954323405 GIT_BRANCH=fix/http-templates-progress GIT_TAG=untagged GIT_TREE_STATE=dirty RELEASE_TAG=false DEV_BRANCH=true VERSION=latest
KUBECTX=k3d-argo-workflow DOCKER_DESKTOP=false K3D=true DOCKER_PUSH=false
RUN_MODE=local PROFILE=minimal AUTH_MODE=hybrid SECURE=false STATIC_FILES=false ALWAYS_OFFLOAD_NODE_STATUS=false UPPERIO_DB_DEBUG=0 LOG_LEVEL=debug NAMESPACED=true
cp -v hack/git/hooks/commit-msg .git/hooks/commit-msg
'hack/git/hooks/commit-msg' -> '.git/hooks/commit-msg'
go install k8s.io/code-generator/cmd/go-to-protobuf@v0.21.5
make: *** No rule to make target '/bin/protoc-gen-gogo', needed by 'pkg/apis/workflow/v1alpha1/generated.proto'.  Stop.
```

**Comment by softwarebloat** [comment] 2021-12-21 09:56
@terrytangyuan I opened a draft PR to show you what i've done #7450 
I'm having trouble test it locally. Tests passed but if i try to run argo-workflow i can't see any difference. How should I start the project locally with my new changes? :thinking: 

FYI: i don't even see the controller pod in my local cluster :man_shrugging:

**Comment by terrytangyuan** [comment] 2021-12-21 14:57
Try just building the image locally and then replace your image tag in your installation manifests, e.g. 
```
docker buildx build -t argoproj/workflow-controller:test-image --target argoexec --progress plain .
```

**Comment by softwarebloat** [comment] 2021-12-21 16:08
mmm what do you mean by 
> replace your image in your installation manifests


The only thing i did to run it locally is following this doc https://argoproj.github.io/argo-workflows/running-locally/

**Comment by terrytangyuan** [comment] 2021-12-21 16:21
That should work. Check if your installed controller is using your modified version.

If you want to do that explicitly, you can start your local k3d cluster from scratch, build your images, and then use those new images in your manifests, e.g. 
```
# Build images
IMAGE=test-oss-1
k3d cluster rm k3s-default; k3d cluster create k3s-default; docker buildx build -t argoproj/argoexec:${IMAGE} --target argoexec --progress plain .; docker buildx build -t argoproj/workflow-controller:${IMAGE} --target workflow-controller --progress plain .

# Import the images to k3d cluster
k3d image import argoproj/argoexec:${IMAGE}; k3d image import argoproj/workflow-controller:${IMAGE}
k create namespace argo
# Install the controller
k apply -n argo -f install.yaml
```
Note that this manifest is modified from https://github.com/argoproj/argo-workflows/blob/master/manifests/namespace-install.yaml. The changes are simply replacing the images with the `test-oss-1` image you just built. This ensures that you are using an image that includes your changes.

**Comment by softwarebloat** [comment] 2021-12-21 19:08
mmmm maybe i missed some step. Do i have to install the controller? isn't enough than to run `make start` to install everything needed for local dev? :thinking:

**Comment by softwarebloat** [comment] 2021-12-22 08:46
btw, the draft PR passed all checks.
can you review it and, if everything seems good to you maybe could you also try it locally? (and describe me the steps you do to do so? :pleading_face:)

PR #7450

**Comment by terrytangyuan** [comment] 2021-12-22 14:34
I probably won't have time to try it locally until after the holidays. The steps would be the same as the ones I mentioned above. You had issues with `make start`, which is why I suggested trying my approach that does everything more explicitly and we can debug step by step.

It would be good to get @sarabala1979's review on your PR since he implemented the HTTP template initially but I'd expect some delays as many people are on vacation right now.

**Comment by sarabala1979** [comment] 2021-12-22 14:36
I will take a look

**Comment by softwarebloat** [comment] 2021-12-22 16:53
@terrytangyuan oohh ok i got it sorry. i thought it was like a workaround. i'll try that!!

@sarabala1979 thanks! :rocket:

**Comment by softwarebloat** [comment] 2021-12-23 21:02
@terrytangyuan so, i'm trying with the explicit way and when i run but i got error when trying to import the images in k3d cluster
```bash
k3d image import argoproj/argoexec:${IMAGE}
INFO[0000] Importing image(s) into cluster 'k3s-default' 
WARN[0000] Image 'argoproj/argoexec:test-oss-1' is not a file and couldn't be found in the container runtime 
ERRO[0000] Failed to import image(s) into cluster 'k3s-default': No valid images specified 
WARN[0000] At least one error occured while trying to import the image(s) into the selected cluster(s) 
```
and the error makes sense cause i can't find the images built in `docker images` list

previous steps runs without errors

**Comment by softwarebloat** [comment] 2021-12-24 16:26
I also tried the explicit way suggested by @terrytangyuan but now, when i run `make start` i got an error

```bash
make start
GIT_COMMIT=cda7cd46a7ba6632cf6cb9ce034dabd48a491595 GIT_BRANCH=master GIT_TAG=untagged GIT_TREE_STATE=dirty RELEASE_TAG=false DEV_BRANCH=false VERSION=latest
KUBECTX=k3d-k3s-default DOCKER_DESKTOP=false K3D=true DOCKER_PUSH=false
RUN_MODE=local PROFILE=minimal AUTH_MODE=hybrid SECURE=false STATIC_FILES=false ALWAYS_OFFLOAD_NODE_STATUS=false UPPERIO_DB_DEBUG=0 LOG_LEVEL=debug NAMESPACED=true
kubectl get ns argo || kubectl create ns argo
NAME   STATUS   AGE
argo   Active   85m
kubectl config set-context --current --namespace=argo
Context "k3d-k3s-default" modified.
installing PROFILE=minimal, E2E_EXECUTOR=emissary
kubectl kustomize --load-restrictor=LoadRestrictionsNone test/e2e/manifests/minimal | sed 's|quay.io/argoproj/|argoproj/|' | sed 's/namespace: argo/namespace: argo/' | kubectl -n argo apply --prune -l app.kubernetes.io/part-of=argo -f -
customresourcedefinition.apiextensions.k8s.io/clusterworkflowtemplates.argoproj.io unchanged
customresourcedefinition.apiextensions.k8s.io/cronworkflows.argoproj.io unchanged
customresourcedefinition.apiextensions.k8s.io/eventbus.argoproj.io unchanged
customresourcedefinition.apiextensions.k8s.io/eventsources.argoproj.io unchanged
customresourcedefinition.apiextensions.k8s.io/sensors.argoproj.io unchanged
customresourcedefinition.apiextensions.k8s.io/workfloweventbindings.argoproj.io unchanged
customresourcedefinition.apiextensions.k8s.io/workflows.argoproj.io unchanged
customresourcedefinition.apiextensions.k8s.io/workflowtasksets.argoproj.io unchanged
customresourcedefinition.apiextensions.k8s.io/workflowtemplates.argoproj.io unchanged
serviceaccount/argo unchanged
serviceaccount/argo-server unchanged
serviceaccount/github.com unchanged
role.rbac.authorization.k8s.io/argo-role unchanged
role.rbac.authorization.k8s.io/argo-server-role unchanged
role.rbac.authorization.k8s.io/submit-workflow-template unchanged
role.rbac.authorization.k8s.io/workflow-role unchanged
clusterrole.rbac.authorization.k8s.io/argo-clusterworkflowtemplate-role unchanged
clusterrole.rbac.authorization.k8s.io/argo-server-clusterworkflowtemplate-role unchanged
clusterrole.rbac.authorization.k8s.io/kubelet-executor unchanged
rolebinding.rbac.authorization.k8s.io/argo-binding unchanged
rolebinding.rbac.authorization.k8s.io/argo-server-binding unchanged
rolebinding.rbac.authorization.k8s.io/github.com unchanged
rolebinding.rbac.authorization.k8s.io/workflow-default-binding unchanged
clusterrolebinding.rbac.authorization.k8s.io/argo-clusterworkflowtemplate-role-binding unchanged
clusterrolebinding.rbac.authorization.k8s.io/argo-server-clusterworkflowtemplate-role-binding unchanged
clusterrolebinding.rbac.authorization.k8s.io/kubelet-executor-default unchanged
configmap/artifact-repositories unchanged
configmap/workflow-controller-configmap unchanged
secret/argo-server-sso configured
secret/argo-workflows-webhook-clients configured
secret/my-minio-cred configured
service/argo-server unchanged
service/minio unchanged
service/workflow-controller-metrics unchanged
deployment.apps/minio unchanged
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"labels\":{\"app.kubernetes.io/part-of\":\"argo\"},\"name\":\"argo-server\",\"namespace\":\"argo\"},\"spec\":{\"replicas\":0,\"selector\":{\"matchLabels\":{\"app\":\"argo-server\",\"app.kubernetes.io/part-of\":\"argo\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"argo-server\",\"app.kubernetes.io/part-of\":\"argo\"}},\"spec\":{\"containers\":[{\"args\":[\"server\",\"--secure=false\",\"--auth-mode=hybrid\"],\"image\":\"argoproj/argocli:latest\",\"imagePullPolicy\":\"Never\",\"name\":\"argo-server\",\"ports\":[{\"containerPort\":2746,\"name\":\"web\"}],\"readinessProbe\":{\"httpGet\":{\"path\":\"/\",\"port\":2746,\"scheme\":\"HTTP\"},\"initialDelaySeconds\":10,\"periodSeconds\":20},\"securityContext\":{\"capabilities\":{\"drop\":[\"ALL\"]}},\"volumeMounts\":[{\"mountPath\":\"/tmp\",\"name\":\"tmp\"}]}],\"nodeSelector\":{\"kubernetes.io/os\":\"linux\"},\"securityContext\":{\"runAsNonRoot\":true},\"serviceAccountName\":\"argo-server\",\"volumes\":[{\"emptyDir\":{},\"name\":\"tmp\"}]}}}}\n"},"labels":{"app.kubernetes.io/part-of":"argo"}},"spec":{"replicas":0,"selector":{"matchLabels":{"app.kubernetes.io/part-of":"argo"}},"template":{"metadata":{"labels":{"app.kubernetes.io/part-of":"argo"}},"spec":{"$setElementOrder/containers":[{"name":"argo-server"}],"containers":[{"args":["server","--secure=false","--auth-mode=hybrid"],"image":"argoproj/argocli:latest","imagePullPolicy":"Never","name":"argo-server","readinessProbe":{"httpGet":{"scheme":"HTTP"}}}]}}}}
to:
Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"
Name: "argo-server", Namespace: "argo"
for: "STDIN": Deployment.apps "argo-server" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"argo-server", "app.kubernetes.io/part-of":"argo"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"labels\":{\"app.kubernetes.io/part-of\":\"argo\"},\"name\":\"workflow-controller\",\"namespace\":\"argo\"},\"spec\":{\"replicas\":0,\"selector\":{\"matchLabels\":{\"app\":\"workflow-controller\",\"app.kubernetes.io/part-of\":\"argo\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"workflow-controller\",\"app.kubernetes.io/part-of\":\"argo\"}},\"spec\":{\"containers\":[{\"args\":[\"--configmap\",\"workflow-controller-configmap\",\"--executor-image\",\"argoproj/argoexec:latest\",\"--namespaced\"],\"command\":[\"workflow-controller\"],\"env\":[{\"name\":\"LEADER_ELECTION_IDENTITY\",\"valueFrom\":{\"fieldRef\":{\"apiVersion\":\"v1\",\"fieldPath\":\"metadata.name\"}}}],\"image\":\"argoproj/workflow-controller:latest\",\"imagePullPolicy\":\"Never\",\"livenessProbe\":{\"failureThreshold\":3,\"httpGet\":{\"path\":\"/healthz\",\"port\":6060},\"initialDelaySeconds\":90,\"periodSeconds\":60,\"timeoutSeconds\":30},\"name\":\"workflow-controller\",\"ports\":[{\"containerPort\":9090,\"name\":\"metrics\"},{\"containerPort\":6060}],\"securityContext\":{\"allowPrivilegeEscalation\":false,\"capabilities\":{\"drop\":[\"ALL\"]},\"readOnlyRootFilesystem\":true,\"runAsNonRoot\":true}}],\"nodeSelector\":{\"kubernetes.io/os\":\"linux\"},\"securityContext\":{\"runAsNonRoot\":true},\"serviceAccountName\":\"argo\"}}}}\n"},"labels":{"app.kubernetes.io/part-of":"argo"}},"spec":{"replicas":0,"selector":{"matchLabels":{"app.kubernetes.io/part-of":"argo"}},"template":{"metadata":{"labels":{"app.kubernetes.io/part-of":"argo"}},"spec":{"$setElementOrder/containers":[{"name":"workflow-controller"}],"containers":[{"args":["--configmap","workflow-controller-configmap","--executor-image","argoproj/argoexec:latest","--namespaced"],"image":"argoproj/workflow-controller:latest","imagePullPolicy":"Never","name":"workflow-controller"}]}}}}
to:
Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"
Name: "workflow-controller", Namespace: "argo"
for: "STDIN": Deployment.apps "workflow-controller" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"workflow-controller", "app.kubernetes.io/part-of":"argo"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
make: *** [Makefile:399: install] Error 1
```

**Comment by terrytangyuan** [comment] 2021-12-26 02:41
You have an existing and incompatible installation in the cluster. Try removing the cluster and starting from scratch: `k3d cluster rm k3s-default; k3d cluster create k3s-default`.

**Comment by softwarebloat** [comment] 2021-12-26 09:58
already tried that but nothing changed. same error.

in the `namespace-install.yml` i only changed the image from `quay.io/argoproj/workflow-controller:latest` to `argoproj/workflow-controller:test-oss-1` (same for the argoexec one)
is it correct, right?!

**Comment by softwarebloat** [comment] 2021-12-28 10:20
so, i tried to clean some stuff and delete again the k3d cluster.
now, if i re-create it without manually building the **argoexec** and **controller** images, `make start` "works" but actually it doesn't (as stated above)
i have no controller/server pods and deployments looks like this:
```
NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
argo-server           0/0     0            0           3m47s
workflow-controller   0/0     0            0           3m47s
minio                 1/1     1            1           3m47s
```

then, after succesfully built and imported the images but i got that error while trying to apply the modified manifest:
```bash
k apply -f manifests/namespace-install.yaml 
customresourcedefinition.apiextensions.k8s.io/clusterworkflowtemplates.argoproj.io configured
customresourcedefinition.apiextensions.k8s.io/cronworkflows.argoproj.io configured
customresourcedefinition.apiextensions.k8s.io/workfloweventbindings.argoproj.io configured
customresourcedefinition.apiextensions.k8s.io/workflows.argoproj.io configured
customresourcedefinition.apiextensions.k8s.io/workflowtasksets.argoproj.io configured
customresourcedefinition.apiextensions.k8s.io/workflowtemplates.argoproj.io configured
serviceaccount/argo configured
serviceaccount/argo-server configured
role.rbac.authorization.k8s.io/argo-role configured
role.rbac.authorization.k8s.io/argo-server-role configured
rolebinding.rbac.authorization.k8s.io/argo-binding configured
rolebinding.rbac.authorization.k8s.io/argo-server-binding configured
configmap/workflow-controller-configmap configured
service/argo-server configured
service/workflow-controller-metrics configured
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"name\":\"argo-server\",\"namespace\":\"argo\"},\"spec\":{\"selector\":{\"matchLabels\":{\"app\":\"argo-server\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"argo-server\"}},\"spec\":{\"containers\":[{\"args\":[\"server\",\"--namespaced\"],\"image\":\"quay.io/argoproj/argocli:latest\",\"name\":\"argo-server\",\"ports\":[{\"containerPort\":2746,\"name\":\"web\"}],\"readinessProbe\":{\"httpGet\":{\"path\":\"/\",\"port\":2746,\"scheme\":\"HTTPS\"},\"initialDelaySeconds\":10,\"periodSeconds\":20},\"securityContext\":{\"capabilities\":{\"drop\":[\"ALL\"]}},\"volumeMounts\":[{\"mountPath\":\"/tmp\",\"name\":\"tmp\"}]}],\"nodeSelector\":{\"kubernetes.io/os\":\"linux\"},\"securityContext\":{\"runAsNonRoot\":true},\"serviceAccountName\":\"argo-server\",\"volumes\":[{\"emptyDir\":{},\"name\":\"tmp\"}]}}}}\n"},"labels":null},"spec":{"replicas":null,"selector":{"matchLabels":{"app.kubernetes.io/part-of":null}},"template":{"metadata":{"labels":{"app.kubernetes.io/part-of":null}},"spec":{"$setElementOrder/containers":[{"name":"argo-server"}],"containers":[{"args":["server","--namespaced"],"imagePullPolicy":null,"name":"argo-server","readinessProbe":{"httpGet":{"scheme":"HTTPS"}}}]}}}}
to:
Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"
Name: "argo-server", Namespace: "argo"
for: "manifests/namespace-install.yaml": Deployment.apps "argo-server" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"argo-server"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"name\":\"workflow-controller\",\"namespace\":\"argo\"},\"spec\":{\"selector\":{\"matchLabels\":{\"app\":\"workflow-controller\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"workflow-controller\"}},\"spec\":{\"containers\":[{\"args\":[\"--configmap\",\"workflow-controller-configmap\",\"--executor-image\",\"quay.io/argoproj/argoexec:latest\",\"--namespaced\"],\"command\":[\"workflow-controller\"],\"env\":[{\"name\":\"LEADER_ELECTION_IDENTITY\",\"valueFrom\":{\"fieldRef\":{\"apiVersion\":\"v1\",\"fieldPath\":\"metadata.name\"}}}],\"image\":\"quay.io/argoproj/workflow-controller:latest\",\"livenessProbe\":{\"failureThreshold\":3,\"httpGet\":{\"path\":\"/healthz\",\"port\":6060},\"initialDelaySeconds\":90,\"periodSeconds\":60,\"timeoutSeconds\":30},\"name\":\"workflow-controller\",\"ports\":[{\"containerPort\":9090,\"name\":\"metrics\"},{\"containerPort\":6060}],\"securityContext\":{\"allowPrivilegeEscalation\":false,\"capabilities\":{\"drop\":[\"ALL\"]},\"readOnlyRootFilesystem\":true,\"runAsNonRoot\":true}}],\"nodeSelector\":{\"kubernetes.io/os\":\"linux\"},\"securityContext\":{\"runAsNonRoot\":true},\"serviceAccountName\":\"argo\"}}}}\n"},"labels":null},"spec":{"replicas":null,"selector":{"matchLabels":{"app.kubernetes.io/part-of":null}},"template":{"metadata":{"labels":{"app.kubernetes.io/part-of":null}},"spec":{"$setElementOrder/containers":[{"name":"workflow-controller"}],"containers":[{"imagePullPolicy":null,"name":"workflow-controller"}]}}}}
to:
Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"
Name: "workflow-controller", Namespace: "argo"
for: "manifests/namespace-install.yaml": Deployment.apps "workflow-controller" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"workflow-controller"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

**Comment by terrytangyuan** [comment] 2022-01-03 15:44
Could you try `kubectl create -f manifests/namespace-install.yaml`?

**Comment by terrytangyuan** [comment] 2022-01-03 15:51
Also looks like you ran `make start` and then built, import images followed by a `kubectl apply`. This is why you are seeing the error above. Please try the commands I suggested for now without running `make start`.

**Comment by softwarebloat** [comment] 2022-01-04 09:50
oh you are right, without running `make start` first, it works. But should i then run `make start`?? or how should i run the application after applying the modified manifest?!

and also, do you know why i'm facing this problem with `make start`? :thinking:

**Comment by terrytangyuan** [comment] 2022-01-11 14:07
@softwarebloat Thank you for your contribution and congrats on getting your first PR merged!

**Closed by terrytangyuan** 2022-01-11 14:07 UTC
Labels: enhancement
