### ISSUE TITLE
Templates named filter when added to dependencies caused error

### ISSUE THREAD

**Issue by firecast** [argoproj/argo-workflows#12308] opened 2023-12-01 10:03 UTC
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Workflow should run as normal independent of template names. I think `filter` is a keyword in the `depends` expression evaluation. If the name of the dag template is changed, it works as expected. Error seen in Argo UI. The same works in Argo v3.4.9 which we had running previously.

```
unable to evaluate expression '(filter.Succeeded || filter.Skipped || filter.Daemoned)': unable to evaluate expression '(filter.Succeeded || filter.Skipped || filter.Daemoned)': type func(...interface {}) (interface {}, error)[string] is undefined (1:9) | (filter.Succeeded || filter.Skipped || filter.Daemoned) | ........^
```

### Version

v3.5.2

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: filter-example
  namespace: default
spec:
  podGC:
    strategy: OnPodSuccess
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: filter
        template: filter
      - name: un-filter
        dependencies:
        - filter
        template: filter

  - name: filter
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```
```


### Logs from the workflow controller

```text
time="2023-12-01T10:01:03.710Z" level=info msg="Processing workflow" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:01:03.750Z" level=info msg="Task-result reconciliation" namespace=default numObjs=0 workflow=filter-example-8wr6j
time="2023-12-01T10:01:03.750Z" level=info msg="Updated phase  -> Running" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:01:03.754Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:01:03.755Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:01:03.755Z" level=info msg="Retry node filter-example-8wr6j initialized Running" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:01:03.755Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:01:03.755Z" level=info msg="DAG node filter-example-8wr6j-3268908687 initialized Running" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:01:03.755Z" level=warning msg="was unable to obtain the node for filter-example-8wr6j-1267657701, taskName un-filter"
time="2023-12-01T10:01:03.755Z" level=warning msg="was unable to obtain the node for filter-example-8wr6j-1751296445, taskName filter"
time="2023-12-01T10:01:03.755Z" level=warning msg="was unable to obtain the node for filter-example-8wr6j-1751296445, taskName filter"
time="2023-12-01T10:01:03.755Z" level=info msg="All of node filter-example-8wr6j(0).filter dependencies [] completed" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:01:03.755Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:01:03.755Z" level=info msg="Retry node filter-example-8wr6j-1751296445 initialized Running" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:01:03.755Z" level=info msg="Pod node filter-example-8wr6j-4207907020 initialized Pending" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:01:03.773Z" level=info msg="Created pod: filter-example-8wr6j(0).filter(0) (filter-example-8wr6j-filter-4207907020)" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:01:03.773Z" level=warning msg="was unable to obtain the node for filter-example-8wr6j-1267657701, taskName un-filter"
time="2023-12-01T10:01:03.773Z" level=warning msg="was unable to obtain the node for filter-example-8wr6j-1267657701, taskName un-filter"
time="2023-12-01T10:01:03.773Z" level=info msg="TaskSet Reconciliation" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:01:03.773Z" level=info msg=reconcileAgentPod namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:01:03.795Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=868061 workflow=filter-example-8wr6j
time="2023-12-01T10:02:03.711Z" level=info msg="Processing workflow" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:03.712Z" level=info msg="Task-result reconciliation" namespace=default numObjs=1 workflow=filter-example-8wr6j
time="2023-12-01T10:02:03.712Z" level=info msg="task-result changed" namespace=default nodeID=filter-example-8wr6j-4207907020 workflow=filter-example-8wr6j
time="2023-12-01T10:02:03.712Z" level=warning msg="workflow uses legacy/insecure pod patch, see https://argoproj.github.io/argo-workflows/workflow-rbac/" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:03.712Z" level=info msg="node changed" namespace=default new.message= new.phase=Succeeded new.progress=0/1 nodeID=filter-example-8wr6j-4207907020 old.message= old.phase=Pending old.progress=0/1 workflow=filter-example-8wr6j
time="2023-12-01T10:02:03.712Z" level=warning msg="was unable to obtain the node for filter-example-8wr6j-1267657701, taskName un-filter"
time="2023-12-01T10:02:03.713Z" level=info msg="node filter-example-8wr6j-1751296445 phase Running -> Succeeded" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:03.713Z" level=info msg="node filter-example-8wr6j-1751296445 finished: 2023-12-01 10:02:03.713044153 +0000 UTC" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:03.713Z" level=warning msg="was unable to obtain the node for filter-example-8wr6j-1267657701, taskName un-filter"
time="2023-12-01T10:02:03.717Z" level=info msg="Skipped node filter-example-8wr6j-1267657701 initialized Error (message: unable to evaluate expression '(filter.Succeeded || filter.Skipped || filter.Daemoned)': unable to evaluate expression '(filter.Succeeded || filter.Skipped || filter.Daemoned)': type func(...interface {}) (interface {}, error)[string] is undefined (1:9)\n | (filter.Succeeded || filter.Skipped || filter.Daemoned)\n | ........^)" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:03.717Z" level=info msg="Outbound nodes of filter-example-8wr6j-3268908687 set to [filter-example-8wr6j-1267657701]" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:03.717Z" level=info msg="node filter-example-8wr6j-3268908687 phase Running -> Error" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:03.717Z" level=info msg="node filter-example-8wr6j-3268908687 finished: 2023-12-01 10:02:03.71753539 +0000 UTC" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:03.717Z" level=info msg="node filter-example-8wr6j message: Backoff for 1 second" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:03.717Z" level=info msg="TaskSet Reconciliation" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:03.717Z" level=info msg=reconcileAgentPod namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:03.973Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=868267 workflow=filter-example-8wr6j
time="2023-12-01T10:02:04.719Z" level=info msg="Processing workflow" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:04.719Z" level=info msg="Task-result reconciliation" namespace=default numObjs=1 workflow=filter-example-8wr6j
time="2023-12-01T10:02:04.719Z" level=info msg="task-result changed" namespace=default nodeID=filter-example-8wr6j-4207907020 workflow=filter-example-8wr6j
time="2023-12-01T10:02:04.719Z" level=warning msg="workflow uses legacy/insecure pod patch, see https://argoproj.github.io/argo-workflows/workflow-rbac/" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:04.720Z" level=info msg="node unchanged" namespace=default nodeID=filter-example-8wr6j-4207907020 workflow=filter-example-8wr6j
time="2023-12-01T10:02:04.720Z" level=info msg="node has maxDuration set, setting executionDeadline to: Mon Jan 01 00:00:00 +0000 (a long while ago)" namespace=default node=filter-example-8wr6j workflow=filter-example-8wr6j
time="2023-12-01T10:02:04.720Z" level=info msg="node filter-example-8wr6j message: " namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:04.720Z" level=info msg="Retry Policy: OnError (onFailed: false, onError true)" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:04.720Z" level=info msg="1 child nodes of filter-example-8wr6j failed. Trying again..." namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:04.724Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:04.724Z" level=info msg="DAG node filter-example-8wr6j-651850386 initialized Running" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:04.724Z" level=warning msg="was unable to obtain the node for filter-example-8wr6j-1782282744, taskName un-filter"
time="2023-12-01T10:02:04.724Z" level=warning msg="was unable to obtain the node for filter-example-8wr6j-3602526966, taskName filter"
time="2023-12-01T10:02:04.724Z" level=warning msg="was unable to obtain the node for filter-example-8wr6j-3602526966, taskName filter"
time="2023-12-01T10:02:04.724Z" level=info msg="All of node filter-example-8wr6j(1).filter dependencies [] completed" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:04.724Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:04.724Z" level=info msg="Retry node filter-example-8wr6j-3602526966 initialized Running" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:04.725Z" level=info msg="Pod node filter-example-8wr6j-1243279349 initialized Pending" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:04.746Z" level=info msg="Created pod: filter-example-8wr6j(1).filter(0) (filter-example-8wr6j-filter-1243279349)" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:04.746Z" level=warning msg="was unable to obtain the node for filter-example-8wr6j-1782282744, taskName un-filter"
time="2023-12-01T10:02:04.746Z" level=warning msg="was unable to obtain the node for filter-example-8wr6j-1782282744, taskName un-filter"
time="2023-12-01T10:02:04.746Z" level=info msg="TaskSet Reconciliation" namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:04.746Z" level=info msg=reconcileAgentPod namespace=default workflow=filter-example-8wr6j
time="2023-12-01T10:02:04.770Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=868272 workflow=filter-example-8wr6j
xtime="2023-12-01T10:02:08.975Z" level=info msg="cleaning up pod" action=deletePod key=default/filter-example-8wr6j-filter-4207907020/deletePod
```

### Logs from in your workflow's wait container

```text
NA, the errored pod does not start
```

**Comment by Joibel** [comment] 2023-12-01 11:15
This is a duplicate of #12037, same root cause. Filter is a function in the `expr` library we use.

**Closed by Joibel** 2023-12-01 11:15 UTC
Labels: bug, regression, area/templating, P2, duplicate
