### ISSUE TITLE
Trying to access artifacts from archived workflows breaks the UI

### ISSUE THREAD

**Issue by nikita-akuity** [argoproj/argo-workflows#9772] opened 2022-10-08 03:34 UTC
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

The artifact preview works perfectly with unarchived workflows, but when I'm trying to access same artifacts from the archived workflow I get this:

https://user-images.githubusercontent.com/102942773/194685536-96617d9b-28c9-44be-bcd6-84b06a128ced.mov

Artifacts stored in AWS S3 with IRSA authentication.

Stacktrace:
```
react-dom.production.min.js:209 TypeError: Cannot read properties of undefined (reading 'type')
    at t.WorkflowNodeInfo (workflow-node-info.tsx:471:28)
    at Gi (react-dom.production.min.js:153:146)
    at gs (react-dom.production.min.js:261:496)
    at ul (react-dom.production.min.js:246:265)
    at sl (react-dom.production.min.js:246:194)
    at Xs (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Vo (react-dom.production.min.js:122:325)
    at Ko (react-dom.production.min.js:123:61)
```

Network tab in the debug console:
<img width="1338" alt="Screen Shot 2022-10-07 at 8 12 10 PM" src="https://user-images.githubusercontent.com/102942773/194685686-6b5d0b53-cb1c-4c32-9de4-46d39e9bbbeb.png">

Headers from the failed request:
```
Request URL: https://<url>:2746/api/v1/workflow-events/single-wf-dev?listOptions.fieldSelector=metadata.namespace=single-wf-dev&listOptions.resourceVersion=1230367&fields=result.object.metadata.name,result.object.metadata.namespace,result.object.metadata.resourceVersion,result.object.metadata.creationTimestamp,result.object.metadata.uid,result.object.status.finishedAt,result.object.status.phase,result.object.status.message,result.object.status.startedAt,result.object.status.estimatedDuration,result.object.status.progress,result.type,result.object.metadata.labels,result.object.spec.suspend
Referrer Policy: strict-origin-when-cross-origin
#-----------------
Accept: text/event-stream
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Cookie: authorization=Bearer k8s-aws-v1.<token>
Host: <url>:2746
Referer: https://<url>:2746/workflows/single-wf-dev?limit=50
sec-ch-ua: "Google Chrome";v="105", "Not)A;Brand";v="8", "Chromium";v="105"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
```

### Version

3.4.1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
---
```

### Logs from the workflow controller

Logs from argo server, nothing is here:

```
grpc.service=workflowarchive.ArchivedWorkflowService grpc.start_time="2022-10-08T03:29:18Z" grpc.time_ms=8.271 span.kind=server system=grpc
time="2022-10-08T03:29:18.172Z" level=info duration=12.770649ms method=GET path=/api/v1/archived-workflows size=2920 status=0
time="2022-10-08T03:29:20.389Z" level=info msg="tracking UI usage️️" name=openedArchivedWorkflowDetails
time="2022-10-08T03:29:20.389Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=CollectEvent grpc.service=info.InfoService grpc.start_time="2022-10-08T03:29:20Z" grpc.time_ms=0.665 span.kind=server system=grpc
time="2022-10-08T03:29:20.390Z" level=info duration=1.336136ms method=POST path=/api/v1/tracking/event size=2 status=0
time="2022-10-08T03:29:20.666Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetArchivedWorkflow grpc.service=workflowarchive.ArchivedWorkflowService grpc.start_time="2022-10-08T03:29:20Z" grpc.time_ms=17.007 span.kind=server system=grpc
time="2022-10-08T03:29:20.670Z" level=info duration=20.67733ms method=GET path=/api/v1/archived-workflows/7582af45-29aa-4420-9e37-f4d2a79d265f size=21482 status=0
time="2022-10-08T03:29:21.352Z" level=info duration="119.691µs" method=GET path=index.html size=473 status=0

```

### Logs from in your workflow's wait container

---

**Comment by tooptoop4** [comment] 2022-10-09 05:24
dupe of https://github.com/argoproj/argo-workflows/issues/9627 ?

**Comment by juliev0** [comment] 2022-10-10 15:32
> dupe of #9627 ?

Yes, it seems to be. I added a comment there.

**Comment by tooptoop4** [comment] 2022-10-29 10:06
crispy

**Closed** 2022-10-29 16:32 UTC
Labels: bug, P2
