### ISSUE TITLE
`argo lint`: `failed to resolve {{workflow.labels.workflows.argoproj.io/workflow-template}}` but works when applied and ran

### ISSUE THREAD

**Issue by yay14** [argoproj/argo-workflows#10748] opened 2023-03-24 13:32 UTC
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When we run argo lint, using some variables like `workflow.namespace`, `workflow.labels.workflows.argoproj.io/workflow-template` gives the below error

` in "test-argo-lint" (WorkflowTemplate): templates.test-argo-lint templates.test-argo-lint: failed to resolve {{workflow.labels.workflows.argoproj.io/workflow-template}}`

Even though the templates get applied correctly, and run successfully, the argo lint gives this error? Is it expected or it's a bug on the argo lint side.

The command used to run argo lint. We run a post-renderer script just to convert to valid argo helm template
 `helm template . --post-renderer ./../../post-render.sh > out.yaml && argo lint out.yaml`

### Version

v3.4.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: "test-argo-lint"
  namespace: "argo-workflows-test"
spec:
  templates:
  - name: test-argo-lint
    metrics:
      prometheus:
      - name: step_status_total
        help: "Count of step execution by step name and result status"
        labels:
        - key: name
          value: test-argo-lint
        - key: workflow_template
          value: "[[workflow.labels.workflows.argoproj.io/workflow-template]]"
        - key: status
          value: "[[status]]"
        - key: namespace
          value: "[[workflow.namespace]]"
        counter:
          value: "1"
      - name: step_duration_seconds
        help: "Duration of step execution by step name and workflow template"
        labels:
        - key: name
          value: test-argo-lint
        - key: workflow_template
          value: "[[workflow.labels.workflows.argoproj.io/workflow-template]]"
        - key: namespace
          value: '[[workflow.namespace]]'
        histogram:
          buckets:
          - 60
          - 120
          - 240
          - 480
          - 720
          - 960
          - 1200
          - 1440
          - 1680
          - 1800
          - 2400
          - 4800
          value: "[[duration]]"
    container:
      image: python:alpine3.6
      command: [python, -c]
      # fail with a 66% probability
      args: ["import random; import sys; exit_code = random.choice([0, 1, 1]); sys.exit(exit_code)"]
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

- Logs are not required since it's a lint issue
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by yay14** [comment] 2023-03-28 06:17
@terrytangyuan can someone please guide me here? If it's a small fix, I would take it up, but i need help to get started.

**Comment by yay14** [comment] 2023-03-28 06:18
```
        - key: workflow_template
          value: "[[workflow.labels.workflows.argoproj.io/workflow-template]]"
```

The lint error comes from the above lines ^^

Here we want to pass template name in prometheus metrics , is there any alternative to achieve this?

**Comment by JPZ13** [comment] 2023-03-30 17:21
Hey @yay14 - I quickly linted the sample WorkflowTemplate using the v3.4.5 argo cli, and I didn't experience a linting issue. Here's my terminal output:
```
➜  ui git:(master) argo version
argo: v3.4.5+1253f44.dirty
  BuildDate: 2023-02-07T13:42:52Z
  GitCommit: 1253f443baa8ad1610d2e62ec26ecdc85fe1b837
  GitTreeState: dirty
  GitTag: v3.4.5
  GoVersion: go1.19.5
  Compiler: gc
  Platform: darwin/arm64
➜  ui git:(master) vim sample-template.yaml
➜  ui git:(master) ✗ argo lint sample-template.yaml
✔ no linting errors found!
➜  ui git:(master) ✗
```

Can you confirm whether it's working with an updated CLI on your end?

**Comment by yay14** [comment] 2023-03-31 09:43
Hi @JPZ13 seems to work with the updated version of the cli, thanks for the help!

**Comment by yay14** [comment] 2023-03-31 10:45
Still doesnt work in linux, worked for mac @JPZ13 can you check this?

```argo: v3.4.5
  BuildDate: 2023-02-07T13:22:11Z
  GitCommit: 1253f443baa8ad1610d2e62ec26ecdc85fe1b837
  GitTreeState: clean
  GitTag: v3.4.5
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
Linting banking-accounts
out.yaml:
   ✖ in "banking-accounts-e2e" (WorkflowTemplate): rpc error: code = InvalidArgument desc = templates.main.tasks.post-github-init-notification templates.post-github-notification: failed to resolve {{workflow.labels.workflows.argoproj.io/workflow-template}}
   ✖ in "banking-accounts-master-e2e" (WorkflowTemplate): rpc error: code = InvalidArgument desc = templates.main.tasks.post-github-init-notification templates.post-github-notification: failed to resolve {{workflow.labels.workflows.argoproj.io/workflow-template}}
   ```

**Comment by yay14** [comment] 2023-04-06 09:35
@JPZ13 any updates here?

**Comment by JPZ13** [comment] 2023-04-06 15:56
Hey @yay14 - can you provide the post-render script as well so we can fully repro? If the script is private, feel free to ping me and @tico24 on the Argo Workflows slack channel, but as always we'd rather problem solve on this thread in the open

**Comment by yay14** [comment] 2023-04-18 10:30
@JPZ13 Any update on this?

**Comment by agilgur5** [comment] 2024-06-30 16:38
Was able to reproduce this on `main` after converting the YAML:

```
./dist/argo lint test-workflowtemplate-issue-10748.yml 
test-workflowtemplate-issue-10748.yml:
   ✖ in "test-argo-lint" (WorkflowTemplate): rpc error: code = InvalidArgument desc = templates.test-argo-lint templates.test-argo-lint: failed to resolve {{workflow.labels.workflows.argoproj.io/workflow-template}}

✖ 1 linting errors found!
```

This seems to work fine with an `expr` expression though:
```yaml
          value: "{{=workflow.labels['workflows.argoproj.io/workflow-template']}}"
```
```
./dist/argo lint test-workflowtemplate-issue-10748.yml 
✔ no linting errors found!
```

So I imagine this is due to the dashes, slashes, or dots in the label name

**Comment by agilgur5** [comment] 2024-06-30 16:47
Ah this is actually a duplicate of #10554.

And the workaround there applies here too: https://github.com/argoproj/argo-workflows/issues/10554#issuecomment-1437002673.

Adding the label to your template will make this pass lint:
```yaml
  labels:
    workflows.argoproj.io/workflow-template: "blah"
```

**Closed by agilgur5** 2024-06-30 16:47 UTC
Labels: type/bug, solution/workaround, area/cli, area/templating, P3
