### ISSUE TITLE
Can't use expressions involving {{retries}} in podSpecPatch

### ISSUE THREAD

**Issue by therc** [argoproj/argo-workflows#5219] opened 2021-02-26 00:35 UTC
## Summary 

I get errors when I try to use `{{retries}}` in podSpecPatch, with and without quotes.
This seems to be a variant of https://github.com/argoproj/argo-workflows/issues/4767
I think I'm supposed to quote `{{entries}}`, but that gives me `Error in Unmarshalling after merge the patch`.
Below is the simplest podSpecPatch I could think of. I was really trying something like `"memory": (2 ** {{retries}})+"GB"`. I'm sure there will be other surprises with expressions, but right now I can't figure how to use a plain variable.

Looking at the source, it looks like `retries` is a string. I'm not sure if that's the problem, given that a string is fine the basic case of using the existing variable as is. Maybe it would all magically work if if were an integer, both the variable reference and the arithmetic expression?

## Diagnostics

What Kubernetes provider are you using? 
EKS 1.18

What version of Argo Workflows are you running? 
2.10.2

I made slight tweaks to one of the examples:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: retry-with-steps-
  generation: 3
  labels:
    user: foo
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Failed
    manager: workflow-controller
    operation: Update
    time: "2021-02-25T22:22:28Z"
  name: retry-with-steps-cdvvg
  namespace: argo
spec:
  arguments: {}
  entrypoint: retry-with-steps
  # serviceAccountName: argo
  templates:
  - arguments: {}
    inputs: {}
    metadata: {}
    name: retry-with-steps
    outputs: {}
    steps:
    - - arguments: {}
        name: hello1
        template: random-fail
    - - arguments: {}
        name: hello2a
        template: random-fail
      - arguments: {}
        name: hello2b
        template: random-fail
  - arguments: {}
    container:
      args:
      - 'import random; import sys; print(''retries: {{retries}}''); exit_code = random.choice([0,
        0, 1, 1, 1]); sys.exit(exit_code)'
      command:
      - python
      - -c
      image: python:alpine3.6
      name: ""
      resources: {}
    inputs:
      parameters:
      - name: ret
        value: '{{retries}}'
    metadata:
      labels:
        user: foo
    name: random-fail
    outputs: {}
    podSpecPatch: '{"containers":[{"name":"main", "resources":{"requests":{"cpu":
      {{retries}} }}}]}'
    retryStrategy:
      limit: 10
status:
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2021-02-25T22:22:28Z"
  message: child 'retry-with-steps-cdvvg[0].hello1' errored
  nodes:
    retry-with-steps-cdvvg:
      children:
      - retry-with-steps-cdvvg-3565907139
      displayName: retry-with-steps-cdvvg
      finishedAt: "2021-02-25T22:22:28Z"
      id: retry-with-steps-cdvvg
      message: child 'retry-with-steps-cdvvg[0].hello1' errored
      name: retry-with-steps-cdvvg
      outboundNodes:
      - retry-with-steps-cdvvg-872421055
      phase: Failed
      startedAt: "2021-02-25T22:22:27Z"
      templateName: retry-with-steps
      templateScope: local/retry-with-steps-cdvvg
      type: Steps
    retry-with-steps-cdvvg-872421055:
      boundaryID: retry-with-steps-cdvvg
      displayName: hello1(0)
      finishedAt: "2021-02-25T22:22:28Z"
      hostNodeName: ip-10-1-145-61.ec2.internal
      id: retry-with-steps-cdvvg-872421055
      inputs:
        parameters:
        - name: ret
          value: "0"
      message: Invalid PodSpecPatch String
      name: retry-with-steps-cdvvg[0].hello1(0)
      phase: Error
      startedAt: "2021-02-25T22:22:27Z"
      templateName: random-fail
      templateScope: local/retry-with-steps-cdvvg
      type: Pod
    retry-with-steps-cdvvg-1306962068:
      boundaryID: retry-with-steps-cdvvg
      children:
      - retry-with-steps-cdvvg-872421055
      displayName: hello1
      finishedAt: null
      id: retry-with-steps-cdvvg-1306962068
      inputs:
        parameters:
        - name: ret
          value: '{{retries}}'
      name: retry-with-steps-cdvvg[0].hello1
      phase: Running
      startedAt: "2021-02-25T22:22:27Z"
      templateName: random-fail
      templateScope: local/retry-with-steps-cdvvg
      type: Retry
    retry-with-steps-cdvvg-3565907139:
      boundaryID: retry-with-steps-cdvvg
      children:
      - retry-with-steps-cdvvg-1306962068
      displayName: '[0]'
      finishedAt: "2021-02-25T22:22:28Z"
      id: retry-with-steps-cdvvg-3565907139
      message: child 'retry-with-steps-cdvvg[0].hello1' errored
      name: retry-with-steps-cdvvg[0]
      phase: Error
      startedAt: "2021-02-25T22:22:27Z"
      templateName: retry-with-steps
      templateScope: local/retry-with-steps-cdvvg
      type: StepGroup
  phase: Failed
  startedAt: "2021-02-25T22:22:27Z"
```

The logs from the controller are what you'd expect them to look like.

---
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment] 2021-02-26 00:38
Will take a look

**Comment by simster7** [comment] 2021-02-26 15:28
This works for me I am not able to reproduce:

<details>
<summary>See my logs:</summary>

```
Name:                retry-with-steps-cdvvg
Namespace:           argo
ServiceAccount:      default
Status:              Succeeded
Conditions:
 PodRunning          False
 Completed           True
Created:             Fri Feb 26 07:24:27 -0800 (47 seconds ago)
Started:             Fri Feb 26 07:24:27 -0800 (47 seconds ago)
Finished:            Fri Feb 26 07:25:14 -0800 (now)
Duration:            47 seconds
Progress:            7/7
ResourcesDuration:   34s*(1 cpu),16s*(100Mi memory)

STEP                       TEMPLATE          PODNAME                            DURATION  MESSAGE
 ✔ retry-with-steps-cdvvg  retry-with-steps
 ├───✔ hello1              random-fail
 │   ├─✖ hello1(0)         random-fail       retry-with-steps-cdvvg-872421055   15s       Error (exit code 1)
 │   ├─✖ hello1(1)         random-fail       retry-with-steps-cdvvg-1476562434  3s        Error (exit code 1)
 │   └─✔ hello1(2)         random-fail       retry-with-steps-cdvvg-1342488577  4s
 └─┬─✔ hello2a             random-fail
   │ ├─✖ hello2a(0)        random-fail       retry-with-steps-cdvvg-3554571188  4s        Error (exit code 1)
   │ ├─✖ hello2a(1)        random-fail       retry-with-steps-cdvvg-2950429809  4s        Error (exit code 1)
   │ └─✔ hello2a(2)        random-fail       retry-with-steps-cdvvg-936968434   4s
   └─✔ hello2b(0)          random-fail       retry-with-steps-cdvvg-916404183   4s

This workflow does not have security context set. You can run your workflow pods more securely by setting it.
Learn more at https://argoproj.github.io/argo-workflows/workflow-pod-security-context/
[256]:argo-workflows 🌵  k get pod retry-with-steps-cdvvg-936968434
NAME                               READY   STATUS      RESTARTS   AGE
retry-with-steps-cdvvg-936968434   0/2     Completed   0          24s
[257]:argo-workflows 🌵  k get pod retry-with-steps-cdvvg-936968434 -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    workflows.argoproj.io/execution: '{"deadline":"2021-02-26T15:29:27Z"}'
    workflows.argoproj.io/node-name: retry-with-steps-cdvvg[1].hello2a(2)
    workflows.argoproj.io/outputs: '{"artifacts":[{"name":"main-logs","s3":{"key":"retry-with-steps-cdvvg/retry-with-steps-cdvvg-936968434/main.log"}}],"exitCode":"0"}'
    workflows.argoproj.io/template: '{"name":"random-fail","inputs":{"parameters":[{"name":"ret","value":"2"}]},"outputs":{},"metadata":{"labels":{"user":"foo"}},"container":{"name":"","image":"python:alpine3.6","command":["python","-c"],"args":["import
      random; import sys; print(''retries: 2''); exit_code = random.choice([0, 0,
      1, 1, 1]); sys.exit(exit_code)"],"resources":{}},"archiveLocation":{"archiveLogs":true,"s3":{"endpoint":"minio:9000","bucket":"my-bucket","insecure":true,"accessKeySecret":{"name":"my-minio-cred","key":"accesskey"},"secretKeySecret":{"name":"my-minio-cred","key":"secretkey"},"key":"retry-with-steps-cdvvg/retry-with-steps-cdvvg-936968434"}},"retryStrategy":{"limit":10},"podSpecPatch":"{\"containers\":[{\"name\":\"main\",
      \"resources\":{\"requests\":{\"cpu\": 2 }}}]}"}'
  creationTimestamp: "2021-02-26T15:25:08Z"
  labels:
    user: foo
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/workflow: retry-with-steps-cdvvg
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:workflows.argoproj.io/execution: {}
          f:workflows.argoproj.io/node-name: {}
          f:workflows.argoproj.io/template: {}
        f:labels:
          .: {}
          f:user: {}
          f:workflows.argoproj.io/completed: {}
          f:workflows.argoproj.io/workflow: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"f0afec2b-8f3a-4bb4-9414-a868e2478f9a"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:activeDeadlineSeconds: {}
        f:containers:
          k:{"name":"main"}:
            .: {}
            f:args: {}
            f:command: {}
            f:env:
              .: {}
              k:{"name":"ARGO_CONTAINER_NAME"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"ARGO_INCLUDE_SCRIPT_OUTPUT"}:
                .: {}
                f:name: {}
                f:value: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources:
              .: {}
              f:requests:
                .: {}
                f:cpu: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
          k:{"name":"wait"}:
            .: {}
            f:command: {}
            f:env:
              .: {}
              k:{"name":"ARGO_CONTAINER_NAME"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"ARGO_CONTAINER_RUNTIME_EXECUTOR"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"ARGO_INCLUDE_SCRIPT_OUTPUT"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"ARGO_POD_NAME"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:fieldRef:
                    .: {}
                    f:apiVersion: {}
                    f:fieldPath: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:securityContext:
              .: {}
              f:capabilities:
                .: {}
                f:add: {}
              f:privileged: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/argo/podmetadata"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/argo/secret/my-minio-cred"}:
                .: {}
                f:mountPath: {}
                f:name: {}
                f:readOnly: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:shareProcessNamespace: {}
        f:terminationGracePeriodSeconds: {}
        f:volumes:
          .: {}
          k:{"name":"my-minio-cred"}:
            .: {}
            f:name: {}
            f:secret:
              .: {}
              f:defaultMode: {}
              f:items: {}
              f:secretName: {}
          k:{"name":"podmetadata"}:
            .: {}
            f:downwardAPI:
              .: {}
              f:defaultMode: {}
              f:items: {}
            f:name: {}
    manager: workflow-controller
    operation: Update
    time: "2021-02-26T15:25:08Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:workflows.argoproj.io/outputs: {}
    manager: argoexec
    operation: Update
    time: "2021-02-26T15:25:12Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.42.0.201"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: k3s
    operation: Update
    time: "2021-02-26T15:25:12Z"
  name: retry-with-steps-cdvvg-936968434
  namespace: argo
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Workflow
    name: retry-with-steps-cdvvg
    uid: f0afec2b-8f3a-4bb4-9414-a868e2478f9a
  resourceVersion: "271792"
  uid: 397cdab9-3ff2-4bd4-a4c2-e7f4a255b6be
spec:
  activeDeadlineSeconds: 258
  containers:
  - command:
    - argoexec
    - wait
    - --loglevel
    - debug
    env:
    - name: ARGO_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: ARGO_CONTAINER_RUNTIME_EXECUTOR
      value: pns
    - name: ARGO_CONTAINER_NAME
      value: wait
    - name: ARGO_INCLUDE_SCRIPT_OUTPUT
      value: "false"
    image: argoproj/argoexec:latest
    imagePullPolicy: IfNotPresent
    name: wait
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE
        - SYS_CHROOT
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /argo/podmetadata
      name: podmetadata
    - mountPath: /argo/secret/my-minio-cred
      name: my-minio-cred
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-rhrl9
      readOnly: true
  - args:
    - 'import random; import sys; print(''retries: 2''); exit_code = random.choice([0,
      0, 1, 1, 1]); sys.exit(exit_code)'
    command:
    - python
    - -c
    env:
    - name: ARGO_CONTAINER_NAME
      value: main
    - name: ARGO_INCLUDE_SCRIPT_OUTPUT
      value: "false"
    image: python:alpine3.6
    imagePullPolicy: IfNotPresent
    name: main
    resources:
      requests:
        cpu: "2"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-rhrl9
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k3d-k3s-default-server-0
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  shareProcessNamespace: true
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations
        path: annotations
    name: podmetadata
  - name: my-minio-cred
    secret:
      defaultMode: 420
      items:
      - key: accesskey
        path: accesskey
      - key: secretkey
        path: secretkey
      secretName: my-minio-cred
  - name: default-token-rhrl9
    secret:
      defaultMode: 420
      secretName: default-token-rhrl9
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-02-26T15:25:08Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-02-26T15:25:08Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-02-26T15:25:08Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-02-26T15:25:08Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://af4dd2e98695d7f1d0f142cc2bc80cf24f081ae3f985e9e15a89c1d0e03f1a42
    image: docker.io/library/python:alpine3.6
    imageID: docker.io/library/python@sha256:766a961bf699491995cc29e20958ef11fd63741ff41dcc70ec34355b39d52971
    lastState: {}
    name: main
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://af4dd2e98695d7f1d0f142cc2bc80cf24f081ae3f985e9e15a89c1d0e03f1a42
        exitCode: 0
        finishedAt: "2021-02-26T15:25:09Z"
        reason: Completed
        startedAt: "2021-02-26T15:25:09Z"
  - containerID: containerd://3c9e6b3c59bad2b0be88d9c4961032d3f16a1dd6cfa9889ce0731e54102dcd11
    image: docker.io/argoproj/argoexec:latest
    imageID: sha256:bcfc2b4e1e16f5f2680062b2e3b7e6a2dbf2cebc1790f3749a57426793765c17
    lastState: {}
    name: wait
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://3c9e6b3c59bad2b0be88d9c4961032d3f16a1dd6cfa9889ce0731e54102dcd11
        exitCode: 0
        finishedAt: "2021-02-26T15:25:12Z"
        reason: Completed
        startedAt: "2021-02-26T15:25:08Z"
  hostIP: 172.18.0.2
  phase: Succeeded
  podIP: 10.42.0.201
  podIPs:
  - ip: 10.42.0.201
  qosClass: Burstable
  startTime: "2021-02-26T15:25:08Z"
[258]:argo-workflows 🌵  k get pod -o yaml retry-with-steps-cdvvg-2950429809
apiVersion: v1
kind: Pod
metadata:
  annotations:
    workflows.argoproj.io/execution: '{"deadline":"2021-02-26T15:29:27Z"}'
    workflows.argoproj.io/node-name: retry-with-steps-cdvvg[1].hello2a(1)
    workflows.argoproj.io/outputs: '{"artifacts":[{"name":"main-logs","s3":{"key":"retry-with-steps-cdvvg/retry-with-steps-cdvvg-2950429809/main.log"}}],"exitCode":"1"}'
    workflows.argoproj.io/template: '{"name":"random-fail","inputs":{"parameters":[{"name":"ret","value":"1"}]},"outputs":{},"metadata":{"labels":{"user":"foo"}},"container":{"name":"","image":"python:alpine3.6","command":["python","-c"],"args":["import
      random; import sys; print(''retries: 1''); exit_code = random.choice([0, 0,
      1, 1, 1]); sys.exit(exit_code)"],"resources":{}},"archiveLocation":{"archiveLogs":true,"s3":{"endpoint":"minio:9000","bucket":"my-bucket","insecure":true,"accessKeySecret":{"name":"my-minio-cred","key":"accesskey"},"secretKeySecret":{"name":"my-minio-cred","key":"secretkey"},"key":"retry-with-steps-cdvvg/retry-with-steps-cdvvg-2950429809"}},"retryStrategy":{"limit":10},"podSpecPatch":"{\"containers\":[{\"name\":\"main\",
      \"resources\":{\"requests\":{\"cpu\": 1 }}}]}"}'
  creationTimestamp: "2021-02-26T15:25:01Z"
  labels:
    user: foo
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/workflow: retry-with-steps-cdvvg
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:workflows.argoproj.io/execution: {}
          f:workflows.argoproj.io/node-name: {}
          f:workflows.argoproj.io/template: {}
        f:labels:
          .: {}
          f:user: {}
          f:workflows.argoproj.io/completed: {}
          f:workflows.argoproj.io/workflow: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"f0afec2b-8f3a-4bb4-9414-a868e2478f9a"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:activeDeadlineSeconds: {}
        f:containers:
          k:{"name":"main"}:
            .: {}
            f:args: {}
            f:command: {}
            f:env:
              .: {}
              k:{"name":"ARGO_CONTAINER_NAME"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"ARGO_INCLUDE_SCRIPT_OUTPUT"}:
                .: {}
                f:name: {}
                f:value: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources:
              .: {}
              f:requests:
                .: {}
                f:cpu: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
          k:{"name":"wait"}:
            .: {}
            f:command: {}
            f:env:
              .: {}
              k:{"name":"ARGO_CONTAINER_NAME"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"ARGO_CONTAINER_RUNTIME_EXECUTOR"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"ARGO_INCLUDE_SCRIPT_OUTPUT"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"ARGO_POD_NAME"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:fieldRef:
                    .: {}
                    f:apiVersion: {}
                    f:fieldPath: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:securityContext:
              .: {}
              f:capabilities:
                .: {}
                f:add: {}
              f:privileged: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/argo/podmetadata"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/argo/secret/my-minio-cred"}:
                .: {}
                f:mountPath: {}
                f:name: {}
                f:readOnly: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:shareProcessNamespace: {}
        f:terminationGracePeriodSeconds: {}
        f:volumes:
          .: {}
          k:{"name":"my-minio-cred"}:
            .: {}
            f:name: {}
            f:secret:
              .: {}
              f:defaultMode: {}
              f:items: {}
              f:secretName: {}
          k:{"name":"podmetadata"}:
            .: {}
            f:downwardAPI:
              .: {}
              f:defaultMode: {}
              f:items: {}
            f:name: {}
    manager: workflow-controller
    operation: Update
    time: "2021-02-26T15:25:01Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.42.0.200"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: k3s
    operation: Update
    time: "2021-02-26T15:25:03Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:workflows.argoproj.io/outputs: {}
    manager: argoexec
    operation: Update
    time: "2021-02-26T15:25:05Z"
  name: retry-with-steps-cdvvg-2950429809
  namespace: argo
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Workflow
    name: retry-with-steps-cdvvg
    uid: f0afec2b-8f3a-4bb4-9414-a868e2478f9a
  resourceVersion: "271770"
  uid: 8b7379e1-caa6-4a88-8aad-dc92ecb56135
spec:
  activeDeadlineSeconds: 265
  containers:
  - command:
    - argoexec
    - wait
    - --loglevel
    - debug
    env:
    - name: ARGO_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: ARGO_CONTAINER_RUNTIME_EXECUTOR
      value: pns
    - name: ARGO_CONTAINER_NAME
      value: wait
    - name: ARGO_INCLUDE_SCRIPT_OUTPUT
      value: "false"
    image: argoproj/argoexec:latest
    imagePullPolicy: IfNotPresent
    name: wait
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE
        - SYS_CHROOT
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /argo/podmetadata
      name: podmetadata
    - mountPath: /argo/secret/my-minio-cred
      name: my-minio-cred
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-rhrl9
      readOnly: true
  - args:
    - 'import random; import sys; print(''retries: 1''); exit_code = random.choice([0,
      0, 1, 1, 1]); sys.exit(exit_code)'
    command:
    - python
    - -c
    env:
    - name: ARGO_CONTAINER_NAME
      value: main
    - name: ARGO_INCLUDE_SCRIPT_OUTPUT
      value: "false"
    image: python:alpine3.6
    imagePullPolicy: IfNotPresent
    name: main
    resources:
      requests:
        cpu: "1"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-rhrl9
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k3d-k3s-default-server-0
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  shareProcessNamespace: true
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations
        path: annotations
    name: podmetadata
  - name: my-minio-cred
    secret:
      defaultMode: 420
      items:
      - key: accesskey
        path: accesskey
      - key: secretkey
        path: secretkey
      secretName: my-minio-cred
  - name: default-token-rhrl9
    secret:
      defaultMode: 420
      secretName: default-token-rhrl9
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-02-26T15:25:01Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-02-26T15:25:01Z"
    message: 'containers with unready status: [wait main]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-02-26T15:25:01Z"
    message: 'containers with unready status: [wait main]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-02-26T15:25:01Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://f7c91527b3b74c0295c668caf137662d57104cf1ac55e0c25b3eb39f444536e0
    image: docker.io/library/python:alpine3.6
    imageID: docker.io/library/python@sha256:766a961bf699491995cc29e20958ef11fd63741ff41dcc70ec34355b39d52971
    lastState: {}
    name: main
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://f7c91527b3b74c0295c668caf137662d57104cf1ac55e0c25b3eb39f444536e0
        exitCode: 1
        finishedAt: "2021-02-26T15:25:02Z"
        reason: Error
        startedAt: "2021-02-26T15:25:02Z"
  - containerID: containerd://62936dfb7895869056b6fbbea250032f8359fb324b49fb231854298645cdc93e
    image: docker.io/argoproj/argoexec:latest
    imageID: sha256:bcfc2b4e1e16f5f2680062b2e3b7e6a2dbf2cebc1790f3749a57426793765c17
    lastState: {}
    name: wait
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://62936dfb7895869056b6fbbea250032f8359fb324b49fb231854298645cdc93e
        exitCode: 0
        finishedAt: "2021-02-26T15:25:05Z"
        reason: Completed
        startedAt: "2021-02-26T15:25:02Z"
  hostIP: 172.18.0.2
  phase: Failed
  podIP: 10.42.0.200
  podIPs:
  - ip: 10.42.0.200
  qosClass: Burstable
  startTime: "2021-02-26T15:25:01Z"
```

</details>

> 2.10.2

Upgrade to latest `v2.12.9` and try again?

**Comment by therc** [comment] 2021-02-26 15:56
Thank you! I had skimmed through the changelogs, but I hadn't seen anything relevant. I'll try upgrading.

**Comment by therc** [comment] 2021-02-26 17:11
You're right, at some point it got fixed. The next step is still broken, though. Any expression other than {{retries}} seems to result in errors:

`{"cpu": {{retries}} + 0.1 }`: `Invalid PodSpecPatch String`
`{"cpu": ({{retries}} + 0.1) }`: `Invalid PodSpecPatch String`
`{"cpu": ({{retries}}) }`: `Invalid PodSpecPatch String`

Should retries be an int? Would that change break any workflows?

**Comment by simster7** [comment] 2021-02-26 18:37
Those are currently not supported, but support is coming soon. See #5115

**Comment by simster7** [comment] 2021-02-26 18:37
Closing this

**Closed by simster7** 2021-02-26 18:37 UTC
