### ISSUE TITLE
onStart handler for DAGTask/Step 

### ISSUE THREAD

**Issue by bklaubos** [argoproj/argo-workflows#5505] opened 2021-03-24 18:44 UTC
# Summary

What change needs making?
We  currently have `onExit` handler for DAG Task/workflowStep
(
see example:https://argoproj.github.io/argo-workflows/fields/#dagtask
https://argoproj.github.io/argo-workflows/fields/#workflowstep
)
We need to add `onStart` handler  to allow custom code to be executed before the `Main` container entrypoint formally started.
# Use Cases
- I want to be able to  do some pre-processing of "initialization" data before formally starting up the pod.

When would you use this?
For Machine Learning to do custom deserialization of data from AWS S3/FSx

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment] 2021-03-24 19:33
Why not just add a step before your `main` container?

**Comment by simster7** [comment] 2021-03-24 19:33
Duplicate of https://github.com/argoproj/argo-workflows/issues/3428

**Comment by bklaubos** [comment] 2021-03-24 21:00
We don't want to add additional steps as our workflow  has 1000-2000 steps.
Doing that would mean 2 x extra allocation resources and time.

**Closed** 2022-02-07 17:42 UTC
Labels: solution/workaround
