### ISSUE TITLE
GUI: provide 'select all' and 'deselect all' options in filters

### ISSUE THREAD

**Issue by Sebast1aan** [argoproj/argo-workflows#11950] opened 2023-10-05 14:23 UTC
# Summary

In the Event Flow tab I wanted to only display 'webhooks'. Now it looks like I have to deselect all other types. Instead, it would be useful if a 'select all' and 'deselect all' option are provided.

The 'filter' option is probably present in some other places as well in the GUI, seems useful to add it in general.

Screenshot for reference:
![image](https://github.com/argoproj/argo-workflows/assets/22411346/0844681e-d8b0-4767-9b66-1e31032139fd)

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by Sebast1aan** [comment] 2023-10-06 07:59
I have no experience with TypeScript, but if I understand #11132 correctly, the 'Check All' box is available for all graphs (and thus also for the one on the Event Flows page) from 3.5 onward? I currently don't have a development machine available and codespaces doesn't work according to the docs, so not sure how I can efficiently contribute to the code...

**Comment by agilgur5** [comment] 2023-10-06 14:04
> I have no experience with TypeScript, but if I understand #11132 correctly, the 'Check All' box is available for all graphs (and thus also for the one on the Event Flows page) from 3.5 onward?

Oh I think you're right actually! I had only taken a glance before, but that does indeed seem to be for all graphs. Nice read despite not knowing TS! 😄

So yes it seems like it should be available for Event Flows in 3.5 as well.
We can close this as a duplicate of #11129 then

**Closed by agilgur5** 2023-10-06 14:04 UTC
Labels: area/ui, solution/duplicate

**Comment by agilgur5** [comment] 2023-10-13 03:20
For reference (and confirmation), you can see the "Check All" box on the Event Flows page in [this GIF from a PR](https://github.com/argoproj/argo-workflows/pull/11901#pullrequestreview-1651739876)
