### ISSUE TITLE
The startup time of the init container is later than that of the application container.

### ISSUE THREAD

**Issue by wiscloud** [argoproj/argo-workflows#13222] opened 2024-06-20 06:44 UTC
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

When the argo task is executed, The startup time of the init container is later than that of the application container.

In the output of the kubectl describe pod xxx command, the value of startedAt for the init container is later than that for the application container.
The init container starts to run the application container after the running of the init container is complete. However, the application container runs first. The init container runs during the running of the application container.
When the two containers run at the same time, the argoexec file is operated. As a result, the `open /var/run/argo/argoexec: text file busy` exception occurs.

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/default-container: main
    kubernetes.io/psp: psp-global
    workflows.argoproj.io/node-id: vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99-333335174
    workflows.argoproj.io/node-name: vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99.coverage(1:cov-type:coverage_report,version:0.2.5)
  creationTimestamp: "2024-06-19T19:44:39Z"
  labels:
    fuzz-worker: "true"
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/workflow: vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99
  name: vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99-333335174
  namespace: argo
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Workflow
    name: vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99
    uid: 2e182e9c-f249-44cf-911a-b3c10310e451
  resourceVersion: "544998173"
  selfLink: /api/v1/namespaces/argo/pods/vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99-333335174
  uid: 9b7ba2d3-65f7-4e3f-8621-538d1cfb256f
spec:
  activeDeadlineSeconds: 259200
  containers:
  - command:
    - argoexec
    - wait
    - --loglevel
    - info
    env:
    - name: ARGO_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: ARGO_POD_UID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.uid
    - name: ARGO_CONTAINER_RUNTIME_EXECUTOR
      value: emissary
    - name: GODEBUG
      value: x509ignoreCN=0
    - name: ARGO_WORKFLOW_NAME
      value: vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99
    - name: ARGO_CONTAINER_NAME
      value: wait
    - name: ARGO_TEMPLATE
      value: '....'
    - name: ARGO_NODE_ID
      value: vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99-333335174
    - name: ARGO_INCLUDE_SCRIPT_OUTPUT
      value: "false"
    - name: ARGO_DEADLINE
      value: "0001-01-01T00:00:00Z"
    - name: ARGO_PROGRESS_FILE
      value: /var/run/argo/progress
    - name: ARGO_PROGRESS_PATCH_TICK_DURATION
      value: 1m0s
    - name: ARGO_PROGRESS_FILE_TICK_DURATION
      value: 3s
    image: ../argoexec:v3.3.8
    imagePullPolicy: IfNotPresent
    name: wait
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /argo/secret/my-minio-cred
      name: my-minio-cred
      readOnly: true
    - mountPath: /var/run/argo
      name: var-run-argo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-6htk6
      readOnly: true
  - args:
    - 'python3 entry_point.py; sh run.sh '
    command:
    - /var/run/argo/argoexec
    - emissary
    - --
    - sh
    - -c
    env:
    - name: TENANT_ID
      value: "1009"
    - name: DEBUG_COV
      value: "false"
    - name: GIT_SSL_NO_VERIFY
      value: "1"
    - name: GIT_BRANCH
      value: master
    - name: FUZZ_CONFIG
      value: '...'
    - name: COVERAGE_ARGS
      value: -C 10000000 -T 3600 -r reportPath -c corpusPath
    - name: PROJECT_NAME
      value: VOS_CortexM
    - name: JOB_NAME
      value: VOS_CortexM
    - name: S3_DIR
      value: SECTRACY/261035810/VOS_CortexM/vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99/
    - name: S3_REPORT_DIR
      value: SECTRACY-REPORT/261035810/VOS_CortexM/0.2.5/vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99/
    - name: VERSION
      value: 0.2.5
    - name: COV_TYPE
      value: coverage_report
    - name: WORKFLOW_ID
      value: 3763805e-581a-4070-96e9-8c8ff7b74058
    - name: BRANCH
      value: master
    - name: COVERAGE_URL
      value: ..
    - name: FUZZTYPE
      value: DTFUZZ
    - name: SERVICE_AREA
      value: yellow
    - name: SERVICE_ENVIR
      value: pro
    - name: PROJECT_PBI
      value: "261035810"
    - name: ARGO_CONTAINER_NAME
      value: main
    - name: ARGO_TEMPLATE
      value: '...'
    - name: ARGO_NODE_ID
      value: vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99-333335174
    - name: ARGO_INCLUDE_SCRIPT_OUTPUT
      value: "false"
    - name: ARGO_DEADLINE
      value: "0001-01-01T00:00:00Z"
    - name: ARGO_PROGRESS_FILE
      value: /var/run/argo/progress
    - name: ARGO_PROGRESS_PATCH_TICK_DURATION
      value: 1m0s
    - name: ARGO_PROGRESS_FILE_TICK_DURATION
      value: 3s
    image: ..
    imagePullPolicy: IfNotPresent
    name: main
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/argo
      name: var-run-argo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-6htk6
      readOnly: true
    workingDir: /Sectracy
  dnsConfig:
    options:
    - name: single-request-reopen
      value: ""
    - name: timeout
      value: "2"
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: regcred
  - name: default-secret
  initContainers:
  - command:
    - argoexec
    - init
    - --loglevel
    - info
    env:
    - name: ARGO_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: ARGO_POD_UID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.uid
    - name: ARGO_CONTAINER_RUNTIME_EXECUTOR
      value: emissary
    - name: GODEBUG
      value: x509ignoreCN=0
    - name: ARGO_WORKFLOW_NAME
      value: vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99
    - name: ARGO_CONTAINER_NAME
      value: init
    - name: ARGO_TEMPLATE
      value: '...'
    - name: ARGO_NODE_ID
      value: vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99-333335174
    - name: ARGO_INCLUDE_SCRIPT_OUTPUT
      value: "false"
    - name: ARGO_DEADLINE
      value: "0001-01-01T00:00:00Z"
    - name: ARGO_PROGRESS_FILE
      value: /var/run/argo/progress
    - name: ARGO_PROGRESS_PATCH_TICK_DURATION
      value: 1m0s
    - name: ARGO_PROGRESS_FILE_TICK_DURATION
      value: 3s
    image: ../argoexec:v3.3.8
    imagePullPolicy: IfNotPresent
    name: init
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /argo/secret/my-minio-cred
      name: my-minio-cred
      readOnly: true
    - mountPath: /var/run/argo
      name: var-run-argo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-6htk6
      readOnly: true
  nodeName: 7.218.69.27
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: var-run-argo
  - name: my-minio-cred
    secret:
      defaultMode: 420
      items:
      - key: accesskey
        path: accesskey
      - key: secretkey
        path: secretkey
      secretName: my-minio-cred
  - name: default-token-6htk6
    secret:
      defaultMode: 420
      secretName: default-token-6htk6
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-06-19T21:43:38Z"
    message: 'containers with incomplete status: [init]'
    reason: ContainersNotInitialized
    status: "False"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-06-19T21:43:39Z"
    message: 'containers with unready status: [wait main]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-06-19T21:43:39Z"
    message: 'containers with unready status: [wait main]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-06-19T19:44:39Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://9208031ef8307e4d1561020ae84cfb867ea435bac4fffde09aa2efd33c05531c
    image: ..
    imageID: ..
    lastState: {}
    name: main
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://9208031ef8307e4d1561020ae84cfb867ea435bac4fffde09aa2efd33c05531c
        exitCode: 137
        finishedAt: "2024-06-19T21:43:38Z"
        reason: Error
        startedAt: "2024-06-19T21:43:36Z"
  - containerID: docker://5d1d650c0225e09a0077768cd0bba2b24458de5495e88e4db5793aa488fbd20e
    image: ../argoexec:v3.3.8
    imageID: ..
    lastState: {}
    name: wait
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://5d1d650c0225e09a0077768cd0bba2b24458de5495e88e4db5793aa488fbd20e
        exitCode: 0
        finishedAt: "2024-06-19T21:43:38Z"
        message: Step terminated
        reason: Completed
        startedAt: "2024-06-19T19:44:41Z"
  hostIP: 7.218.69.27
  initContainerStatuses:
  - containerID: docker://d9ab7d5ec93b06c04f2970ce2b30f672298069ed3098176683a654f487f28072
    image: ../argoexec:v3.3.8
    imageID: ..
    lastState: {}
    name: init
    ready: false
    restartCount: 0
    state:
      terminated:
        containerID: docker://d9ab7d5ec93b06c04f2970ce2b30f672298069ed3098176683a654f487f28072
        exitCode: 1
        finishedAt: "2024-06-19T21:43:37Z"
        message: 'open /var/run/argo/argoexec: text file busy'
        reason: Error
        startedAt: "2024-06-19T21:43:37Z"
  phase: Failed
  podIP: 12.11.1.191
  podIPs:
  - ip: 12.11.1.191
  qosClass: Burstable
  startTime: "2024-06-19T19:44:39Z"

```

### Version

v3.3.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
I don't know how to reproduce it, Same here. Sometimes it shows up, sometimes it doesn't.I can only provide a pod yaml template for running. The running image and workflow are private.
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

I am very sorry, because the production environment has a lot of logs, and the useful information that can be provided is limited. The following is part of the log of the workflow where the error occurs.


kubectl logs -n argo deploy/workflow-controller | grep vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99-333335174 
time="2024-06-19T19:44:39.079Z" level=info msg="Pod node vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99-333335174 initialized Pending" namespace=argo workflow=vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99
time="2024-06-19T19:44:39.107Z" level=info msg="Created pod: vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99.coverage(1:cov-type:coverage_report,version:0.2.5) (vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99-333335174)" namespace=argo workflow=vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99
time="2024-06-19T19:45:09.081Z" level=info msg="node changed" new.message=PodInitializing new.phase=Pending new.progress=0/1 nodeID=vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99-333335174 old.message= old.phase=Pending old.progress=0/1
time="2024-06-19T20:05:09.083Z" level=info msg="node unchanged" nodeID=vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99-333335174
time="2024-06-19T20:25:09.084Z" level=info msg="node unchanged" nodeID=vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99-333335174
time="2024-06-19T20:45:09.086Z" level=info msg="node unchanged" nodeID=vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99-333335174
time="2024-06-19T21:05:09.087Z" level=info msg="node unchanged" nodeID=vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99-333335174
time="2024-06-19T21:25:09.088Z" level=info msg="node unchanged" nodeID=vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99-333335174
time="2024-06-19T21:44:07.247Z" level=info msg="task-result changed" namespace=argo nodeID=vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99-333335174 workflow=vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99
time="2024-06-19T21:44:07.247Z" level=info msg="node changed" new.message="Error (exit code 1): open /var/run/argo/argoexec: text file busy" new.phase=Error new.progress=0/1 nodeID=vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99-333335174 old.message=PodInitializing old.phase=Pending old.progress=0/1
time="2024-06-19T21:44:07.248Z" level=info msg="Outbound nodes of vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99 set to [vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99-1856301460 vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99-333335174]" namespace=argo workflow=vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99
time="2024-06-19T21:44:07.294Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/vos-ee-erika3-dc5d779f1c7c42beba46e7b7909fbb99-333335174/labelPodCompleted
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

No resources found in argo namespace.
```

**Comment by jswxstw** [comment] 2024-06-20 08:27
The main container will not run before the init container completes.I think I think you might have encountered the following situation: 
1. init container was deleted because of diedContainer GC
2. pod re-entered the init state and rebuilt the init container

Please check your kubelet config to see if there is a config named `--maximum-dead-containers`.

**Comment by wiscloud** [comment] 2024-06-20 10:29
> The main container will not run before the init container completes.I think you might have encountered the following situation:
> 
> 1. init container was deleted because of dead containers GC
> 2. pod re-entered the init state and rebuilt the init container
> 
> Please check your kubelet config to see if there is a config named `--maximum-dead-containers`.

Could it be related to this parameter? I have not manually set the value of this parameter. The default value is used.

**Comment by wiscloud** [comment] 2024-06-20 11:24
> > Could it be related to this parameter? I have not manually set the value of this parameter. The default value is used.
> 
> Yes, if the number of running pods which contain init container exceeds this value, it will trigger this issue. You can try to increase it according to the number of running pods, or just unset it, or set it to -1.

I haven't set the value of kubelet's --maximum-dead-containers parameter, which defaults to -1.

**Comment by jswxstw** [comment] 2024-06-20 11:46
> I haven't set the value of kubelet's --maximum-dead-containers parameter, which defaults to -1.

🤔That's so weird. This init container appears to have been rebuilt.
init container startedAt: "2024-06-19T21:43:37Z"
main container startedAt: "2024-06-19T21:43:36Z" 
wait container startedAt: "2024-06-19T19:44:41Z" (same as pod create time)

**Comment by Joibel** [comment] 2024-06-20 12:09
This is an old and unsupported version of argo-workflows. You've ticked the box saying you've reproduced it on latest or explained in detail why not, but then not given that detail - although I guess "It's production" is the reason.

Do you have any evidence from **outside** of workflows that the init container is restarting? My guess would be that workflows is somehow getting confused (confusing two pods with one another) or somehow otherwise lying about this.

**Comment by wiscloud** [comment] 2024-06-20 12:11
> > I haven't set the value of kubelet's --maximum-dead-containers parameter, which defaults to -1.
> 
> 🤔That's so weird. This init container appears to have been rebuilt. init container startedAt: "2024-06-19T21:43:37Z" main container startedAt: "2024-06-19T21:43:36Z" wait container startedAt: "2024-06-19T19:44:41Z" (same as pod create time)
> 
> `maximum-dead-containers` and `maximum-dead-containers-per-container` is DEPRECATED now... Does the node has a high disk usage? reached the image gc threshold?

All resources are sufficient

**Comment by jswxstw** [comment] 2024-06-20 12:20
> All resources are sufficient

From the observation, it appears that the init container has been rebuilt. However, I can't think of any other reasons that could cause this issue.🐻🤷
My suggestion is to upgrade the argo version and thoroughly check the kubelet configuration.

**Comment by agilgur5** [comment] 2024-06-20 14:46
> This is an old and unsupported version of argo-workflows. You've ticked the box saying you've reproduced it on latest or explained in detail why not, but then not given that detail

Yes, please fill out the template accurately, as it asks.
As this is an unsupported version, there's nothing Argo can do about it anyway.

But the issue does also seem pretty clearly out of scope of Argo -- `initContainers` starting before `containers` is defined by k8s, not Argo. If you have a problem with that, your problem would be with k8s, not Argo. Argo can't fix a k8s issue for you

**Closed by agilgur5** 2024-06-20 14:46 UTC
Labels: type/bug, area/executor, problem/more information needed, area/upstream, solution/outdated

**Comment by agilgur5** [comment] 2024-06-20 14:56
> If you have a problem with that, your problem would be with k8s, not Argo. Argo can't fix a k8s issue for you
> 
> Given your unsupported version of Argo, I would also check if you're running a supported version of k8s across all its components

Seems like OP did file an issue upstream in https://github.com/kubernetes/kubernetes/issues/125602 and there are similarly many other unsupported and outdated versions there.

Please update your cluster to supported versions and then, if you still have an issue, follow issue templates to post those.

**Comment by wiscloud** [comment] 2024-06-21 10:24
In Kubernetes 1.19, the init container is deleted during the execution of the application container. Then, the pod recreates the init container and executes it. At this time, the main container and the init container compete for argoexec. it leads to mistakes.

Although this is the reason, there is still a little doubt. Does the init container provided by argo-workflow modify the content of argoexec during execution? After all, `text file busy` error generally means that an executable file was modified during execution.
