### ISSUE TITLE
Support for multiple semaphores

### ISSUE THREAD

**Issue by uday-mandava** [argoproj/argo-workflows#13181] opened 2024-06-13 22:10 UTC
# Summary
Argo workflow has semaphores feature https://argo-workflows.readthedocs.io/en/latest/synchronization/
Allows only one currently, need support of multiple semaphores
What change needs making?
Support multiple semaphores

## Use Cases

We are using this feature to limit the parallelism. Sometimes we need to limit parallelism at different levels, for example limit at the workflow level, and limit at the group of workflows level. 
When would you use this?
For limiting workflows and to fairly distribute namespace resources
---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment] 2024-06-14 00:36
Duplicate of #5022

**Closed by agilgur5** 2024-06-14 00:36 UTC
Labels: type/feature
