### ISSUE TITLE
argo lint local mode

### ISSUE THREAD

**Issue by brabster** [argoproj/argo-workflows#3729] opened 2020-08-11 10:09 UTC
# Summary

A means of specifying whether to fail validation for features that are not available locally, like
```
FATA[0000] cannot validate Workflow: templates.workflow.tasks.foo template reference RELEASE-NAME-templates.foo not found
```

# Use Cases

Validating templates locally. Tested with 2.9.4

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment] 2020-08-11 13:59
There's the [`runtimeResolution`](https://github.com/argoproj/argo/blob/master/docs/fields.md#templateref) flag in the `templateRef` field for this

**Comment by alexec** [comment] 2020-08-11 16:17
Simon has suggested one `runtimeResolution`. You can run the CLI in server mode with `ARGO_SERVER` if you are running Argo Server. I actually think this issue in a duplicate of #3209 .

**Closed** 2020-08-11 18:46 UTC
Labels: area/cli, solution/duplicate
