### ISSUE TITLE
3.4.8 Workflows and Archived Workflows on the UI are sometimes empty (confirm that there is data)

### ISSUE THREAD

**Issue by Zhangdong3915** [argoproj/argo-workflows#13287] opened 2024-07-01 10:01 UTC
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

我这边针对同一个url：https://ali-app.argo.neuralgalaxy.cn/archived-workflows?phase=Failed&minStartedAt=2024-05-31T16%3A00%3A00.000Z&maxStartedAt=2024-07-01T16%3A00%3A00.000Z
多次刷新可能出现不同的返回结果
![image](https://github.com/argoproj/argo-workflows/assets/156639184/0fd008f7-c0cb-4666-a3c5-c230de7991c0)
![image](https://github.com/argoproj/argo-workflows/assets/156639184/2d9a91c0-4f68-4418-9f0b-465e4c7d0cb6)

### Version

3.4.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
It will appear when multiple requests are made. I don’t know if it is a bug in this version.
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

time="2024-07-01T09:51:03.120Z" level=info msg="Get leases 200"
time="2024-07-01T09:51:11.601Z" level=info msg="Get leases 200"
time="2024-07-01T09:51:16.465Z" level=info msg="List workflows 200"
time="2024-07-01T09:51:19.707Z" level=info msg="Get leases 200"
time="2024-07-01T09:51:30.112Z" level=info msg="Get leases 200"
time="2024-07-01T09:51:36.701Z" level=info msg="Get leases 200"
time="2024-07-01T09:51:44.394Z" level=info msg="Get leases 200"
time="2024-07-01T09:51:51.270Z" level=info msg="Get leases 200"
time="2024-07-01T09:51:56.707Z" level=info msg="Get leases 200"
time="2024-07-01T09:52:03.377Z" level=info msg="Get leases 200"
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded


aaa
```

**Comment by agilgur5** [comment] 2024-07-01 15:18
The issue template specifically asks to test with `:latest`. You checked the box but did not seem to do that. Please follow the issue template accurately.

Closing this issue until a reproduction on `:latest` or at least `3.4.18` can be provided.

**Closed by agilgur5** 2024-07-01 15:18 UTC
Labels: type/bug, solution/outdated

**Comment by Zhangdong3915** [comment] 2024-07-02 01:19
![image](https://github.com/argoproj/argo-workflows/assets/156639184/03e9eac0-a5e3-4837-8d6c-185a5f1b5547)
我使用了quay.io/argoproj/workflow-controller:latest 进行测试，还是会出现这个问题

**Comment by Zhangdong3915** [comment] 2024-07-02 01:22
> > 不知道是不是这个版本的bug。
> 
> 问题模板特别要求使用 进行测试`:latest`。您勾选了复选框但似乎并未执行此操作。请准确遵循问题模板。
> 
> 3.4.8 已经过时了。关闭此问题，直到`:latest`可以提供 3.4.18 或至少 3.4.18 的复制版本。

3.4.18会解决这个问题吗

**Comment by Zhangdong3915** [comment] 2024-07-02 01:31
@agilgur5 Will 3.4.18 fix this issue?

**Comment by agilgur5** [comment] 2024-07-02 03:48
> 我使用了quay.io/argoproj/workflow-controller:latest 进行测试，还是会出现这个问题

Your issue is with the Server, not the Controller. If you can reproduce with the Server on `:latest`, we can reopen.
In that case, would definitely need more details as to when this occurs, since I can't reproduce this myself on `:latest`.

> @agilgur5 Will 3.4.18 fix this issue?

`:latest` has more bugfixes if you can try that. I said 3.4.18 in case you couldn't try `:latest` as that's the newest patch release of 3.4

**Comment by Zhangdong3915** [comment] 2024-07-02 06:19
@agilgur5  The latest 3.4 version is only 3.4.17. I tried version 3.4.17 and this problem has not occurred for the time being. In which specific version was this problem fixed?

**Comment by agilgur5** [comment] 2024-07-02 06:27
> The latest 3.4 version is only 3.4.17. 

Oh you're right, sorry about that.

> In which specific version was this problem fixed?

You're ~10 versions behind, so it's pretty hard to tell. I don't know off the top of my head, would need to search the CHANGELOG for Server/API fixes for the list workflows endpoint

**Comment by Zhangdong3915** [comment] 2024-07-02 07:02
https://github.com/argoproj/argo-workflows/pull/12172
https://github.com/argoproj/argo-workflows/pull/11792    

Are these two？

**Comment by agilgur5** [comment] 2024-07-02 07:13
> #12172

That one only affects if you're using `BASE_HREF`, which you aren't based on your screenshots. You'd also get an error.

> #11792

That doesn't affect archived workflows, only unarchived workflows. It also works the same way consistently; you wouldn't have gotten different results with the same query due to the bug.

**Comment by Zhangdong3915** [comment] 2024-07-02 07:20
ok，thank you.
