### ISSUE TITLE
Publish Argo UI TypeScript Models Independently

### ISSUE THREAD

**Issue by divideby0** [argoproj/argo-workflows#10016] opened 2022-11-11 16:32 UTC
# Summary

My teams often develop and interact with Argo Workflows from Node.js backends using TypeScript. In the past, we've had to manually build and maintain our TypeScript bindings to ensure they match the structure of Argo CRDs. This may often involve a lot of duplicated effort and risk of drift as the Argo models evolve.

We noticed that the Argo UI has well-defined TypeScript interfaces for many key objects such as WorkflowSpec, Status, etc:

https://github.com/argoproj/argo-workflows/blob/7d9319b60d0bc417b25d35968c1619e51c13b7ec/ui/src/models/workflows.ts

These types allow the Argo UI front-end code to safely read and manage resources using the Argo REST API. However, these interfaces are packaged alongside front-end concerns and dependencies (e.g. React). This makes it more difficult to re-use these models without introducing unnecessary (and often incompatible) transitive dependencies.

There may be an opportunity to bundle these interfaces separately as a [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)-style `.d.ts` package. Then the Argo UI package could consume those types alongside other first-party and third-party projects.

# Use Cases

Provide type safety for backend and frontend developers when they create and interact with Argo Workflow CRDs from TypeScript.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by aarushisoni** [comment] 2022-11-14 13:52
Hi! I want to contribute to this issue .

**Comment by alexec** [comment] 2022-11-16 15:33
You could add a new Typscript SDK like the Java or Python ones. They use the OpenAPI generator.

**Comment by joebowbeer** [comment] 2023-05-15 05:30
See #3309

**Comment by agilgur5** [comment] 2023-10-27 23:28
Duplicate of #3309

**Closed by agilgur5** 2023-10-27 23:28 UTC
Labels: enhancement, area/sdks, area/ui
