### ISSUE TITLE
Allow parameter input also in CronWorkflow UI

### ISSUE THREAD

**Issue by panicboat** [argoproj/argo-workflows#13985] opened 2024-12-11 00:56 UTC
# Summary

Workflows that are normally executed on a regular basis may need to be manually executed by changing parameters when something goes wrong. Most CronWorkflows only require periodic execution, but there are rare cases where it is necessary to change parameters, in which case a flow to add manifests is required, but this is also difficult to anticipate in advance.
Therefore, I would like CronWorkflow to have a UI for specifying parameters like WorkflowTemplate.

## Use Cases

Normally, the dryrun option is set to Off, verbose logs are not output, etc.
We may want to set these options to investigate a failure of a recurring run.

We may also want to run a recurring workflow only once, with parameters changed, as a separate project task.

---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by tooptoop4** [comment] 2024-12-12 04:56
dupe of https://github.com/argoproj/argo-workflows/issues/11026

**Comment by Joibel** [comment] 2024-12-23 09:55
Closing as duplicate

**Closed by Joibel** 2024-12-23 09:55 UTC
