### ISSUE TITLE
3.5 Workflow List UI pagination not enabled for archived workflows when few live workflows

### ISSUE THREAD

**Issue by panicboat** [argoproj/argo-workflows#12647] opened 2024-02-09 10:08 UTC
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

This occurs when the number of workflow custom resource objects is less than the results per page in the Workflow UI.
The archived workflow does not appear to be paged.

### Version

v3.5.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Not related to workflows
```

### Logs from the workflow controller

```text
Not related to workflows
```

### Logs from in your workflow's wait container

```text
Not related to workflows
```

**Comment by agilgur5** [comment] 2024-02-18 16:40
I believe this might be a duplicate of #11715. Since the pagination `limit` is applied to both the Live and Archived Workflows, it is possible for it to overfetch and have up to twice as many (`limit` of both). The UI does not expect that so that may cause buggy behavior

**Closed** 2024-02-18 16:40 UTC
Labels: bug, regression, area/api, area/ui, area/workflow-archive, P2, duplicate
