### ISSUE TITLE
argo : automatic labelling of workflows based on arguments

### ISSUE THREAD

**Issue by christopheblin** [argoproj/argo-workflows#6113] opened 2021-06-09 15:48 UTC
Based on https://github.com/argoproj/argo-workflows/discussions/6096

Basically, I have a workflow template that is launched 100+ times a day, each time with different arguments

it is either launched from the ui by a end user (who specifies the parameters manually, basically the name of a subdirectory) or by a cron (when launched from the cron, the cron use a generate step to launch the wftpl for all subdirectories)

basically, my argo-ui is fulled with the "same" rows dataset-xxxxx

<img width="1676" alt="Capture d’écran 2021-06-04 à 15 01 44" src="https://user-images.githubusercontent.com/11044877/120805580-3e632680-c546-11eb-87a1-20b19641fd86.png">

I'd like to know if it is possible to use arguments to label the workflows, or if it would be possible to see the arguments directly on the row (not only in the workflows, but also in the archived workflows) ?

Also, I'd like searching by the arguments (like "find the dataset for directory X"). Here again, I'd need that in workflows AND in archived workflows

I know that the user and the cron can add the labels, but this is "risky" when it is the end-user (he has to repeat the arguments names and values in the labels every time he submits a workflow template and some chars are forbidden in a label whereas they are possible in an argument...)

also, we cannot see the labels directly on the row

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by christopheblin** [comment] 2021-06-09 15:49
also note that using arguments to generate the name would be A.W.E.S.O.M.E

**Comment by alexec** [comment] 2021-06-09 16:06
When you submit a workflow, you can choose the name for it. Would that work?

**Comment by christopheblin** [comment] 2021-06-10 06:31
@alexec 

I see 2 problems
1. like for labels, when it is the end-user that submits, it is "risky" (typo, forget, ...)
2. not searchable (neither in workflows nor in the archives)

somehow, inside a WorflowTemplate, I'd like to set 

```
metadata:
  labels:
    - name: the_directory
    - value: {{workflow.arguments.the_directory}} #here, argo should sanitize
```

eventually, if it is also supported in generateName, that would be great too

Otherwise, something "magical" inside the controller (for labels)

Otherwise, maybe doing the filter directly in the UI is possible...

Note : I thought that arguments were available  directly on the list level, but I see this is not the case when I open chrome devtools (however, the arguments are correctly saved in the archive db and are inside the k8s resources, so it somehow filtered by argo-server I think) 

How do other people do to find their manually submitted workflows ? are they truly placing labels manually ? or is it somehow an unusual thing on my side ?

**Comment by christopheblin** [comment] 2021-06-11 06:02
ok, i've found a (ugly) workaround to cope with that situation

be prepared, it's really ugly :)

```
metadata:
  name: hello  
spec:
  entrypoint: hello-launcher
  arguments:
    parameters:
      - name: the_message
        value: xxx
  templates:
    - name: hello-main
      inputs:
        parameters:
          - name: the_message
      steps:
        - - name: hello
            arguments:
              parameters:
                - name: message
                  value: test
            templateRef: #this is just a template stored elsewhere like cowsay
              name: lib
              template: echo
    - name: hello-launcher
      inputs:
        parameters:
          - name: the_message
      outputs: #these are not required, they just make easy to find the sub-workflow later
        parameters:
          - name: name
            valueFrom:
              jsonPath: '{.metadata.name}'
          - name: namespace
            valueFrom:
              jsonPath: '{.metadata.namespace}'
          - name: uid
            valueFrom:
              jsonPath: '{.metadata.uid}'
      resource:
        action: create
        manifest: |-
          {
            "apiVersion": "argoproj.io/v1alpha1",
            "kind": "Workflow",
            "metadata": {
              "generateName": ""hello-{{workflow.parameters.the_message}}-",
              "labels": {
                "the_message": "{{workflow.parameters.the_message}}",
                "workflow": "hello",
                "workflows.argoproj.io/workflow-template": "hello" 
              }
            },
            "spec": {
              "arguments": {
                "parameters": [
                  {
                    "name": "the_message",
                    "value": "{{workflow.parameters.the_message}}"
                  }
                ]
              },
              "entrypoint": "hello-main",
              "workflowTemplateRef": {
                "name": "hello"
              }
            }
          }
        successCondition: 'status.phase in (Failed, Error, Succeeded)'
        failureCondition: 'false'
```

**explanation :** 

we add a template named 'launcher' which is set to the entrypoint

this template just create a workflow resource, setting the expected parameters, name and labels thanks to {{workflow.parameters.xxx}}

when you submit manually, the default entrypoint launcher is proposed in the UI
 
if you set the_message to 'world', this will create a "normal" hello-xxxxx which will create a subworklow named hello-world-xxx (and this subworkflow also has labels workflow=hello, the_message=world)

here you can see a screenshot where we used 'test1' for the_message

![Capture d’écran 2021-06-10 à 17 58 06](https://user-images.githubusercontent.com/11044877/121557904-6f939900-ca15-11eb-8b69-37c3773b9c5b.png)

obviously, this is ugly because it creates a "useless" workflow when you submit from the ui (which is not the majority for us)

note that when you want to call the workflow without UI, you obviously set the entrypoint to 'main' (not to launcher) and you also set the labels and the names

if you forget to use main in this situation, you will have some kind of "inception" : your workflow would create a workflow that create a workflow 😵 

note that this is possible in my case only because we do NOT write the yaml by hand (and so , the launcher is crated automatically on behalf of the programmer)

I still hope that one day argo will natively allow to display arguments directly in the list and to search workflows by arguments 😄 

you can close the issue if you find this workaround appropriate or let it open if you plan to implement something in the future

**Comment by Lobstrosity** [comment] 2021-08-05 20:56
Appears to be a duplicate of https://github.com/argoproj/argo-workflows/issues/3434.

**Comment by alexec** [comment] 2022-01-31 21:24
Closing and duplicate.

**Closed by alexec** 2022-01-31 21:24 UTC
Labels: solution/workaround
