### ISSUE TITLE
`workflow shutdown with strategy: Terminate`, but stuck in `Running` 

### ISSUE THREAD

**Issue by zhucan** [argoproj/argo-workflows#13726] opened 2024-10-08 09:29 UTC
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

![image](https://github.com/user-attachments/assets/2cf28bb5-1556-4cb6-9600-bc4ac6b7ed1e)

workflow shutdown with strategy: Terminate， but the status of the workflow stuck running state

I expect the taskresults to be completed and the status of workflow not stuck Running state

### Version(s)

v3.5.8

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
I don't remmber how to reproduce it.
```

### Logs from the workflow controller

```text
no any errors record
```

### Logs from in your workflow's wait container

```text
no any errors record
```

**Comment by zhucan** [comment] 2024-10-08 09:30
@jswxstw  a little changes can update the status of the wf.
```
		if label == "false" && (old.IsPodDeleted() || old.FailedOrError()) {
			if recentlyDeleted(old) {
				woc.log.WithField("nodeID", nodeID).Debug("Wait for marking task result as completed because pod is recently deleted.")
				// If the pod was deleted, then it is possible that the controller never get another informer message about it.
				// In this case, the workflow will only be requeued after the resync period (20m). This means
				// workflow will not update for 20m. Requeuing here prevents that happening.
				woc.requeue()
				continue
			} else {
				woc.log.WithField("nodeID", nodeID).Info("Marking task result as completed because pod has been deleted for a while.")
				woc.wf.Status.MarkTaskResultComplete(nodeID)
			}
		}
```

**Comment by Joibel** [comment] 2024-10-08 09:31
This should be fixed in 3.5.11.

**Comment by zhucan** [comment] 2024-10-08 09:36
@Joibel Coud you paste the pr links?

**Comment by jswxstw** [comment] 2024-10-08 09:40
> @Joibel Coud you paste the pr links?

Related PR: #13491. Have you tested it with v3.5.11？@zhucan

**Comment by zhucan** [comment] 2024-10-08 09:43
the status of the pod is not "pod.Status.Reason == "Evicted" " @jswxstw

**Comment by jswxstw** [comment] 2024-10-08 09:45
> @jswxstw I had cherry-pick the pr to the v3.5.8, can not fix the problem

I'll check it out later.

**Comment by jswxstw** [comment] 2024-10-08 11:53
@zhucan Please check if you have RBAC problem(see https://github.com/argoproj/argo-workflows/pull/13537#issuecomment-2378303180), the controller will rely on `podReconciliation` which is unreliable to synchronize taskresult status if so.

The root cause may be as below:
- Node will be marked as `Failed` directly before pod is terminated when workflow is shutting down.
- The order of pod cleanup policy may be: `terminateContainers` -> `labelPodCompleted` -> `killContainers`, which causing `podReconciliation` does not work because pod has been labeled as completed, so it can not be observed by controller.

**Comment by agilgur5** [comment] 2024-10-08 15:19
> ### Version(s)
> v3.5.8

> * [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.

You checked this off, but did not test with `:latest`. This should be fixed in 3.5.11, as Alan said. This is not optional.

> I don't remmber how to reproduce it. [sic]

You also did not provide a reproduction nor logs, which makes this difficult if not impossible to investigate.

Please fill out the issue template accurately and in-full, it is there for a reason. It is not optional.

> @jswxstw I had cherry-pick the pr to the v3.5.8, can not fix the problem

I've told you this before, that means you're running a fork, and we don't support forks. You can file an issue in that fork.

**Closed by agilgur5** 2024-10-08 15:19 UTC
Labels: type/bug, area/controller, problem/more information needed, solution/outdated

**Comment by zhucan** [comment] 2024-10-08 16:16
> @zhucan Please check if you have RBAC problem(see [#13537 (comment)](https://github.com/argoproj/argo-workflows/pull/13537#issuecomment-2378303180)), the controller will rely on `podReconciliation` which is unreliable to synchronize taskresult status if so.
> 
> The root cause may be as below:
> 
> * Node will be marked as `Failed` directly before pod is terminated when workflow is shutting down.
> * The order of pod cleanup policy may be: `terminateContainers` -> `labelPodCompleted` -> `killContainers`, which causing `podReconciliation` does not work because pod has been labeled as completed, so it can not be observed by controller.

I had checked the logs of the controller, there is no rbac warning informations. @jswxstw

**Comment by zhucan** [comment] 2024-10-08 16:21
> > ### Version(s)
> > v3.5.8
> 
> > * [x]  I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
> 
> You checked this off, but did not test with `:latest`. This should be fixed in 3.5.11, as Alan said. This is not optional.
> 
> > I don't remmber how to reproduce it. [sic]
> 
> You also did not provide a reproduction nor logs, which makes this difficult if not impossible to investigate.
> 
> Please fill out the issue template accurately and in-full, it is there for a reason. It is not optional.
> 
> > @jswxstw I had cherry-pick the pr to the v3.5.8, can not fix the problem
> 
> I've told you this before, that means you're running a fork, and we don't support forks (that's not possible by definition). You can file an issue in that fork.

we coundn't always to upgrade the version to the latest when there are some bugs exists under the version; we need to know which pr fix it, not upgrade the version when there is bug. because we don't know the new version whether exists other bugs. if you couldn't help to do it, no neeed to answer the question.

**Comment by zhucan** [comment] 2024-10-08 16:43
> @zhucan Please check if you have RBAC problem(see [#13537 (comment)](https://github.com/argoproj/argo-workflows/pull/13537#issuecomment-2378303180)), the controller will rely on `podReconciliation` which is unreliable to synchronize taskresult status if so.
> 
> The root cause may be as below:
> 
> * Node will be marked as `Failed` directly before pod is terminated when workflow is shutting down.
> * The order of pod cleanup policy may be: `terminateContainers` -> `labelPodCompleted` -> `killContainers`, which causing `podReconciliation` does not work because pod has been labeled as completed, so it can not be observed by controller.

https://github.com/argoproj/argo-workflows/blob/07703ab1e5e61f1735008bf79847af49f01af817/pkg/apis/workflow/v1alpha1/workflow_types.go#L2413 Node will be marked as `Failed` directly，but the error messages is not "pod deleted" but it is "workflow shutdown with strategy: Terminate",   the status is same but error messages is not same. @jswxstw

**Comment by agilgur5** [comment] 2024-10-08 17:27
> we couldn't always to upgrade the version to the latest

The issue template asks that you, at minimum, _check_ whether `:latest` resolves your bug. If it does, your bug has already been fixed and you can search through the changelog to see what fixed it. Filing an issue would be duplicative, as it very likely is here, and invalid, as you're reporting a bug on a fork and not this repo and failing to follow the issue template in multiple places.

> when there are some bugs exists under the version; we need to know which pr fix it, not upgrade the version when there is bug. because we don't know the new version whether exists other bugs

You could say this of literally any software. Virtually all software has bugs. If you were to follow this and fork every dependency of yours, you wouldn't be doing anything other than dependency management (that is a big part of software development these days, but usually not the only thing). You're using Argo as a dependency, so if you update other dependencies to fix bugs, you would do the same with Argo.

> if you couldn't help to do it, no neeed to answer the question.

That's not how OSS works -- you filed a bug report for a fork to the origin. Your bug report is therefore invalid as this is not that fork. If you want to contribute to OSS or receive free _community_ support, you should follow the rules and norms of OSS and that community, including following issue templates.

If you want support for a fork, you can pay a vendor for that. You should not expect community support from the origin for your own fork.

**Comment by jswxstw** [comment] 2024-10-09 02:34
> Node will be marked as `Failed` directly，but the error messages is not `pod deleted` but it is `workflow shutdown with strategy: Terminate`, the status is same but error messages is not same. @jswxstw

@zhucan This is a fix for wait container exiting abnormally because of pod deletion by #13537, which is different from #13491. You can see https://github.com/argoproj/argo-workflows/pull/13537#issuecomment-2323921762 for a summary.

What `PodGCStrategy` are you using? Is it `OnWorkflowCompletion`? Please privide more information for us, one screenshot isn't enough.
