### ISSUE TITLE
Support more path syntax for `successCondition` and `failureCondition` on `resource` templates

### ISSUE THREAD

**Issue by jazka** [argoproj/argo-workflows#7143] opened 2021-11-03 14:39 UTC
## Summary

Support more syntax for successCondition and failureCondition like [gjson](https://github.com/tidwall/gjson).  The guide doc tells us the two fields use kubernetes label selection syntax and can be applied against any field of the resource (not just labels). But how to check the value of the field in set? 

## Use Cases

For PytorchJob, the status section will be used to check the job status. That means the successCondition should be set like `successCondition=status.conditions.#(type="Created").status="True"`, but this syntax is not supported. Any way to deal with the case with array struct?

```yaml
 status:
    completionTime: 2019-01-11T01:03:15Z
    conditions:
    - lastTransitionTime: 2019-01-11T00:51:48Z
      lastUpdateTime: 2019-01-11T00:51:48Z
      message: PyTorchJob pytorch-dist-mnist-gloo is created.
      reason: PyTorchJobCreated
      status: "True"
      type: Created
    - lastTransitionTime: 2019-01-11T00:57:22Z
      lastUpdateTime: 2019-01-11T00:57:22Z
      message: PyTorchJob pytorch-dist-mnist-gloo is running.
      reason: PyTorchJobRunning
      status: "False"
      type: Running
    - lastTransitionTime: 2019-01-11T01:03:15Z
      lastUpdateTime: 2019-01-11T01:03:15Z
      message: PyTorchJob pytorch-dist-mnist-gloo is successfully completed.
      reason: PyTorchJobSucceeded
      status: "True"
      type: Succeeded
    replicaStatuses:
      Master:
        succeeded: 1
      Worker:
        succeeded: 1
    startTime: 2019-01-11T00:57:22Z
```

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment] 2021-11-03 14:42
`status.replicaStatuses.Worker.succeeded > 1`

**Comment by jazka** [comment] 2021-11-03 14:57
Thanks for your response so quickly. 

Yes, we used the training-operator. 

It works with `status.replicaStatuses.Worker.succeeded > 1` for successCondition, but how to set failureCondition? I think it will wrong to check status.replicaStatuses.*.failed count, since it may failed by any master or any worker, and the master and worker could be set restarted policy.

**Comment by terrytangyuan** [comment] 2021-11-03 15:10
That will be up to your training logic, e.g. whether you've enabled elastic training.

`gjson` is actually used underneath: https://github.com/argoproj/argo-workflows/blob/9c76cc34c7591f0113dea4e35b58b902d8386544/workflow/executor/resource.go#L240-L265

You may play with the unit test to test different conditions locally: https://github.com/argoproj/argo-workflows/blob/9c76cc34c7591f0113dea4e35b58b902d8386544/workflow/executor/resource_test.go#L124-L150

**Comment by terrytangyuan** [comment] 2021-11-03 17:37
Would you like to submit a PR to support the additional syntax or make it fully compatible with gjson?

**Comment by jazka** [comment] 2021-11-04 16:08
> Would you like to submit a PR to support the additional syntax or make it fully compatible with gjson?

Sure, I could try it. 

BTW, the description of `failureCondition` should be updated on official [docs](https://argoproj.github.io/argo-workflows/fields/#templateref) . The default label selector syntax is AND, but actually its syntax is OR for `failureCondition`. 
![image](https://user-images.githubusercontent.com/7553111/140373306-6785ac9a-b2c4-4055-aa62-fb1bff311215.png)

This is very misleading if user does not check the code here.
https://github.com/argoproj/argo-workflows/blob/9c76cc34c7591f0113dea4e35b58b902d8386544/workflow/executor/resource.go#L240-L265.

**Comment by terrytangyuan** [comment] 2021-11-04 18:39
Feel free to update the docs along the way as well.

**Comment by berlinsaint** [comment] 2021-11-12 03:13
the same problem here. failureCondition should support array struct here. For example, when set tfjob pod restart policy to 
`OnFailure` and set a `backoffLimit：3`.
now if exceed the backoffLimit 3, job failed ,like this
![image](https://user-images.githubusercontent.com/10629930/141402713-353cd34d-0be5-4532-af86-f317e84772e2.png)

now,  failureCondition can't support this array struct .
BTW, we can also change operator code.....but i thinks we should. support here , in argo is more useful

**Comment by berlinsaint** [comment] 2021-11-14 11:14
according gjson , and my try......

use this fix my problem:

![image](https://user-images.githubusercontent.com/10629930/141678450-7ed0b22c-fc23-4137-bd33-84a0caa4dafe.png)
like gjson doc say..
https://github.com/tidwall/gjson

However ,some complex syntax will be conflict with  label selector syntax..
BTW, do we really need label selector syntax? i thinks jsonPath is better.. @terrytangyuan

**Comment by agilgur5** [comment] 2024-10-18 07:31
This seems to have been a duplicate of #2288 which has a decent bit more upvotes. The discussions don't exactly overlap though

**Closed by agilgur5** 2024-10-18 07:31 UTC
Labels: type/feature, area/templates/resource
