### ISSUE TITLE
Pagination doesn't always work correctly with archived workflows

### ISSUE THREAD

**Issue by jacek-jablonski** [argoproj/argo-workflows#12725] opened 2024-03-01 08:53 UTC
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Workflows pagination to work correctly.

It seems like pagination works very randomly. But most of the time `Next Page` button is just disabled.
https://github.com/argoproj/argo-workflows/assets/35669512/df7a1666-47fd-4a6a-98e8-7d20768287e6

### Version

v3.5.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
N/A
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```

**Comment by terrytangyuan** [comment] 2024-03-01 14:40
Likely https://github.com/argoproj/argo-workflows/issues/12025

**Comment by agilgur5** [comment] 2024-03-01 15:45
> Likely #12025

Or #11715 rather. But it's not clear if archived workflows are being used here. @jacek-jablonski are you using archived workflows? Can you provide your Controller ConfigMap?

> v3.5.5

Also did you mean to file this as a regression? Was it working in v3.5.4? If so, then #12672 and related code would be suspect (although I had to test pagination in order to fix that)

**Comment by jacek-jablonski** [comment] 2024-03-01 21:56
Archived workflows are being used.
In v3.5.4 workflows list behaved exactly the same, so no regression since v3.5.4.

Here is my controller ConfigMap:

```
config: |
  artifactRepository:
    archiveLogs: true
    gcs:
      bucket: xxx
  metricsConfig:
    enabled: true
    path: /metrics
    port: 9090
    ignoreErrors: false
    secure: false
  persistence:
    archive: true
    archiveTTL: 14d
    postgresql:
      database: argo_workflows
      host: localhost
      passwordSecret:
        key: password
        name: argo-workflows-postgres-credentials
      port: 5432
      tableName: argo_workflows
      userNameSecret:
        key: username
        name: argo-workflows-postgres-credentials
  retentionPolicy:
    completed: 10
    errored: 3
    failed: 3
  nodeEvents:
    enabled: true
```

**Comment by agilgur5** [comment] 2024-03-02 04:33
Thanks for the additional info. This would indeed be a duplicate of #11715, which is very closely related to #12025.
Basically the API is currently overfetching by a factor of 2x the page limit; 1x in-cluster live workflows + 1x archived workflows, but it only keeps a single cursor for live workflows as the offset. So that makes pagination a bit wacky; effectively you're only paging through live workflows but archived ones are thrown on top in addition almost like extras.

**Closed by agilgur5** 2024-03-02 04:33 UTC
Labels: bug, area/api, area/workflow-archive, P2, duplicate, area/server
