### ISSUE TITLE
gRPC message too large when getting status of a very large workflow

### ISSUE THREAD

**Issue by ebr** [argoproj/argo-workflows#4576] opened 2020-11-20 17:47 UTC
## Summary 

Trying to get details on a very large workflow after it progresses beyond a certain point (unclear what that point is), returns a message:

`FATA[0004] rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (113030693 vs. 104857600)`

This workflow is offloaded, and current progress (retrieved by `kubectl get wf -o yaml`) is `progress: 26372/27798`.

Communication with the server is via `kubectl port-forward`; we are using `ARGO_TOKEN="" ARGO_SERVER=127.0.0.1:2746 argo get ${workflow}` to get status of offloaded workflows.

## Diagnostics

What Kubernetes provider are you using? 

`docker`

What version of Argo Workflows are you running? 

client: `2.12.0rc2`
controller: `2.12.0 ??` engineering build (`:mot`)
server: `2.12.0rc2`

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment] 2020-11-20 18:54
Duplicate of #4529

**Closed by alexec** 2020-11-20 18:54 UTC
