### ISSUE TITLE
V3: In namespaced mode, Argo UI's /workflows tries to serve all workflows across the cluster

### ISSUE THREAD

**Issue by Radolumbo** [argoproj/argo-workflows#5577] opened 2021-04-02 00:35 UTC
## Summary 

What happened/what you expected to happen?
In Argo v2, in namespaced server mode, going to /workflows in the Argo UI served only the workflows for the corresponding namespace of the server you're connected to. In v3, it appears to serve the workflows across the cluster, even though you're connecting to the server of a specific namespace. This forces you to go to /workflows/namespace to view your workflows if you are not permissioned to view workflows in the cluster. Before, it wasn't even possible to view cluster-wide workflows in namespaced mode, which I think is the more expected behavior.

Is this behavior intentional? Did something change about how routes are served?

## Diagnostics
What version of Argo Workflows are you running? 
v3.0.0

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment] 2021-04-02 16:46
Can I please request...

* Screenshot.
* Contents of `localStorage`, found in Javascript console. Looks like:

```
Storage {managedNamespace: "argo", loglevel:webpack-dev-server: "INFO", ListOptions/options: "{"selectedPhases":[],"selectedLabels":[],"paginationLimit":500}", current_namespace: "", length: 4}
```

**Comment by Radolumbo** [comment] 2021-04-02 17:05
E.G. 
<img width="917" alt="Screenshot 2021-04-02 125956" src="https://user-images.githubusercontent.com/3118655/113437106-07d92600-93b4-11eb-8b54-2e94a98d5a3d.png">

```
Storage {managedNamespace: "s-workflow-platform", ListOptions/options: "{"selectedPhases":[],"selectedLabels":[],"paginationLimit":500}", current_namespace: "", length: 3}
ListOptions/options: "{"selectedPhases":[],"selectedLabels":[],"paginationLimit":500}"
current_namespace: ""
length: 3
managedNamespace: "s-workflow-platform"
__proto__: Storage
```

**Comment by Radolumbo** [comment] 2021-04-02 17:06
When I browse to the base URL, it auto redirects me to /workflows/s-workflow-platform

But I can manually delete the namespace name, whereupon it will serve (or attempt to, if I'm not permissioned) all workflows in the cluster.  My expectation would be that there is no way to view cluster-wide workflows from a namespaced server, which is how it behaved in V2.

**Comment by hadim** [comment] 2021-04-04 14:28
I see the same error.

**Comment by alexec** [comment] 2021-04-04 17:12
This needs to be fixed here:

https://github.com/argoproj/argo-workflows/blob/master/ui/src/app/workflows/components/workflows-list/workflows-list.tsx#L198

Basically we need to check to see if managed namespace is set.

Would anyone like to submit a PR?

**Comment by Radolumbo** [comment] 2021-04-06 00:26
Are you suggesting that we just filter down to the managed namespace on all fetchWorkflow calls?

To go in hand with this, we should probably also change the redirect from base URL to just go to /workflows/ when there is a managed namespace, too, right?

**Comment by alexec** [comment] 2021-04-06 00:31
Either that - or there's a bug in app-router?

**Comment by Radolumbo** [comment] 2021-04-06 00:37
I just edited my like 30 seconds ago so not sure if you saw it -- but I linked where I think this might be happening https://github.com/argoproj/argo-workflows/blob/master/ui/src/app/app-router.tsx#L167 .. if any namespace is set, which will always be true I think since we have a managed namespace in this case .. it directs there.

So perhaps we should update it to just redirect to /workflows if we're in managed-namespace mode and then add the logic to filter workflows where you linked. What say you to that?

**Comment by alexec** [comment] 2021-04-06 16:00
I wonder if the order of those elements is important and the redirect should be top of the list?

**Comment by alexec** [comment] 2021-04-15 15:35
Bump! @Radolumbo are you still investigating?

**Comment by Radolumbo** [comment] 2021-04-15 17:00
I definitely still intend on coming back to this! I've been on vacation for the last week so haven't had a chance. If someone else feels like they want to make the fix they can, else I'll be working on it next week!

**Comment by alexec** [comment] 2021-04-17 21:50
Related:

fix(ui): Fix editor. Fixes #5613 Fixes #5617 (#5620)

**Comment by alexec** [comment] 2021-04-17 21:50
I think this *may* have been fixed on master.

**Comment by Radolumbo** [comment] 2021-04-19 16:54
I'll test it out in a bit, and see!

**Comment by Radolumbo** [comment] 2021-04-20 01:27
I'm still seeing the same behavior.

**Comment by alexec** [comment] 2021-04-20 14:57
I could not reproduce this. Can anyone volunteer to debug via Zoom?

**Comment by Radolumbo** [comment] 2021-04-20 16:17
I could do so. I just got back to looking at this, and I think I understand what's happening, though I haven't decided exactly the best way to approach it, yet.

**Comment by Radolumbo** [comment] 2021-04-20 20:41
I should at least have a draft PR soon for one way we can approach this. I think it's a little hacky, but it's similar to what was being done in V2, and should at least start a discussion.

**Comment by Radolumbo** [comment] 2021-04-21 14:17
Please see https://github.com/argoproj/argo-workflows/pull/5729

**Closed** 2021-04-23 23:21 UTC
Labels: P3, bug, workaround
