### ISSUE TITLE
multiprocessing when saving an artifact back to S3 (wait container)

### ISSUE THREAD

**Issue by ldejuan** [argoproj/argo-workflows#9022] opened 2022-06-22 13:01 UTC
# Summary
When the result artifact is a directory with an extreme large number of files (> 1million) of size ~10k, the saving back to the S3 buckets **not in  compressed** mode is very **slow** ~300ms/file. The enhancement will be to execute this saving (done by the **wait** container) in a multi-process mode.    

# Use Cases
It is useful when saving an artifact to S3 made of **millions** of single files, because the files must be exposed in raw and not over a compressed tarball. 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by DocX** [comment] 2022-10-11 15:38
This looks like duplicate of https://github.com/argoproj/argo-workflows/issues/4014

**Comment by tooptoop4** [comment] 2024-09-30 19:57
@shuangkun did a recent PR cover this?

**Comment by shuangkun** [comment] 2024-10-02 07:15
> @shuangkun did a recent PR cover this?

Do you mean muti-upload, i can try it

**Comment by ldejuan** [comment] 2024-10-02 08:34
Hi ShuangkunYes it is exactly that. Uploading multi artifacts to the S3 takes to much time since the current method is not multi-processes. The Minio lib does it, but it is not a very good method to create a component that writes directly to the S3 bucket, it should be handle by Argo. Regards LuisEnvoyé depuis mon téléphone-------- Message original --------De : shuangkun tian ***@***.***>Date : mer. 2 oct. 2024 à 09:15À : argoproj/argo-workflows ***@***.***>Cc : Luis de Juan ***@***.***>, Author ***@***.***>Objet : Re: [argoproj/argo-workflows] multiprocessing when saving an artifact back to S3 (wait container) (Issue #9022)

@shuangkun did a recent PR cover this?

Do you mean muti-upload, i can try it

**Comment by agilgur5** [comment] 2024-10-16 02:51
Duplicate of #4014 and superseded by #12442

**Closed by agilgur5** 2024-10-16 02:51 UTC
Labels: type/feature
