### ISSUE TITLE
cannot use 'continueOn' when using 'depends'. Instead use 'dep-task.Failed'/'dep-task.Errored'

### ISSUE THREAD

**Issue by preethidh** [argoproj/argo-workflows#9709] opened 2022-09-29 07:17 UTC
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I am trying to skip failures and move to next stage. But when i try same i am getting " cannot use 'continueOn' when using 'depends'. Instead use 'dep-task.Failed'/'dep-task.Errored'" error.
I referred - https://github.com/argoproj/argo-workflows/blob/master/examples/continue-on-fail.yaml  

### Version

v3.3.2

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
NA
```

### Logs from the workflow controller

kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

### Logs from in your workflow's wait container

kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

**Comment by tczhao** [comment] 2024-04-12 03:18
> Because of the added control found in depends, the dag.task.continueOn is not available when using it. Furthermore, it is not possible to use both dependencies and depends in the same task group.
https://github.com/argoproj/argo-workflows/blob/main/docs/enhanced-depends-logic.md

This is by design, let us know if there's functionality you want to achieve using both `continueOn` and `depends`

closing for now

**Closed by tczhao** 2024-04-12 03:18 UTC
Labels: type/bug, P3
