### ISSUE TITLE
Ability to duplicate a workflow and change only what we want in the UI

### ISSUE THREAD

**Issue by cscetbon** [argoproj/argo-workflows#10809] opened 2023-04-03 21:10 UTC
# Summary

What change needs making?

We would like to be able to resubmit a workflow but change some parameters

# Use Cases

When would you use this?

We want to resubmit a workflow but just change one parameter and copy/pasting from one to another always introduce spaces that are missed and make our workflows fail

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment] 2023-04-06 20:21
Duplicate to https://github.com/argoproj/argo-workflows/issues/10824?

**Comment by cscetbon** [comment] 2023-04-21 05:09
> Duplicate to https://github.com/argoproj/argo-workflows/issues/10824?

It doesn't seem to be the same. In short what I'm saying is I'd like to resubmit a workflow but overwrite some of its parameters. In the UI it would get opened with all the previous parameters' values and allow me to change whatever I want before it gets actually resubmitted.

**Comment by jburke-godaddy** [comment] 2023-04-25 00:42
👍

**Comment by agilgur5** [comment] 2023-09-01 14:38
I believe this was indeed a duplicate of #10824, just that #10824 has no description and so required interpretation.

#11083 added functionality for this and was released with 3.5.0

**Closed** 2023-09-01 14:39 UTC
Labels: enhancement, area/ui
