### ISSUE TITLE
link to argoCD

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#10020] opened 2022-11-12 06:13 UTC
argoWorkflows users will often also use argoCD
idea is to have a link on the specific object (ie cronworkflowXYZ, workflowtemplateABC) that will open up that object in argoCD UI
benefit is that it would link back to commit details, also show deployment errors (ie in case new version of object was not being reflected in argoWorkflows)

basic implementation idea:
optional config for argoCD base URL
ui change to show that argoCD href link on each relevant object in argoWorkflows

**Comment by gitsan13** [comment] 2022-11-14 13:47
Hi 
Will you be accepting a PR request for this?
I would like to contribute to this enhancement:)

**Comment by tooptoop4** [comment] 2022-11-14 19:04
yes @gitsan13

**Comment by caelan-io** [comment] 2022-11-15 18:16
duplicate of #7912 I believe. There should be a presentation about this new plugin in an upcoming Argo Workflows community meeting.

See this repo for now: https://github.com/crenshaw-dev/argocd-executor-plugin

**Comment by crenshaw-dev** [comment] 2022-11-16 15:03
This request sounds more UI-oriented, something my plugin can't do.

> optional config for argoCD base URL

You'll need more information to construct a link to the resource. Specifically, you'll need the name of the Application which manages the resource, and the namespace in which that Application is installed (both used to construct the Argo CD application URL). That information might be available in a [tracking annotation on the resource](https://argo-cd.readthedocs.io/en/stable/user-guide/resource_tracking/#additional-tracking-methods-via-an-annotation).

**Comment by tooptoop4** [comment] 2023-06-09 23:17
maybe https://argoproj.github.io/argo-workflows/links/ does this?

**Closed** 2024-09-30 21:22 UTC
Labels: type/feature, area/ui
