### ISSUE TITLE
maxDuration broken in v2.9.4

### ISSUE THREAD

**Issue by fabio-rigato** [argoproj/argo-workflows#3655] opened 2020-08-03 06:31 UTC
Hey all (@simster7 @alexec ),

I'm facing a weird issue after upgrading to v2.9.4 from v2.9.2.

Argo version: 2.9.4

Maybe the issue comes from v2.9.3 with the PR [#3477](https://github.com/argoproj/argo/pull/3477)

retryStrategy:
      limit: 4
      retryPolicy: "Always"
      backoff:
        duration: "12s"
        factor: 5
        maxDuration: "200m"

I'm reaching the "**Max duration limit exceeded**" error even if the sum of backoff time is < then maxDuration value.

Could you please double-check de logic?

Cheers,
Fabio

**Comment by simster7** [comment] 2020-08-03 15:32
Can you attach a full Workflow object where this happen? You can get it by running `kubectl get wf <NAME> -o yaml`. It's difficult to diagnose this issue without it.

**Comment by fabio-rigato** [comment] 2020-08-03 23:01
Hey @simster7 thanks for your quick answer!

I shared with you in slack the yaml file and a screenshot of argo get result.
Please, let me know if you need any more information from me.
Cheers,
Fabio

**Comment by simster7** [comment] 2020-08-06 15:58
Duplicate of #3665

**Closed by simster7** 2020-08-06 15:58 UTC
