### ISSUE TITLE
`BASE_HREF=/argo/` sub path routing gives blank page running behind ingress-nginx proxy

### ISSUE THREAD

**Issue by tbernacchi** [argoproj/argo-workflows#13407] opened 2024-07-27 22:38 UTC
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

I'm not able to open the UI for argo-workflow, if I `curl` it gives me `200`:

```
~|⇒ curl -o /dev/null -w "%{http_code}\n" -s -k https://mykubernetes.com/argo/
200
```

but when I try to open in a browser it gives me a blank page. 

Inspecting the page there is this message: `Uncaught SyntaxError: Unexpected number`.

<img width="1312" alt="Screenshot 2024-07-27 at 7 22 08 pm" src="https://github.com/user-attachments/assets/8668c3ea-6e81-4796-a4de-ecca150b1582">

### Version(s)

`v3.5.8`

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```
kubectl create namespace argo
kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.5.8/install.yaml
```

```
kubectl set env deployment/argo-server -n argo BASE_HREF=/argo/
```

### Logs from the workflow controller
```
kubectl logs -n argo deploy/workflow-controller 
time="2024-07-27T22:32:52Z" level=info msg="index config" indexWorkflowSemaphoreKeys=true
time="2024-07-27T22:32:52Z" level=info msg="cron config" cronSyncPeriod=10s
time="2024-07-27T22:32:52Z" level=info msg="Memoization caches will be garbage-collected if they have not been hit after" gcAfterNotHitDuration=30s
time="2024-07-27T22:32:52.327Z" level=info msg="not enabling pprof debug endpoints"
time="2024-07-27T22:32:52.477Z" level=info msg="Configuration:\nartifactRepository: {}\ninitialDelay: 0s\nmetricsConfig: {}\nnodeEvents: {}\npodSpecLogStrategy: {}\nsso:\n  clientId:\n    key: \"\"\n  clientSecret:\n    key: \"\"\n  issuer: \"\"\n  redirectUrl: \"\"\n  sessionExpiry: 0s\ntelemetryConfig: {}\n"
time="2024-07-27T22:32:52.477Z" level=info msg="Persistence configuration disabled"
time="2024-07-27T22:32:52.477Z" level=info executorImage="quay.io/argoproj/argoexec:v3.5.8" executorImagePullPolicy= managedNamespace=
time="2024-07-27T22:32:52.489Z" level=info msg="Starting dummy metrics server at localhost:9090/metrics"
I0727 22:32:52.494845       1 leaderelection.go:248] attempting to acquire leader lease argo/workflow-controller...
time="2024-07-27T22:32:52.506Z" level=info msg="new leader" leader=workflow-controller-76ffbdcf8f-d5q9q
time="2024-07-27T22:33:16.497Z" level=info msg="new leader" leader=workflow-controller-76ffbdcf8f-nhx6v
I0727 22:33:16.497629       1 leaderelection.go:258] successfully acquired lease argo/workflow-controller
time="2024-07-27T22:33:16.498Z" level=info msg="Successfully shutdown dummy metrics server at localhost:9090/metrics"
time="2024-07-27T22:33:16.503Z" level=info msg="Starting prometheus metrics server at localhost:9090/metrics"
time="2024-07-27T22:33:16.505Z" level=info msg="DB migration is disabled"
time="2024-07-27T22:33:16.505Z" level=info msg="Starting Workflow Controller" defaultRequeueTime=10s version=v3.5.8
time="2024-07-27T22:33:16.505Z" level=info msg="Current Worker Numbers" podCleanup=4 workflowTtlWorkers=4 workflowWorkers=32
time="2024-07-27T22:33:16.508Z" level=info msg="Watching task results" labelSelector="!workflows.argoproj.io/controller-instanceid,workflows.argoproj.io/workflow"
time="2024-07-27T22:33:16.512Z" level=info msg=Plugins executorPlugins=false
time="2024-07-27T22:33:16.536Z" level=info msg="Manager initialized successfully"
time="2024-07-27T22:33:16.544Z" level=info msg="Received Workflow Controller config map argo/workflow-controller-configmap update"
time="2024-07-27T22:33:16.578Z" level=info msg="Configuration:\nartifactRepository: {}\ninitialDelay: 0s\nmetricsConfig: {}\nnodeEvents: {}\npodSpecLogStrategy: {}\nsso:\n  clientId:\n    key: \"\"\n  clientSecret:\n    key: \"\"\n  issuer: \"\"\n  redirectUrl: \"\"\n  sessionExpiry: 0s\ntelemetryConfig: {}\n"
time="2024-07-27T22:33:16.578Z" level=info msg="Persistence configuration disabled"
time="2024-07-27T22:33:16.578Z" level=info executorImage="quay.io/argoproj/argoexec:v3.5.8" executorImagePullPolicy= managedNamespace=
time="2024-07-27T22:33:16.694Z" level=info msg="Performing periodic GC" periodicity=5m0s
time="2024-07-27T22:33:16.694Z" level=info msg="Persistence disabled - so archived workflow GC disabled - you must restart the controller if you enable this"
time="2024-07-27T22:33:16.695Z" level=info msg="Starting CronWorkflow controller"
time="2024-07-27T22:33:16.695Z" level=info msg="Starting workflow garbage collector controller (retentionWorkers 4)"
time="2024-07-27T22:33:16.695Z" level=info msg="Started workflow garbage collection"
W0727 22:33:16.696077       1 shared_informer.go:401] The sharedIndexInformer has started, run more than once is not allowed
```

**Comment by tbernacchi** [comment] 2024-07-28 00:23
My ingress:

```
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: self-signed
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  name: argo-server
  namespace: argo
spec:
  ingressClassName: nginx
  rules:
  - host: mykubernetes.com
    http:
      paths:
      - backend:
          service:
            name: argo-server
            port:
              number: 2746
        path: /argo(/|$)(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - mykubernetes.com
    secretName: my-kubernetes-cert
```

**Comment by tico24** [comment] 2024-07-29 08:40
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-server
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - path: /argo(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: argo-server
            port:
              name: web
  tls:
  - hosts:
    - localhost
    secretName: tls.localhost
```

This yaml in our ci example works fine. https://github.com/pipekit/argo-workflows-ci-example/blob/main/bootstrap/argo-workflows/ingress.yaml

The key differences being we are not forcing a ssl redirect and we are using regex to make the regex be regex.

**Comment by tico24** [comment] 2024-07-29 16:14
Looks to not be a workflows issue according to the slack thread. Closing

https://cloud-native.slack.com/archives/C01QW9QSSSK/p1722126308664249

**Closed by tico24** 2024-07-29 16:14 UTC
Labels: solution/duplicate, area/server, type/support

**Comment by agilgur5** [comment] 2024-07-30 02:31
> and we are using regex to make the regex be regex.

I also noticed the `Ingress` seemed to be missing the `use-regex` annotation, unlike the NGINX Ingress Controller's [own documentation for rewrites](https://kubernetes.github.io/ingress-nginx/examples/rewrite/).
And yes, Argo's own CI has many E2E tests against the Server, so it 100% works. The `Ingress` configuration is also not part of Argo's own manifests, so entirely out of the control of Argo.

<hr>

OP commented on [old Slack threads](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1722127248009079?thread_ts=1711445082.180069&cid=C01QW9QSSSK) and several closed issues (https://github.com/argoproj/argo-workflows/issues/10290#issuecomment-2254276869, https://github.com/argoproj/argo-workflows/issues/3080#issuecomment-2254261263, plus "same" with no context to comments made 4+ years ago on much older versions on long closed issues like https://github.com/argoproj/argo-workflows/issues/716#issuecomment-2254273582, https://github.com/argoproj/argo-workflows/issues/10194#issuecomment-2254288074). OP even DM'd me...
In nearly all of those issues, they are tagged as `type/support` and _not_ `type/bug`, and many, many users there wrote how they resolved their misconfigurations. In fact, I have yet to see a case of something like this that _isn't_ a misconfiguration; the only one that isn't `type/support` is the ones that documented and added the `BASE_HREF` feature.

Please note that in the "Create an Issue" and in the issue templates themselves, it very explicitly says that issues are not for support (they are for bugs and features) and directs you to Discussions and Slack for support. Please follow the instructions and standard OSS best practices, conventions, and common courtesies. Spamming "same" with no details or context on closed 4 year old issues is discouraged, same as "+1" (in general, saying "same" with no details is discouraged, you can just upvote. but in the case of a 4+ year old issue, it's rare that it's even related at that point, opening a new issue is better. in this case, this is a misconfiguration though, not a bug, so you can open a new discussion or Slack thread, which is where Tim responded to you.).
