### ISSUE TITLE
Visualise the WorkflowTemplate in the UI without submitting a Workflow

### ISSUE THREAD

**Issue by Ezzmo** [argoproj/argo-workflows#12213] opened 2023-11-16 12:05 UTC
# Summary

Currently, the UI does not show the complete graph for workflows unless the tasks/steps are scheduled. A visual representation of the workflow in the UI would go a long way. This was a blocker for convincing developers to adopt Argo Workflows

## Use Cases

Visual representation of Workflow templates would be beneficial for people who are not familiar with that template. The only option right now is to view the manifest. 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment] 2023-11-16 15:16
Duplicate of #8646

**Closed by agilgur5** 2023-11-16 15:16 UTC
Labels: area/ui, area/workflow-templates, solution/duplicate
